### ISSUE TITLE
Document replacement for deprecated functions

### ISSUE THREAD

**Issue by Holzhaus** [taglib/taglib#1001]
Since the latest release, i get warnings like these:

```
warning: ‘bool TagLib::ByteVector::isNull() const’ is deprecated [-Wdeprecated-declarations]
```

The documentation and the changelog state that this function is deprecated, but don't mention any replacement or alternative. What is the best way to resolve these warnings?

**Comment by ufleisch** [comment]
When looking at how `TagLib::String` and `TagLib::ByteVector` are used in the library, you can use an empty string or byte vector where a null element was used, i.e. TagLib no longer makes a difference between `isNull()` and `isEmpty()` as it is done in Qt.

**Comment by ufleisch** [comment]
I just went through all uses of the `\deprecated` doxygen command in the source code, and there is always a hint with `\note`, `\see`, direclty with `\deprecated`, a `BIC:` comment or another non deprecated overload, so I am regarding this as solved.
