### ISSUE TITLE
MP3: Can't see Album art on Windows Media Player

### ISSUE THREAD

**Issue by hyperpixel34** [taglib/taglib#1002]
Hello,

I can't see the Album Art on Windows Media Player, but I can see it on VLC.
I'm using this Code:

` TagLib.File trackFile = TagLib.File.Create($"{path.Text}\\" + RemoveIllegalCharacters(title) + ".mp3");
  Picture picture = new Picture($"{path.Text}\\maxresdefault.jpg");
  picture.Type = PictureType.FrontCover;
  picture.MimeType = "image/jpeg";
  trackFile.Tag.Pictures = new TagLib.IPicture[1] { picture };
  trackFile.Save();`

Hope you can help me

**Comment by ufleisch** [comment]
You probably want to go to [TagLib#](https://github.com/mono/taglib-sharp).
