### ISSUE TITLE
Error when trying to load `Ogg` file type.

### ISSUE THREAD

**Issue by apoorv569** [taglib/taglib#1003]
I'm getting an error when I try to load `ogg` file,
```
TagLib: Vorbis::File::read() - Could not find the Vorbis comment header.
```
Do I need to import some header file to fix this?

**Comment by scotchi** [comment]
No, that would be a compile time warning.  This is referring to [Vorbis headers](https://xiph.org/vorbis/doc/v-comment.html).  It usually indicates a file that's corrupt.
