### ISSUE TITLE
Update macOS Build Documentation/Defaults?

### ISSUE THREAD

**Issue by bdkjones** [taglib/taglib#1005]
`install.md` currently talks about building a "Universal Binary" targeting macOS 10.4. That version of macOS was current 16 years ago.

"Universal Binary" itself no longer refers to a PPC/Intel binary but rather to an `x86_64/arm64` binary. Perhaps the build docs (and the default settings) could be updated to reference modern versions of macOS?

It's certainly commendable that taglib has lived such a long life, but examples that are 16 years old just aren't relevant. People have to google how to build taglib on modern systems because the docs are so dated. Thanks!

**Comment by bdkjones** [comment]
In case it helps others, I used the settings below. I'm running on macOS 11.2.3, with Xcode 12.4 on an M1 Mac. 

After building with these settings, I swapped the architecture to `x86_64`, built taglib on an Intel Mac, then used `lipo` to create a universal framework.

```
cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_FRAMEWORK=ON \
      -DCMAKE_C_COMPILER=/usr/bin/clang \
      -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
      -DCMAKE_OSX_SYSROOT=`xcode-select --print-path`/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/ \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
      -DCMAKE_OSX_ARCHITECTURES="arm64"
```

(From: https://brendonjustin.com/2015/10/18/using-taglib-xcode-7/)

Clang threw out a warning:

<img width="1190" alt="Screen Shot 2021-03-21 at 16 27 15" src="https://user-images.githubusercontent.com/926566/111924550-73410080-8a62-11eb-8d53-7e0aa01fd0a9.png">

**Comment by scotchi** [comment]
On the Swift Module Map stuff, I'd encourage you to file a pull request.  I don't think any of the TagLib developers work with Swift, so it's not something that we have any clue about.

(And, as a funny sidenote, that file was created many years after the first TagLib release.  Work on TagLib started before OS X had even been released.  ;-) )
