### ISSUE TITLE
Invalid MPEG file can be handled better?

### ISSUE THREAD

**Issue by fillobotto** [taglib/taglib#1007]
This mp3 file cannot be opened with Taglib.
However, after removing the first byte using HxD, I am able to open and edit it with Taglib as well.
Can this kind of junk be handled better? It looks like online mp3 downloaders often have this problem.

[Bastille - Send Them Off! [mp3clan].zip](https://github.com/taglib/taglib/files/6236747/Bastille.-.Send.Them.Off.mp3clan.zip)

**Comment by ufleisch** [comment]
I do not see extraordinary problems with this file, the properties and tags of the file can be read and written.

```
examples/tagreader ~/Downloads/Bastille.mp3
******************** "Bastille.mp3" ********************
TagLib: MPEG::Header::parse() -- MPEG header did not match MPEG synch.
-- TAG (basic) --
title   - ""
artist  - ""
album   - ""
year    - "0"
comment - ""
track   - "0"
genre   - ""
-- TAG (properties) --
-- AUDIO --
bitrate     - 320
sample rate - 44100
channels    - 2
length      - 3:21
```

The file has many problems, I suggest that you repair it using [Mp3Diags](http://mp3diags.sourceforge.net) or a similar tool. However, it is not TagLib's purpose to repair MP3 files.
