### ISSUE TITLE
[ Question ] Adding Taglib as a submodule to a project.

### ISSUE THREAD

**Issue by apoorv569** [taglib/taglib#1015]
Hi, I have project that I'm working on, here is the link to the repository - https://gitlab.com/samplehive/sample-hive

I was wondering if I can add `Taglib` as a `submodule` for my project, as I want to make sure all users use the version `1.12` and some distributions like `Ubuntu` and `Debian` does not seem to have the required version in their repositories. Was asking if there is an licensing or some other issue or not? My project is licensed under `GPL v3`.

Thanks.

**Comment by ufleisch** [comment]
As you can see in the sources, the project is dual licensed under the GNU Lesser General Public License version 2.1 and the Mozilla Public License Version 1.1, so this should not be a problem. Alternatively, you could consider building TagLib as a static library and linking it to your project.

**Comment by scotchi** [comment]
Note that Ubuntu and Debian packagers will probably undo your static linking of the project in their packages, however, as that's their policy.
