### ISSUE TITLE
Support WAVE_FORMAT_MULAW

### ISSUE THREAD

**Issue by igaspard** [taglib/taglib#1023]
I have issues that a wav file format is **WAVE_FORMAT_MULAW**.
Look like we can't support it well and got the below error message.
So it jump out of the `RIFF::WAV::Properties::read()` without have the sampleRate, bitrate, ... etc filled.
Look at the WAV spec, there are WAVE_FORMAT_ALAM & WAVE_FORMAT_MULAW didn't supported in this library.
Any chance we could have it?

`TagLib: RIFF::WAV::Properties::read() - Non-PCM format (7), but 'fact' chunk not found.`

**Comment by ufleisch** [comment]
If you try to parse the example WAV files from http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Samples.html you will see that also the audio properties for files with μ-law are correctly parsed by TagLib, see for instance addf8-mulaw-GW.wav, M1F1-mulaw-AFsp.wav, M1F1-mulawWE-AFsp.wav. There are also two files (Pmiscck.wav, Ptjunk.wav) which cannot be parsed and where the mentioned log output `TagLib: RIFF::WAV::Properties::read() - Non-PCM format, but 'fact' chunk not found` is printed. However, these two files are titled as *Perverse Files, The following WAVE files are perverse or have problems*, so your file is likely to belong to this category too. A missing `fact` chunk  might mean missing information and is probably required, see [Multimedia Programming Interface and Data Specifications 1.0](https://www.aelius.com/njh/wavemetatools/doc/riffmci.pdf):

> The “fact” chunk is required if the waveform data is contained in a “wavl” LIST chunk and for all
> compressed audio formats.
