### ISSUE TITLE
taglib speed difference in first and second time of loading files

### ISSUE THREAD

**Issue by MBSadeghzadeh** [taglib/taglib#1028]
I have about 1464 mp3 files on a HDD, windows 10, 16G RAM, with Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz processor. 
I built taglib by MingW with default configs and run tagreader example. It needs about 20 seconds to read tags of all those files for first time and for second time it loads tags very fast in just a second. How this difference is possible? how can I disable such mechanism in taglib? I want to evaluate speed of taglib without caching or something else.

**Comment by scotchi** [comment]
This is disk caches.  Again, please stop using our bug tracking system for general programming questions.

**Comment by scotchi** [comment]
To be a little bit more clear here:  this has nothing to do with TagLib.  This is simply the OS (which all OSes do) caching disk access. 

https://taglib.org/ has links to our mailing list, or honestly, StackOverflow is also an appropriate place for general development questions.

I'm definitely being somewhat curt here, but the issue tracking system is meant to be a place to discuss bugs in TagLib, and so far, all of the issues you've raised are more general development questions.  There's nothing wrong with your questions per se, but they honestly don't have anything to do with TagLib -- they're general issues one encounters in learning more about systems programming.  Our mailing list is read by dozens of developers using TagLib, whereas the issue tracking system is just managed by a small set of people that contribute to core TagLib development.
