### ISSUE TITLE
Possible heap corruption using to8Bit()...?

### ISSUE THREAD

**Issue by Gazoo101** [taglib/taglib#1030]
First and foremost, thank for making TagLib, looks exactly what I've been searching for, for a while. On to the issue -

I'm beyond puzzled. I'm using TagLib on windows installed via vcpkg, and I'm encountering what appears to be heap corruption issues. I submit the following code below:
```
auto pathAsString = pathFileMp3.string();
TagLib::FileRef tagLibFileRef( pathAsString.c_str() );

TagLib::String artist = tagLibFileRef.tag()->artist();
std::string test3 = artist.to8Bit( true );  // works fine - everyone is happy
std::string test4;
test4 = artist.to8Bit( true ); // Expression: __acrt_first_block == header (heap corruption?!)
```
Having searched the issues backlog I thought perhaps I was linking to the wrong library (Release while in debug or vice versa), so I opted to build TagLib on my own, circumventing vcpkg. Same exact behavior.

I'm pretty confounded as to what's going on. Any ideas...?

**Comment by scotchi** [comment]
There's nothing that obviously looks wrong to me in there, but it's also very unlikely to be a TagLib bug as that code path has been in wide use and untouched since 2013.  Can you try running the test suite to see if it works?  We'd need more info (e.g. a test program or something) to be able to do something useful with this one.

**Comment by Gazoo101** [comment]
I ran the test examples, compiled an empty project with TagLib and later also one with the framework I'm using (Cinder) and TagLib too. The issue only occurs with the last of the three. A kind soul on the frameworks forum pointed my attention to this:

https://stackoverflow.com/questions/22797418/how-do-i-safely-pass-objects-especially-stl-objects-to-and-from-a-dll/22797419#22797419

I.e. some combination of differing compiler settings when using the library is causing issues.

More importantly though, it would appear that passing STL objects to / from a DLL is riddled with dangers. Or at the very least more error-prone than C primitives. I'll make use of the TagLib `toCString()` function to avoid this beehive! Thanks for the help @scotchi !
