### ISSUE TITLE
Using taglib as a meson subproject.

### ISSUE THREAD

**Issue by apoorv569** [taglib/taglib#1031]
I am trying to make `taglib` as `meson subproject`. I made a sub directory in the project root directory called `subprojects` and made a `taglib.wrap` file.

```
[wrap-git]
url = https://github.com/taglib/taglib.git
revision = master
```

and I have this section in my `meson.build` file for pulling `taglib` from this repository,

```
# Import CMake
cmake = import('cmake')
cmake_opts = cmake.subproject_options()
cmake_opts.add_cmake_defines({'CMAKE_POSITION_INDEPENDENT_CODE': 'ON',
                              'CMAKE_INSTALL_PREFIX': prefix,
                              'CMAKE_BUILD_TYPE': 'Release',
                              'CMAKE_CXX_COMPILER': 'g++'})

taglib = dependency('taglib', version: '>=1.12', required: false)
if not taglib.found()
  taglib_subproject = cmake.subproject('taglib', options: cmake_opts)
  taglib = taglib_subproject.dependency('taglib')
endif
```

but when I try to build the project I get this error,

```
meson.build:89:2: ERROR: The CMake target taglib does not exist
  Use the following command in your meson.build to list all available targets:

    message('CMaket targets:\n - ' + '\n - '.join(<cmake_subproject>.target_list()))
```

So I added this line in my `meson.build` file,
```
message('CMaket targets:\n - ' + '\n - '.join(taglib_subproject.target_list()))
```

and it gives me this huge list of `cmake` targets,
```
Message: CMaket targets:
 - Experimental
 - Nightly
 - Continuous
 - NightlyMemoryCheck
 - NightlyStart
 - NightlyUpdate
 - NightlyConfigure
 - NightlyBuild
 - NightlyTest
 - NightlyCoverage
 - NightlyMemCheck
 - NightlySubmit
 - ExperimentalStart
 - ExperimentalUpdate
 - ExperimentalConfigure
 - ExperimentalBuild
 - ExperimentalTest
 - ExperimentalCoverage
 - ExperimentalMemCheck
 - ExperimentalSubmit
 - ContinuousStart
 - ContinuousUpdate
 - ContinuousConfigure
 - ContinuousBuild
 - ContinuousTest
 - ContinuousCoverage
 - ContinuousMemCheck
 - ContinuousSubmit
 - docs
 - uninstall
 - tag
 - tag_c
```

but I'm not sure which target to go with.

**Comment by SeanOMik** [comment]
I'm pretty sure the target is `tag`.

**Comment by apoorv569** [comment]
> I'm pretty sure the target is `tag`.

I had already figured it out, but thanks anyways. Closing this issue now.

**Comment by scotchi** [comment]
Yeah, `tag` is presumably going to be the right one.  I'm also going to go ahead and close this since TagLib doesn't support meson in any official capacity, so this isn't a bug with TagLib.

**Comment by SeanOMik** [comment]
@apoorv569 How did you get it working in meson? I've been trying to set it up, but I get an error when trying to compile:
```
C:/Development/CPP/AudioMetadataTesting/src/main.cpp:3:10: fatal error: 'taglib/tag.h' file not found
```

**Comment by apoorv569** [comment]
> @apoorv569 How did you get it working with meson? I've been trying to set it up, but I get an error when trying to compile:
> 
> ```
> C:/Development/CPP/AudioMetadataTesting/src/main.cpp:3:10: fatal error: 'taglib/tag.h' file not found
> ```

You probably have to add the include path of your `taglib` `subproject` to `meson.build` file. But I'm not sure. I am BTW not developing on `Windows` but on `GNU/Linux`. You can however look at my `meson.build` file [here](https://gitlab.com/samplehive/sample-hive/-/blob/testing/meson.build#L191).
