### ISSUE TITLE
Compile error on Mac M1 (Apple Silicon)

### ISSUE THREAD

**Issue by farshed** [taglib/taglib#1032]
I'm trying to use Taglib in an application. I built and installed it from the source (v1.12). However when I try to compile the program, I get:

```
Undefined symbols for architecture arm64:
  "__ZNKSt3__112basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEE7compareEmmPKwm", referenced from:
      __ZNK6TagLib6StringeqEPKw in libtag.a(tstring.cpp.o)
      __ZNK6TagLib6StringneEPKw in libtag.a(tstring.cpp.o)
  "__ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv", referenced from:
      __ZNSt3__16vectorIcNS_9allocatorIcEEE8__appendEmRKc in libtag.a(tbytevector.cpp.o)
```

Code:

```
#include <taglib/fileref.h>
#include <taglib/tag.h>
#include <taglib/tstring.h>

int main() {
  TagLib::FileRef f("Free City Rhymes.ogg");
}
```

If I remove the `TagLib::FileRef f` declaration and compile with just the headers, it compiles just fine.
Any help is deeply appreciated.

**Comment by scotchi** [comment]
Have you confirmed that your setup is working on any other (e.g. non-M1, on Linux, whatever) configuration?  It wouldn't surprise me if your linker flags are wrong.

**Comment by scotchi** [comment]
Actually, looking at the error again, I wonder if you're maybe mixing libstdc++ and libc++?  (Could be, for example, by compiling one part of it with clang and the other with gcc, which I believe have different defaults on macOS.)

**Comment by farshed** [comment]
> compiling one part of it with clang and the other with gcc, which I believe have different defaults on macOS

This was the issue. It seems that cmake was using clang to generate lib files while I was trying to compile my program with g++. Thank you so much for helping me out. You're awesome.
