### ISSUE TITLE
String::copyFromUTF16() - Invalid UTF16 string. BOM is broken 

### ISSUE THREAD

**Issue by paolovalerdi** [taglib/taglib#1034]
I'm fairly new to all this tagging world and this library so this may be a silly question.

Given a file like this where some properties have more than one value (separated with "\\")
![image](https://user-images.githubusercontent.com/9915479/146657089-bd41d6e9-9436-43a4-a727-5de3e55715bf.png)

When using the `properties()` method this `String::copyFromUTF16() - Invalid UTF16 string. BOM is broken` message is logged out for every value except the first one. This results in every entry but the first one being blank.

```
auto properties = fileRef.file()->properties();

for (auto &property: properties) {
    std::cout << "TAG: " << property.first.toCString(true) << "\n";
    for (auto &value : property.second) {
         std::cout << "\tvalue: " << value.toCString(true) << "\n";  // Only the 
    }
}
```

is this the intended behavior or does it have something to do with the way mp3tag tags files?

**Comment by ufleisch** [comment]
I tried to reproduce this. I created a file with multiple values for artist and genre frame with Mp3Tag 3.11 and then read the file using _tagreader_ from the _examples_ directory of the TagLib sources. Everything is displayed as expected. Then I inserted your code fragment into the _tagreader.cpp_ source, and tested it, but the result is still as expected. I have run my tests on Linux with the current master branch of TagLib. What operating system and compiler are you using? Do you also see this problem when reading your file with _tagreader_?

**Comment by paolovalerdi** [comment]
Thanks for your response @ufleisch.
I'm running this on Android using the NDK (which uses the Clang compiler). I've tested with a couple of other files and everything seems to work as expected 🙃 (with both my code and the _tagreader_ sample). So I'll just assume the tags on some of my files are somewhat corrupted(?)
