### ISSUE TITLE
Wrong track duration being reported.

### ISSUE THREAD

**Issue by splendidsoftware** [taglib/taglib#1038]
I have found a situation where the duration of an MP3 track is reported incorrectly.  Specifically the Billy Joel track "Just the way you are", correctly reported as having a duration of 4:51 on the Windows 'Properties' dialog box, is reported as having a duration of 48+ minutes by the TagLib library.  Screen shots of both added.

![WrongDuration](https://user-images.githubusercontent.com/51451401/149018099-b1925416-9874-4dfb-81e4-c059ea70adc5.jpg)
![CorrectDuration](https://user-images.githubusercontent.com/51451401/149018270-ee6d3738-6714-4d4c-936a-069828163a0b.jpg)
.

**Comment by scotchi** [comment]
This appears to be an issue with TagLib#, which was originally based on TagLib, but is a separate project.

**Comment by splendidsoftware** [comment]
OK, thank you for letting me know.

Stephen Collins

Splendid Software
