### ISSUE TITLE
MP4 files corrupted (no playback) adding tags on Pixel model devices

### ISSUE THREAD

**Issue by TarenLewis** [taglib/taglib#1041]
Hello everyone,

I am working with Shure, exploring the possibility of using the library in an application. I have identified an issue which specifically targets Pixel phones (Pixel 3, Pixel 4, and Pixel 6 tested). This issue does not occur on Samsung phones. When adding any metadata to MP4 files, the file becomes corrupted and cannot play back. 

I have tested this with files recorded in MP4 format, as well as WAV files converted to MP4 format. I have recorded a WAV file, copied it to both a Samsung and Pixel phone (so that I know I have the same recording contents), and converted it to MP4 format on each phone. Only the file with metadata added on the Pixel phone is corrupted. 
<br>

Seen below are some of the files I have used for testing, as well as some error logs generated with this [ffmpeg](https://www.ffmpeg.org/) command:
`ffmpeg -v error -i RecPixel3_recMp4_metaAddedMp3tag.m4a -f null - 2>RecPixel3_recMp4__metaDataAddedMp3Tag.log`

**Original WAV file:**
[RecPixel3_recWav_nometadata.zip](https://github.com/taglib/taglib/files/8111435/RecPixel3_recWav_nometadata.zip)

**Original WAV to MP4 conversion files for Pixel and Samsung:**
[RecPixel3_recWav_nometadata_convertedToMp4OnPixel.zip](https://github.com/taglib/taglib/files/8111441/RecPixel3_recWav_nometadata_convertedToMp4OnPixel.zip)
[RecPixel3_recWav_nometadata_convertedToMp4OnSamsung.zip](https://github.com/taglib/taglib/files/8111443/RecPixel3_recWav_nometadata_convertedToMp4OnSamsung.zip)

WAV to MP4 converted on Pixel, with taglib tag added, as well as logs:
[RecPixel3_recWav_convertedToMp4OnPixel_metaAddedTaglib.zip](https://github.com/taglib/taglib/files/8111488/RecPixel3_recWav_convertedToMp4OnPixel_metaAddedTaglib.zip)
[RecPixel3_recWav_convertedToMp4OnPixel_metaAddedTaglib.log](https://github.com/taglib/taglib/files/8111492/RecPixel3_recWav_convertedToMp4OnPixel_metaAddedTaglib.log)

WAV to MP4 converted on Samsung, with taglib tag added, as well as logs:
[RecPixel3_recWav_convertedToMp4OnSamsung_metaAddedTaglib.zip](https://github.com/taglib/taglib/files/8111494/RecPixel3_recWav_convertedToMp4OnSamsung_metaAddedTaglib.zip)
[RecPixel3_recWav_convertedToMp4OnSamsung_metaAddedTaglib.log](https://github.com/taglib/taglib/files/8111496/RecPixel3_recWav_convertedToMp4OnSamsung_metaAddedTaglib.log)

I also know that this is not an issue with Pixel phones themselves, because I have recorded a file and added tags with [Mp3Tag](https://www.mp3tag.de/en/) without any issues.

MP4 file with tags added with Mp3Tag:
[RecPixel3_recMp4_metaAddedMp3tag.zip](https://github.com/taglib/taglib/files/8111463/RecPixel3_recMp4_metaAddedMp3tag.zip)
[RecPixel3_recMp4_metaAddedMp3Tag.log](https://github.com/taglib/taglib/files/8111589/RecPixel3_recMp4_metaAddedMp3Tag.log)

I have included this graphic which may be helpful for visualizing the issue:
![corruptionGraphic](https://user-images.githubusercontent.com/45551709/155013004-58c3fdf3-263a-45b5-9f77-44dd00edb858.PNG)
(one interesting note, according to ffmpeg and onlinemp4parser, a file recorded in my app with no metadata is "corrupted", but it will still play with Mp3Tag data added, so I do not believe this is relevant to the issue at hand.)
<br>

Some observations about differences between the two files with metadata added, I'm not sure what is relevant and what is not:
- UDTA: all atoms below are exactly equal in hex.
- MVHD: all atoms below are exactly equal in hex except for the creation and modification time.
- META:  all atoms are the same except for the last byte of the ILST atom.
- MDAT: data is all different, maybe because of the way that Pixel vs. Samsung encodes the audio?
- Samsung phones have SDLN, SMRD, and SMTA atoms within the UDTA atom, **Pixel does not**.
- MOOV: The order of sub-atoms is different; 
      *Pixel: Order is MOOV-> UDTA, MVHD, META, TRAK
      *Samsung: Order is MOOV-> MVHD, UDTA, META, TRAK
- STSZ and STSC atoms are different. (sample size and sample to chunk)

Thank you very much for your support and help, it would really make a difference to be able to continue working with the library. Please contact me with any further questions or information!

**Comment by scotchi** [comment]
>  (one interesting note, according to ffmpeg and onlinemp4parser, a file recorded in my app with no metadata is "corrupted", but it will still play with Mp3Tag data added, so I do not believe this is relevant to the issue at hand.)

I'll try to find some time to look at the files later, but this statement is one that I'd urge you to rethink.  If the initial files are non-conformant, it's not surprising that there's undefined behavior when modifying them.  That other players can play them isn't a good indication of file integrity -- it just means that other tools may try harder to work around breakage, or simply be more tolerant.

**Comment by TarenLewis** [comment]
Thank you for taking the time to look! I really appreciate it. 

If you take a close look at the chart that I provided, files recorded in WAV and then **converted to MP4** do not have this "corruption" I mentioned within my app (We'll call it "My Error"). It is only the files natively recorded in MP4 within the app. So, all of the files that I have provided above do not contain "My Error". This means these files can be safely tested, confident that the only error visible is the one associated with taglib tags.

It seems I made the mistake of not mentioning that I have also recorded MP4 files with other apps, which do not contain "My Error" since they aren't my app, but they still experience the corruption of audio associated with adding taglib tags, meaning that _all Pixel associated MP4 files will experience the taglib tag corruption_. 

<br></br>
> If the initial files are non-conformant, it's not surprising that there's undefined behavior when modifying them. That other players can play them isn't a good indication of file integrity -- it just means that other tools may try harder to work around breakage, or simply be more tolerant.

You're absolutely right about this, but it still is not relevant to the current issue, which is that for whatever reason, taglib tags added to Pixel devices recorded on different apps, either recorded natively in MP4 or converted from other file formats, experience corruption and loss of playback. 

Thanks again for saying you'll take a look into the issue, I really appreciate it!

**Comment by TarenLewis** [comment]
I would also like to clarify that this is not just an issue "seen on Pixel" phones, that even with files recorded on Pixel phones, if you use the taglib CLI example tool in Windows to add metadata, or if you play an MP4 with taglib tags which was recorded on a Pixel in Windows, the audio will be unplayable. It seems to touch multiple platforms, and stems from the root cause of the taglib tags being added to an MP4 file which is generated on a Pixel device.  

Again, to reiterate, this does not occur with tags added by Mp3Tag or other programs to these same MP4 audio files generated on Pixel.

Thanks! Looking forward to your responses because this has been something I've looked into extensively for the past few weeks.

**Comment by ufleisch** [comment]
Just to have a second opinion with another tool which is using TagLib and runs on Android: Could you try to take you test MP4 files and tag them with [Kid3](https://kid3.kde.org/), can also be found on [F-Droid](https://f-droid.org/en/packages/net.sourceforge.kid3/). If you can tag the same files on your Samsung and Pixel devices with Kid3 and the files on the Pixel are corrupt afterwards, it could be TagLib, otherwise, it could be something different or depend on the way how TagLib is compiled/linked/used.

**Comment by TarenLewis** [comment]
@ufleisch I have tested these files with Kid3: [RecPixel3_recWav_nometadata_convertedToMp4OnPixel.zip](https://github.com/taglib/taglib/files/8111441/RecPixel3_recWav_nometadata_convertedToMp4OnPixel.zip)
[RecPixel3_recWav_nometadata_convertedToMp4OnSamsung.zip](https://github.com/taglib/taglib/files/8111443/RecPixel3_recWav_nometadata_convertedToMp4OnSamsung.zip)

I can confirm that the audio is corrupted for the file converted on Pixel, but not for the Samsung file.

Thanks!

**Comment by ufleisch** [comment]
I can confirm the corruption and I have probably found the cause. The `meta` atom in this file is not a "full atom" as described [by Leo van Stee](https://leo-van-stee.github.io/), i.e. it is not followed by four bytes containing version and flags. These four bytes are always skipped by TagLib, which will abort the parsing and then fail to correctly update the offsets in the `co64` atom when a new atom is added. With the following patch, the corruption does no longer occur.

```
diff --git a/taglib/mp4/mp4atom.cpp b/taglib/mp4/mp4atom.cpp
index e030579f..140ed12b 100644
--- a/taglib/mp4/mp4atom.cpp
+++ b/taglib/mp4/mp4atom.cpp
@@ -85,7 +85,25 @@ MP4::Atom::Atom(File *file)
   for(int i = 0; i < numContainers; i++) {
     if(name == containers[i]) {
       if(name == "meta") {
-        file->seek(4, File::Current);
+        long posAfterMeta = file->tell();
+        ByteVector nextSize = file->readBlock(8).mid(4, 4);
+        static const char *const metaChildrenNames[] = {
+            "hdlr", "ilst", "mhdr", "ctry", "lang"
+        };
+        bool metaIsFullAtom = true;
+        for(size_t j = 0;
+            j < sizeof(metaChildrenNames) / sizeof(metaChildrenNames[0]);
+            ++j) {
+          if(nextSize == metaChildrenNames[j]) {
+            // meta is not a full atom (i.e. not followed by version, flags). It
+            // is followed by the size and type of the first child atom.
+            metaIsFullAtom = false;
+            break;
+          }
+        }
+        // Only skip next four bytes, which contain version and flags, if meta
+        // is a full atom.
+        file->seek(posAfterMeta + (metaIsFullAtom ? 4 : 0));
       }
       else if(name == "stsd") {
         file->seek(8, File::Current);
```

I will make a pull request out of it if no one who understands more about MP4 than I do has an objection.
