### ISSUE TITLE
String encoding problem(cyrillic)

### ISSUE THREAD

**Issue by m-akc** [taglib/taglib#1048]
Language: Dart (Via FFI)
C Bindings (Tag_c)
Taglib: Last version + tried Master Branch. Same Result :(
Same song, Different name.
![good](https://user-images.githubusercontent.com/69395801/170396381-ab627b12-ca21-4aac-988e-24252baa8251.jpg)
![bad](https://user-images.githubusercontent.com/69395801/170396447-557b93e9-8501-4d71-a4a3-3cebb3950008.jpg)

with taglib_set_strings_unicode(1) = app crashes immediately

Added:
Fixed app crash. It Works with Latin
> var songname = utf8.encode('смысл.mp3');
>   Pointer\<Int8\> pointer = calloc.allocate(songname.length);
>   for (int i = 0; i < songname.length; i++) {
>     pointer[i] = songname[i];
>   }
> ttt.taglib_set_strings_unicode(1); // the app no ​​longer crashes. But still does not work with Cyrillic
> var myfile = ttt.taglib_file_new(pointer);

**Comment by m-akc** [comment]
Taglib(Native) works with Cyrillic? I'm talking about filenames.

**Comment by ufleisch** [comment]
Looking at TagLib's C-bindings, I would say that `taglib_set_strings_unicode()` only affects the strings which are used to get and set the tags (`taglib_tag_title()`, `taglib_tag_set_title()`, ...), but not `taglib_file_new()`. On Linux, `taglib_file_new()` might work with an UTF-8 string, but not on Windows, where `FileName` is handled with different constructors for `const char *` and `const wchar_t *`, but the latter is not supported in the C-bindings and therefore Unicode file names will not work there.

**Comment by m-akc** [comment]
Thank you very much for the information! Now everything works.
![fixed](https://user-images.githubusercontent.com/69395801/170808790-458b0f4d-872c-4b0f-b8db-1c86e7380e75.jpg)

**Comment by scotchi** [comment]
It's probably worth noting that the C bindings pre-date Windows support, and aren't' widely used, so they haven't gotten a lot of updates in the last, say, 20 years.
