### ISSUE TITLE
A picture frame must contain at least 5 bytes

### ISSUE THREAD

**Issue by nlogozzo** [taglib/taglib#1049]
I'm trying to add album art to an MP3 file. 

I made a function to get a ByteVector from a GdkPixbuf (a gdk object that loads an image file)
```cpp
TagLib::ByteVector GtkHelpers::gdk_pixbuf_get_byte_vector(GdkPixbuf* pixbuf)
{
    unsigned int pixbufLength{0};
    unsigned char* data{gdk_pixbuf_get_pixels_with_length(pixbuf, &pixbufLength)};
    return {(char*)data, pixbufLength};
}
```
I then pass this ByteVector into my function to set the album art
```cpp
void MusicFile::setAlbumArt(const TagLib::ByteVector& albumArt)
{
    std::lock_guard<std::mutex> lock{m_mutex};
    if(m_fileType == MediaFileType::MP3)
    {
        m_fileMP3->ID3v2Tag(true)->removeFrames("APIC");
        if(!albumArt.isEmpty())
        {
            TagLib::ID3v2::AttachedPictureFrame* pictureFrame{new TagLib::ID3v2::AttachedPictureFrame};
            pictureFrame->setType(TagLib::ID3v2::AttachedPictureFrame::Type::FrontCover);
            pictureFrame->setPicture(albumArt.data());
            m_fileMP3->ID3v2Tag(true)->addFrame(pictureFrame);
        }
    }
   ...
}
```
If I print out `albumArt.size()` i get `5384672` which is more than 5 bytes, however I'm getting the message `TagLib: A picture frame must contain at least 5 bytes.` and the album art does not set.
What is going on?

**Comment by scotchi** [comment]
By using `albumArt.data()` instead of just `albumArt` you're implicitly creating a new `ByteVector` from a `char *` with the constructor for C strings, which sees it as terminated at the first null byte.  Just leave out the `.data()`.

**Comment by nlogozzo** [comment]
Omg i'm so dumb for not realizing that :laughing: 
Thank you!
