### ISSUE TITLE
taglib library doesn't work on Qt 6 (Windows 10)

### ISSUE THREAD

**Issue by Pbaodoge** [taglib/taglib#1051]
Hello!
I'm trying to implement taglib library into my Qt projects. Everything works fine when I try to build taglib with CMake. However, there's a problem with taglib.h file:
![image](https://user-images.githubusercontent.com/90094025/176463786-aa5a3e82-d829-4fd9-9515-70643a6fec0d.png)
"taglib_config.h" No such file or directory. I think that taglib_config.h was not found in the folder or something.
I'm a beginner in Qt and never have had any experience before...so please help me!
Thank you.

**Comment by scotchi** [comment]
You need to set your header search path to include the directory where `taglib_config.h` is generated or installed.  Normally that would be in your build directory.
