### ISSUE TITLE
File size limitation to 2 GB

### ISSUE THREAD

**Issue by CyberSinh** [taglib/taglib#1089]
The size of the files that can be opened in taglib seems to be limited to 2 GB.

Why such an arbitrary limitation? Is it possible to allow audio files larger than this?

https://github.com/taglib/taglib/blob/97203503b094cb0e34b08686eafe4620f262d4ba/taglib/toolkit/tfilestream.cpp#L457

Thanks.

**Comment by ufleisch** [comment]
A lot of parameters and fields representing file offsets are declared as `long`. On 64-bit Linux and macOS, a `long` variable has 64 bits, but on Windows, `long` has only 32 bits - both on 32-bit and 64-bit architectures. Therefore file sizes are limited to `LONG_MAX` on Windows. To fix this, we would have to change all these parameters to `long long` or another 64-bit type, which would break binary compatibility. Therefore, we cannot do this for 1.x releases, only when we start working on the 2.0 release. If you want to fix this for a "private" library or when statically linking, you could use a path like [taglib-1.13-win00-large_file.patch](https://invent.kde.org/multimedia/kid3/-/blob/master/packaging/patches/taglib-1.13-win00-large_file.patch), which is based on PR #77.

**Comment by CyberSinh** [comment]
Thank you very much for your feedback.
I understand. 
I can't wait for the release of taglib2 then, because this binary compatibility constraint is a real pain that prevents us from getting rid of an increasingly heavy technical debt, and tablib2 from evolving with its time.

**Comment by ufleisch** [comment]
Fixed with [ca8c2e0].
