### ISSUE TITLE
0.13.1 regression: absolute `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` are not supported anymore

### ISSUE THREAD

**Issue by trofi** [taglib/taglib#1098]
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs says that `CMAKE_INSTALL_*` can accept both absolute and relative paths:

```
CMAKE_INSTALL_<dir>

    Destination for files of a given type. This value may be passed to the DESTINATION options of [install()](https://cmake.org/cmake/help/latest/command/install.html#command:install) commands for the corresponding file type. It should typically be a path relative to the installation prefix so that it can be converted to an absolute path in a relocatable way (see CMAKE_INSTALL_FULL_<dir>). However, an absolute path is also allowed.
```

`nixpkgs` package repository usually uses `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` outside the `CMAKE_INSTALL_PREFIX`.

`taglib-0.13.0` used to work as is.

But with https://github.com/taglib/taglib/commit/967c0eefedcf7dea71832400791bed7246a41299 `tagilb.pc` files now append extra unexpected prefix:

Building:

```
$ mkdir b
$ cd b
$ cmake .. -DCMAKE_INSTALL_LIBDIR=/absolute-lib -DCMAKE_INSTALL_INCLUDEDIR=/absolute-include -DCMAKE_INSTALL_PREFIX=/usr
$ make
$ make install DESTDIR=${PWD}/_i_
```

Inspecting the paths:

```
$ cat _i_/absolute-lib/pkgconfig/taglib.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}//absolute-lib
includedir=${prefix}//absolute-include
```

Note the unexpected `${prefix}/`.

Noticed the deficiency when tried to package `0.13.1` as https://github.com/NixOS/nixpkgs/pull/245926.

So far we are working it around by using relative paths, but we would like to switch back to absolute paths to split out development outputs.

Thanks!

**Comment by ufleisch** [comment]
Thanks for the report. You read #1071 and thus you know the reason behind the change, it is to support [Approach 3: Use --define-prefix](https://docs.conan.io/en/1.14/integrations/pkg_config_pc_files.html#approach-3-use-define-prefix) when building with `pkgconfig`. There are a lot of projects using TagLib, and every change to the build system may make someone happy whereas annoying somebody else. In this case, you just have to set `-DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_INCLUDEDIR=include`, you do not even have to patch the source code of TagLib, so I assume it to be a minor inconvenience. Reverting 967c0eef would remove the support for the `prefix` feature of `pkgconfig`, which would mean that people using that feature would have to patch TagLib - much more hassle than just setting two CMake variables. In #1071, I said "I feel a bit reluctant to change the build system once more", now I am feeling even more reluctant to change it once more.

**Comment by trofi** [comment]
Accomodating to main use case is totally understandable. My hope was that if it's a regression there is a chance to restore previous behaviour was something on the table.

If support of `cmake`'s absolute paths in `CMAKE_INSTALL_*` is not intended I would suggest to fail clearly at configure phase and point at the issue (say, this one, or a README) that the mode is not supported.

In the long run `nixpkgs` would like to store header files outside of `${prefix}/` to decrease size of non-development package installs. We'll have to patch it downstream.

**Comment by a17r** [comment]
Since `CMAKE_INSTALL_LIBDIR`, `CMAKE_INSTALL_INCLUDEDIR` et al are allowed to be absolute, the change in 0.13.1 was always going to cause trouble for someone. These variables must not be appended to.

Requests to cmake upstream have led to some kind of support for safely joining paths in >=3.20:
https://gitlab.kitware.com/cmake/cmake/-/issues/19568#note_704230
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5158
https://cmake.org/cmake/help/latest/command/cmake_path.html
