### ISSUE TITLE
MPEG ReadStyle VLC patch

### ISSUE THREAD

**Issue by Tolriq** [taglib/taglib#1150]
Hi,

I'm sorry if I've missed a previous discussion but can't find it.
I was wondering why the VLC patch https://code.videolan.org/videolan/vlc/-/blob/master/contrib/src/taglib/0001-Implement-ID3v2-readStyle-avoid-worst-case.patch is not merged here ?

This is a nice to have patch when using IOStream and parsing network files to avoid too much data read.

**Comment by ufleisch** [comment]
I would say that this is a duplicate of #968 and suggest that we continue the discussion there.

**Comment by Tolriq** [comment]
Yes sorry I completely failed to find that one.
