### ISSUE TITLE
M4A Cannot get track duration

### ISSUE THREAD

**Issue by starkgate** [taglib/taglib#1165]
I am a user of the "Lightweight Music Server", which uses taglib to discover tags in music files. I noticed that taglib doesn't manage to get the track duration of the following M4A music file: [Donia - دویدم من.zip](https://github.com/epoupon/lms/files/13249786/Donia.-.zip).

The repository's owner directed me here for support with the following comment:
> Not sure why taglib does not manage to parse this file.
>  used ffmpeg to extract the aac stream (in copy mode) in a brand new m4a file, it seems to be correctly parsed by taglib.
https://github.com/epoupon/lms/issues/359#issuecomment-1792438610

There are more M4A files from different albums with the same issue, let me know if you need more information.

**Comment by ufleisch** [comment]
Thanks for the report. Your example file has a media header without duration. I have now added a PR #1168 which looks up the duration in the video header in such a case. Could you please check if it solves the problem also for the other M4A files with the same issue you mentioned?

**Comment by starkgate** [comment]
Looks like it's working, thank you for the quick action!
