### ISSUE TITLE
Misplacement of ‘hdvd’ Tag in MP4: A UInt Issue

### ISSUE THREAD

**Issue by aaa444c** [taglib/taglib#1169]
I’ve discovered a bug where a certain value is being treated as a boolean, but it is actually an UInt.
To resolve this issue, please search for the ‘hdvd’ tag in the ‘mp4tag.cpp’ file and move both instances into the UInt section.

**Comment by ufleisch** [comment]
Thanks for the report. I have created PR #1170 to fix this.
