### ISSUE TITLE
Can't read metadata of this flac file

### ISSUE THREAD

**Issue by Kyant0** [taglib/taglib#1174]
Screenshot:
![Screenshot_20231111_123736](https://github.com/taglib/taglib/assets/76829190/fc8c88ca-663d-4e27-9798-7e270e3d9776)

File:
[是什么让我遇见这样的你 - 白安.zip](https://github.com/taglib/taglib/files/13324463/-.zip)

**Comment by Kyant0** [comment]
[Let it go Madilyn Bailey.zip](https://github.com/taglib/taglib/files/13324487/Let.it.go.Madilyn.Bailey.zip)
And can't read the album art of the m4a file, though the title can be read.

**Comment by ufleisch** [comment]
I cannot reproduce this. Using _examples/tagreader_ from the master branch, I can read the tags from both of your files.

```
$ examples/tagreader *.flac *.m4a
******************** "是什么让我遇见这样的你 - 白安.flac" ********************
-- TAG (basic) --
title   - "是什么让我遇见这样的你"
artist  - "白安"
album   - "麦田捕手"
year    - "2012"
comment - ""
track   - "10"
genre   - "国语流行"
-- TAG (properties) --
ALBUM       - "麦田捕手"
ALBUMARTIST - "白安"
ARTIST      - "白安"
DATE        - "2012"
DISCNUMBER  - "1/1"
GENRE       - "国语流行"
TITLE       - "是什么让我遇见这样的你"
TRACKNUMBER - "10/10"
PICTURE:
  colorDepth  - 0
  data        - (42716 bytes)
  description - ""
  height      - 0
  mimeType    - "image/jpeg"
  numColors   - 0
  pictureType - "Front Cover"
  width       - 0
-- AUDIO --
bitrate     - 732
sample rate - 44100
channels    - 2
length      - 4:25
******************** "Let it go Madilyn Bailey.m4a" ********************
-- TAG (basic) --
title   - "Let it go "
artist  - "Madilyn Bailey"
album   - "Music cover "
year    - "0"
comment - ""
track   - "0"
genre   - ""
-- TAG (properties) --
ALBUM     - "Music cover "
ARTIST    - "Madilyn Bailey"
ENCODEDBY - "Lavf58.76.100"
TITLE     - "Let it go "
PICTURE:
  data        - (54495 bytes)
  mimeType    - "image/jpeg"
-- AUDIO --
bitrate     - 129
sample rate - 44100
channels    - 2
length      - 4:03
```

I can also read both files with Kid3 using TagLib 1.13. Which executable are you using?

**Comment by Kyant0** [comment]
https://github.com/Kyant0/taglib/blob/239a37a6674303945f54259b5abcbb55b9f5edad/src/main/cpp/taglib.cpp#L196
I am using this

**Comment by Kyant0** [comment]
hmm, I think I made a same mistake https://github.com/taglib/taglib/issues/1161#issuecomment-1768124498
I will try latter

**Comment by Kyant0** [comment]
It gives me log when parsing the flac file, MPEG::Header::parse() -- MPEG header did not match MPEG synch.

Does this mean TagLib identify this flac file as a mp3 file?

**Comment by ufleisch** [comment]
No, there must be something wrong with your code, you are probably explicitly instantiating an `MPEG::File`. Please have a look at the _examples_ folder. If I run _tagreader_ with your FLAC file, the line issuing the log message you mentioned (mpegheader:165) is never hit.

**Comment by Kyant0** [comment]
Not really, this is indeed a bug. The tagreader example is using file detection by file extension, while mine is stream (via file discriptor). When I move the mpeg stream detection after the flac, everything works fine.
![image](https://github.com/taglib/taglib/assets/76829190/596556c2-5837-448b-b3b7-aa7608caa05e)

**Comment by ufleisch** [comment]
You are right, your file was detected as an MPEG ADTS file. I have now made the check for MPEG headers slightly stricter so that the false detection will no longer occur. Please have a look at PR #1178.
