### ISSUE TITLE
Read write chunks in RIFF files.

### ISSUE THREAD

**Issue by yanc64** [taglib/taglib#1176]
Is there a way to read write individual chunks in RIFF files?
I am particularly interested in the "MARK" chunk (used to set named time markers), in AIFF/WAV files. 
thank you/

**Comment by scotchi** [comment]
Yes, but you'd need to subclass the AIFF / WAV classes to get access to the protected members.  Then you can use the API from RIFF::File:

https://taglib.org/api/classTagLib_1_1RIFF_1_1File.html

**Comment by yanc64** [comment]
thank you …

is there a way to determine the endianness of the file?
I can see it in headers FilePrivate, but how do I access that from an AIFF/WAV file?
