### ISSUE TITLE
Tag and audio properties for this m4a are not loaded

### ISSUE THREAD

**Issue by radioboss** [taglib/taglib#1186]
Taglib (release version 1.13.1) is not able to read the attached file. Previous version (1.13) was able to load it.

**Comment by radioboss** [comment]
[01 Feed The Beast.zip](https://github.com/taglib/taglib/files/13603033/01.Feed.The.Beast.zip)

**Comment by sbooth** [comment]
The file has an APE tag near the end (at offset 5676167) and when an attempt is made to parse it as MP4 atoms the parsing fails for obvious reasons.

APE tags in MP4 files are not explicitly supported and I don't know how commonplace such files are. Do you know  where the file came from?

**Comment by radioboss** [comment]
> APE tags in MP4 files are not explicitly supported and I don't know how commonplace such files are. Do you know where the file came from?

One of the users of my software sent it in a bug report - I don't know from where those files are originated. Maybe TagLib can detect APE tag presence by its header (APETAGEX) and ignore it?

**Comment by sbooth** [comment]
> Maybe TagLib can detect APE tag presence by its header (APETAGEX) and ignore it?

This would certainly be possible but I'm not sure it makes sense to change the library's behavior based on a single file without a supporting standard or at least something that appears to be in common use. I tried searching for information on APE tags in M4A files but didn't find much.

**Comment by ufleisch** [comment]
It does not seem to be common practice to use APE tags in M4A files. What I found was that ffmpeg allows to add APE tags to M4A files ([Is it possible to write ApeV2 tags with FFMPEG in AAC format](https://superuser.com/questions/1172107/is-it-possible-to-write-apev2-tags-with-ffmpeg-in-aac-format)).
However, I think that we could be more tolerant with trailing garbage in M4A files, after all, we also allow this in MP3, WAV and DSF files. Please have a look at PR #1187, it should restore the tolerant behavior from before e21640bf101c1e015b036fc7b8601727cc6a04f5, while still making sure that atoms affecting modifications done by TagLib are valid.
