### ISSUE TITLE
Release tarball for 2.0 is missing on GitHub

### ISSUE THREAD

**Issue by diizzyy** [taglib/taglib#1215]
It would be nice if a static tarball could be uploaded just like previous releases especially due to https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by jonaski** [comment]
Tarball is missing for both 1.13.1 and 2.0 on GH releases.

**Comment by ufleisch** [comment]
Thanks for the hint. I have now added the tarballs from the releases folder of https://taglib.org/ to both releases and updated my release process instructions so that I won't forget it in the next releases.

**Comment by diizzyy** [comment]
Thanks!
