### ISSUE TITLE
[Question] How to reduce the binary size?

### ISSUE THREAD

**Issue by Kyant0** [taglib/taglib#1225]
This is my arm64 build, 1.04MB, which is dynamically linked to c++ shared library. The text takes up the most space, are these debug messages? I don't enable debug.

![image](https://github.com/taglib/taglib/assets/76829190/4b6dfd0b-6da2-49fb-b65f-ad62c23d21e8)

**Comment by ufleisch** [comment]
The text segment contains the compiled code, not debug messages. If you want to know more about the format of ELF shared libraries, I recommend to read ["How To Write Shared Libraries" by Ulrich Drepper](https://www.cs.dartmouth.edu/~sergey/cs108/ABI/UlrichDrepper-How-To-Write-Shared-Libraries.pdf). For the amount of functionality provided by TagLib, I would not consider 1 MB to be too much. To reduce the size considerably, you would have to modify the source code to omit formats which you do not need.
