### ISSUE TITLE
Build problem depending on utf8cpp out of the box

### ISSUE THREAD

**Issue by bugaenko-cyber** [taglib/taglib#1227]
**I am using the qt6.7.0 mingw assembly, the paths are relative and reasonable
Everything works and compiles, but the first time an error occurs!?**

The compilation script itself:
mkdir %folder_taglib%
cd %folder_taglib%
cmake -S ../../taglib -B . -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=../../_bin/%folder_taglib%/qt670/64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DZLIB_LIBRARY=%pathZlib%/bin/libzlib.dll -DZLIB_INCLUDE_DIR=%pathZlib%/include -DVISIBILITY_HIDDEN=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_BINDINGS=OFF
cmake --build .
cmake --install .

Error:

[ 40%] Building CXX object taglib/CMakeFiles/tag.dir/toolkit/tstring.cpp.obj
C:\Project\mp\libs\taglib\taglib\toolkit\tstring.cpp:31:10: fatal error: utf8.h: No such file or directory
   31 | #include <utf8.h>
      |          ^~~~~~~~
compilation terminated.
mingw32-make.exe[2]: *** [taglib\CMakeFiles\tag.dir\build.make:736: taglib/CMakeFiles/tag.dir/toolkit/tstring.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:169: taglib/CMakeFiles/tag.dir/all] Error 2
mingw32-make.exe: *** [Makefile:135: all] Error 2

Output on first compilation:
-- Found ZLIB: c:/Project/mp/libs/_bin/zlib/qt670/64/bin/libzlib.dll (found version "1.3.1.1")
-- Could NOT find utf8cpp (missing: utf8cpp_INCLUDE_DIR)
-- Using utfcpp from C:/Project/mp/libs/taglib/3rdparty/utfcpp

Output from the second compilation:
-- Found ZLIB: c:/Project/mp/libs/_bin/zlib/qt670/64/bin/libzlib.dll (found version "1.3.1.1")
-- Using utfcpp 4.0.4 from C:/Project/mp/libs/_bin/taglib/qt670/64/share/utf8cpp/cmake/utf8cppConfig.cmake

**But with the second everything goes smoothly!
Studying the output, I see that it does not include this file or is there a missing dependency on utf8cpp (add_dependencies())??
I'm trying to assemble everything from the box so that I don't have my own inserts.
Please help me, what am I doing wrong!**

**Comment by bugaenko-cyber** [comment]
Update:
without changing cmakelists it only helped
-DCMAKE_PREFIX_PATH=path to 3rdparty\utfcpp\source

**Comment by ufleisch** [comment]
This makes sense. It looks like you have installed utfcpp somewhere, but not in a standard location where the CMake configurations are searched. Then you need to tell CMake where to look for the configuration, and setting `CMAKE_PREFIX_PATH` is one way to do it. This is also what is described in [INSTALL.md](https://github.com/taglib/taglib/blob/master/INSTALL.md) when using TagLib.

**Comment by bugaenko-cyber** [comment]
this library is located relative to the taglib root, but thanks anyway
