### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by Volodymyr-13** [taglib/taglib#1232]
Hello,

I really want to try this library for an iOS Swift project, and so far, I have tried the following:

https://github.com/NCrusher74/TagLibKit
https://github.com/NCrusher74/TagLib-SPM
https://github.com/hisaac/TagLibKit
None of them worked. Is there any solution for this? Or maybe there is a way to read .flac files on iOS? Any advice would be greatly appreciated!

**Comment by sbooth** [comment]
I actually put together [CXXTagLib](https://github.com/sbooth/CXXTagLib) recently which you might be interested in trying.

**Comment by scotchi** [comment]
I assume it makes sense to close this then?  (Even without @sbooth's comment, this issue would make more sense being filed with the folks that make those packages rather than with TagLib itself.)
