### ISSUE TITLE
Unable to build vlc v3.0.21 using taglib v2.0.1 but v1.13.1 builds just fine

### ISSUE THREAD

**Issue by graysky2** [taglib/taglib#1234]
In building vlc v3.0.21 for ARM64 with taglib v2.0.1, I am encountering errors which are not present if I build against taglib v1.13.1.  I am wondering if you have any insights into the source of these errors.

A build log containing errors can be found [here.](https://gist.github.com/graysky2/c188d60f1a20c4f56fb1bdc07d9d57e2)

**Comment by scotchi** [comment]
The code is using deprecated features from TagLib 1 and needs to be updated to compile with TagLib 2.  This isn't somehow an error on TagLib's side -- it's a new version of the library, and minor changes (particularly when using long deprecated TagLib 1 features) to your code are needed to make it work with the new version.

**Comment by graysky2** [comment]
Thanks, I see there is a [patch](https://gitlab.archlinux.org/archlinux/packaging/packages/vlc/-/blob/main/taglib-2.patch?ref_type=heads) I initially missed that fixes the build.
