### ISSUE TITLE
Setting arbitrary tags for MP4/M4A?

### ISSUE THREAD

**Issue by sentriz** [taglib/taglib#1239]
hi there,

I'm wonder if setting any arbitrary tag is supported for mp4. the usecase is setting non-standard tag names like `albumartists_credit` or `albumartist_credit`. which works for flac, but seems like for mp4 the tag is [ignored](https://github.com/taglib/taglib/blame/c4ed5900/taglib/mp4/mp4tag.cpp#L495-L501) if it's not present in the [`namePropertyMap`](https://github.com/taglib/taglib/blob/master/taglib/mp4/mp4itemfactory.cpp#L307)

other tagging software that I know of will set tag to be something like `----:com.apple.iTunes:<my tag key>` instead of ignoring it. (picard/puddletag/mutagen) 

do you know if this is possible with taglib? 

thanks!

**Comment by ufleisch** [comment]
Thanks for the report. I have fixed it with PR #1240, please test it.

**Comment by sentriz** [comment]
amazing thanks!
