### ISSUE TITLE
[FTBS] taglib v2.0.1 - tstring.cpp:31:10: fatal error: utf8.h: No such file or directory (even though cmake found the utf8cppConfig.cmake file)

### ISSUE THREAD

**Issue by Corin-EU** [taglib/taglib#1243]
This is on openSUSE Leap v15.6

taglib v2.0.1 requires "utf8cpp" libraries and header files.

The openSUSE utfcpp-devel rpm installs the relevant header files under the path /usr/include/utf8cpp and the cmake file at  /usr/lib64/cmake/utf8cpp/utf8cppConfig.cmake which includes the line

                  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/utf8cpp

which should presumably cause the appropriate include flag "-I/usr/include/utf8cpp" to be generated for use by a makefile to pass on in the compilation process to find the header file utf8.h located under the path  /usr/include/utf8cpp. 

On runnning cmake, all goes well with the message

                -- Using utfcpp  from /usr/lib64/cmake/utf8cpp/utf8cppConfig.cmake

but on starting the compilation process with make, the header file is not found when compilation of tstring.cpp commences.

                   [ 27%] Building CXX object taglib/CMakeFiles/tag.dir/toolkit/tstring.cpp.o
                  /usr/src/build/taglib-2.0.1/taglib/toolkit/tstring.cpp:31:10: fatal error: utf8.h: No such file or directory
                  #include <utf8.h>
                  ^~~~~~~~
                  compilation terminated.

It would appear that the include directory flag is not being used when tstring.cpp is being compiled.

Doing a "make VERBOSE=1" confirms that no "-I/usr/include/utf8cpp"  flag is present.

`cd /usr/src/build/taglib-2.0.1/build/taglib && /usr/bin/c++ -DHAVE_CONFIG_H -DTAGLIB_STATIC -I/usr/src/build/taglib-           2.0.1/build/taglib -I/usr/src/build/taglib-2.0.1/taglib -I/usr/src/build/taglib-2.0.1/build -I/usr/src/build/taglib-2.0.1/taglib/toolkit -I/usr/src/build/taglib-2.0.1/taglib/asf -I/usr/src/build/taglib-2.0.1/taglib/mpeg -I/usr/src/build/taglib-2.0.1/taglib/ogg -I/usr/src/build/taglib-2.0.1/taglib/ogg/flac -I/usr/src/build/taglib-2.0.1/taglib/flac -I/usr/src/build/taglib-2.0.1/taglib/mpc -I/usr/src/build/taglib-2.0.1/taglib/mp4 -I/usr/src/build/taglib-2.0.1/taglib/ogg/vorbis -I/usr/src/build/taglib-2.0.1/taglib/ogg/speex -I/usr/src/build/taglib-2.0.1/taglib/ogg/opus -I/usr/src/build/taglib-2.0.1/taglib/mpeg/id3v2 -I/usr/src/build/taglib-2.0.1/taglib/mpeg/id3v2/frames -I/usr/src/build/taglib-2.0.1/taglib/mpeg/id3v1 -I/usr/src/build/taglib-2.0.1/taglib/ape -I/usr/src/build/taglib-2.0.1/taglib/wavpack -I/usr/src/build/taglib-2.0.1/taglib/trueaudio -I/usr/src/build/taglib-2.0.1/taglib/riff -I/usr/src/build/taglib-2.0.1/taglib/riff/aiff -I/usr/src/build/taglib-2.0.1/taglib/riff/wav -I/usr/src/build/taglib-2.0.1/taglib/mod -I/usr/src/build/taglib-2.0.1/taglib/s3m -I/usr/src/build/taglib-2.0.1/taglib/it -I/usr/src/build/taglib-2.0.1/taglib/xm -I/usr/src/build/taglib-2.0.1/taglib/dsf -I/usr/src/build/tag lib-2.0.1/taglib/dsdiff -Wall -std=gnu++1z -MD -MT taglib/CMakeFiles/tag.dir/toolkit/tstring.cpp.o -MF CMakeFiles/tag.dir/toolkit/tstring.cpp.o.d -o CMakeFiles/tag.dir/toolkit/tstring.cpp.o -c /usr/src/build/taglib-2.0.1/taglib/toolkit/tstring.cpp`

cmake version is v3.30.0

Invoking cmake with -DCMAKE_INCLUDE_PATH="/usr/include/utf8cpp"  makes no difference.

Invoking cmake with -DCMAKE_CXX_FLAGS="-I/usr/include/utf8cpp" results in the header file being found and 100% build is reached.

But surely needing to manually add the include flag to the CXXFLAGS should not be necessary if the cmake process to create the makefiles is correctly set up to use the include directive from the utf8cppConfig.cmake file?

**Comment by ufleisch** [comment]
I can reproduce it on openSUSE Leap v15.6, but not with Tumbleweed. Probably it occurs because in the version used by Leap 15.6, the following line is missing at the end of _utf8cppConfig.cmake_:

```
add_library(utf8::cpp ALIAS utf8cpp)
```

and therefore the imported target does not exist.

Try with the following modification:

```
diff --git a/taglib/CMakeLists.txt b/taglib/CMakeLists.txt
index 519bd9a6..c6785fb8 100644
--- a/taglib/CMakeLists.txt
+++ b/taglib/CMakeLists.txt
@@ -347,7 +347,7 @@ target_include_directories(tag INTERFACE
 )
 
 target_link_libraries(tag
-  PRIVATE $<$<TARGET_EXISTS:utf8::cpp>:utf8::cpp>
+  PRIVATE $<IF:$<TARGET_EXISTS:utf8::cpp>,utf8::cpp,$<$<TARGET_EXISTS:utf8cpp>:utf8cpp>>
           $<$<TARGET_EXISTS:ZLIB::ZLIB>:ZLIB::ZLIB>
 )
```

**Comment by Corin-EU** [comment]
Thank you for your speedy response.

I applied the patch to v2.0.1 Taglib taglib/CMakeLists.txt and then tried building invoking cmake without the additional -I/usr/include/utf8cpp" flag and lo and behold "[100%] Built target test_runner" without any erors or warnings.

So this is in fact a bug in the utf8cpp library version   "utfcpp-devel-3.2.1-150200.5.3"   currently provided by openSUSE 15.6

I guess I should have installed a /usr/local version of the latest release of utf8cpp which is 4.0.5 and not been lazy and just installed the openSUSE rpm version.

Thanks for tracking down the cause of the problem.

**Comment by ufleisch** [comment]
I would not call it lazy to use the library versions which come with your system, this should be possible. I have therefore created a pull request to make future versions of TagLib build with older versions of utfcpp even when installed into a non standard location as it is the case in SUSE.
