### ISSUE TITLE
mpeg Frame::instrumentPrefix empty when building with WASI SDK

### ISSUE THREAD

**Issue by sentriz** [taglib/taglib#1246]
hi! 

I'm working on [a project](https://github.com/sentriz/go-taglib-wasm) to compile TagLib to WASM/WASI for use in a Go library for static and embedded builds

It sort of works to far but I've run into an issue when writing tags where seemingly where mpeg Frame::instrumentPrefix is an empty string. The result it [that the check for](https://github.com/taglib/taglib/blob/e3de03501ff66221d1f1f971022b248d5b38ba06/taglib/mpeg/id3v2/id3v2frame.cpp#L385) `person.startsWith(TextIdentificationFrame::instrumentPrefix` is returning, then the tag being added to the `tmclProperties` and the tag later being inserted always with the `PERFORMER:` prefix

eg. writing a tag like key "EXAMPLE" -> "abc", gets written as "PERFORMER:EXAMPLE" -> "abc"

FLAC on the other hand is working fine

I don't have a lot of C++ knowledge so I'm struggling to figure out why this might be, when the string is seemingly already set [here](https://github.com/taglib/taglib/blob/e3de03501ff66221d1f1f971022b248d5b38ba06/taglib/mpeg/id3v2/id3v2frame.cpp#L81).

I know this isn't an issue with TagLib per se but any help would be much appreciated.

If it helps, here is the [CMake project](https://github.com/sentriz/go-taglib-wasm/blob/master/embed/CMakeLists.txt), [the function in question](https://github.com/sentriz/go-taglib-wasm/blob/master/embed/taglib_wasm.cpp#L48), and [the build script](https://github.com/sentriz/go-taglib-wasm/blob/master/embed/embed.go#L10-L13)

Thank you very much!

---

PS if the issue isn't immediately obvious, and you'd be willing to take a look, I can try put together a simplified repo to reproduce the issue

**Comment by ufleisch** [comment]
From a C++ perspective, I see no reason how `instrumentPrefix` could have another value than `"PERFORMER:"`, it is defined and used in the same compilation unit. Maybe, it is a bug in the translation from C++ to WASM or in the use of WASM in Golang. It could be more helpful for you and other Golang developers if the Go bindings of TagLib would be adapted to the latest changes in TagLib, then you could use real Go bindings with better performance and less problems. Unfortunately, I am not a big help here as I am not proficient in this mentioned tech stack.

**Comment by sentriz** [comment]
@ufleisch thanks for the input. I agree native bindings would be nice. But I'm trying out WASM since it's leads to nice static and portable Go binaries when embedded

I have narrowed down the issue a bit. It seems to be related to TagLib::String and 32 bit WASM. Maybe something to do with the fact the string data is stored as a std::wstring, and `sizeof(wchar_t)` on WASM is 4 bytes

I made a little reproduction repo here

https://github.com/sentriz/taglib-string-wasm-repro

all it requries to run is Docker

as you can see the example code (in main.cpp) 
![image](https://github.com/user-attachments/assets/fcb2b9b9-99a6-49ab-b208-9bc7e29a1b65)

when printing, the string is empty - while still having a size
![image](https://github.com/user-attachments/assets/bccdc12f-28da-4656-8540-a91546305e28)

maybe some where in to8Bit, or ByteVector String::data, the WASM `wchar_t` isn't being considered? what do you think? thanks!

![image](https://github.com/user-attachments/assets/4f259c44-e414-4848-9268-eaf59f994b28)

**Comment by sentriz** [comment]
as it turns out the issue was all C++ desctructors being called as the end of main, before any exported functions got to use them :+1: 

fix is to use -mexec-model=reactor

https://github.com/WebAssembly/wasi-sdk/issues/500
