### ISSUE TITLE
Instant application crash if any part of code contains TagLib::FileRef regardless of if the line is executed

### ISSUE THREAD

**Issue by Robinfox1988** [taglib/taglib#1253]
I've been using taglib for many years without issue, but I've come back to the program I used it for to get it running again, and now when I compile my program with taglib it instantly crashes before it should even run the corresponding code.

I have isolated it to the following code, and no amount of fiddling and different permutations can get the program to run with the following lines enabled in the program.

```
QString fileName ="C:/path/to/file";
TagLib::FileRef f(fileName.toStdString().data(), true);
```

This is in QT6.5.3 using mingw 1120 64bit as the compiler on Windows 10 22H2 64bit

The line with TagLib::FileRef is the line that causes the crash, and it doesn't matter if I use a literal string, a QString with fileName.toUtf8().constData(), or casting to a const cString, or any other way of calling FileRef, all valid variations that will compile will crash.

The line isn't even executed within the test program I wrote to isolate the issue, it's just there in an unused function, but its mere existence is enough to cause the application to crash long before the main window ever loads.

Because of this, I can't get any debug info at all, even placing a qDebug() line or std::cout line before any other line in main() doesn't output anything, and it seems as though the application crashes even before it gets to the main entry point for the executable, which is utterly bizarre.
If I comment out the problematic line, the program will execute normally and the main window will appear, but without the functionality of taglib, the program is useless.

The only way I can have any variation of TagLib::FileRef within the program is if I have the line as follows:

```
TagLib::FileRef file();
```

However I can't use this either as I need to point it to a string on instantiation and I don't see any way around this, at least as far as I can tell.

**Comment by ufleisch** [comment]
As I have a project which is running fine on Windows 10 with exactly the same Qt version, it could be that the problem is not related to TagLib. Windows is not very tolerant when it comes to use libraries which have been built with different compilers, so please ensure that your TagLib has been compiled with exactly the same compiler as your application, and as you are using precompiled Qt libraries in your project, that compiler should be the one which comes bundled with Qt (probably in the _Tools/mingw1120_64/bin_ folder of your Qt installation).

If a setup with a TagLib which has been rebuilt with that compiler still fails, please provide a complete project archive to reproduce the issue.

**Comment by ufleisch** [comment]
Here a reproducible way to create your project:

```
vcpkg install utfcpp --triplet=x64-mingw-dynamic

# Adapt to your Qt installation path
$env:PATH = "C:\Qt\Tools\mingw1120_64\bin;${env:PATH}"
# Adapt to your TagLib source directory
$env:TAGLIB_SRC_DIR = "${env:HOMEDRIVE}${env:HOMEPATH}/projects/taglib/src/taglib"
# Adapt to your TagLib build directory
$env:TAGLIB_DST_DIR = "${env:HOMEDRIVE}${env:HOMEPATH}/projects/taglib/src/mingw_vcpkg_build"
cd $env:TAGLIB_SRC_DIR
cmake -B $env:TAGLIB_DST_DIR -DBUILD_SHARED_LIBS=ON -DVISIBILITY_HIDDEN=ON `
  -DBUILD_TESTING=OFF -DWITH_ZLIB=OFF -DBUILD_EXAMPLES=ON -DBUILD_BINDINGS=ON `
  -DCMAKE_BUILD_TYPE=Release `
  -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
  -G "MinGW Makefiles"
cmake --build $env:TAGLIB_DST_DIR --config Release

# Install to \pkg_mingw folder on current drive, probably C:\pkg_mingw
cmake --install $env:TAGLIB_DST_DIR --config Release --prefix /pkg_mingw --strip
```

Now you have a TagLib package for mingw in C:\pkg_mingw

Your example program, _main.cpp_:
```
#include <QString>
#include <taglib/fileref.h>

int main() {
  QString fileName ="C:/path/to/music.mp3";
  TagLib::FileRef f(fileName.toStdString().data(), true);
  printf("Title: %s", f.tag()->title().toCString());
}
```

A minimal CMake file:
```
cmake_minimum_required (VERSION 3.16)

project ("taglibqt")

include($ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
set(CMAKE_PREFIX_PATH "C:/pkg_mingw;C:/Qt/6.5.3/mingw_64")

add_executable(${PROJECT_NAME} "main.cpp")

find_package(TagLib REQUIRED)
find_package(Qt6 REQUIRED COMPONENTS Core)
target_link_libraries(${PROJECT_NAME} PRIVATE TagLib::tag Qt6::Core)
```

Inside the folder containing these two files, build into a folder named _build_:
```
cmake -B build -G "MinGW Makefiles"
cmake --build build --config Release
```

With the folders with the required DLLs added to the PATH, the built executable runs **without** crash:
```
$env:Path += ";C:\Qt\6.5.3\mingw_64\bin;C:\pkg_mingw\bin"
.\build\taglibqt.exe
```
