### ISSUE TITLE
Shorten (SHN) support

### ISSUE THREAD

**Issue by sbooth** [taglib/taglib#1256]
A format I'd like to see TagLib support is [Shorten](https://en.wikipedia.org/wiki/Shorten_(codec)).

It's an older format and doesn't really have any native tags/metadata so it would be a bit of an odd addition, however it would be great to have audio properties support at the least.

There is precedent for formats without native tags already- module (mod) files.

I'm happy to generate a PR for this if it's likely to be accepted.

**Comment by sbooth** [comment]
@ufleisch any thoughts?

**Comment by ufleisch** [comment]
I will be happy to look at your PR.
