### ISSUE TITLE
Only the first instance of an MP4 Atom should be parsed

### ISSUE THREAD

**Issue by dukeyin** [taglib/taglib#126]
I previously wrote to the devel mailing list (MP4 atoms incorrectly showing as non-null empty strings (e.g., "aART" and "\251wrt" atoms).

It seems that some applications, when updating MP4 tags, will have a valid instance of "Atom A" early on in moov/udta/meta/ilst, but towards the end of the atom list, will include orphaned atoms including "Atom A" which have a data block of size 0.  Many applications, including iTunes, foobar2000, and Mp3tag, do not acknowledge the existence of these nth atoms containing no data.  But TagLib's parsing will overwrite the first atom with the last atom (empty).

Here's the patch I put into my 1.8 code mp4tag.cpp.

```
void
MP4::Tag::parseText(MP4::Atom *atom, TagLib::File *file, int expectedFlags)
{
...
if (d->items.contains(atom->name)) {
       // don't overwrite
    } else {
        d->items.insert(atom->name, value);
    }
...
}
```

I have only experienced this with Text atoms - I am unsure if the same patch needs to go into the other ParseX functions.

I have not made a pull request after all because I am using the 1.8 code, not the latest revision, which has changed mp4tag.cpp quite a bit.

**Comment by matt77hias** [comment]
Is this somewhere part of a MP4 standard: Only the first instance of an MP4 Atom should be parsed?

**Mp3Tag**: https://community.mp3tag.de/t/multivalued-fields-for-aac/68857/5

> Yes, there are actually three different ways of properly storing multiple values in MP4.

    1. Flatten multiple values
    This is the most compatible approach, albeit not really multi-value. Here, multiple values are written in one field, separated by a character or character sequence, e.g., ;, ,, or /

    aART...data...Album Artist 1 Name;Album Artist 2 Name

    2. Write one MP4 atom per value
    This is the approach Mp3tag and others have taken. Each value is stored in one MP4 atom, e.g., aART for ALBUMARTIST with a data part that keeps the actual name of the album artist.

    aART...data...Album Artist 1 Name
    aART...data...Album Artist 2 Name

    3. Write one MP4 atom with multiple data parts
    This is the approach Navidrome is using. Individual values are stored in multiple data atoms that are contained in the MP4 atom for the actual field.

    aART...data...Album Artist 1 Name...data...Album Artist 2 Name
