### ISSUE TITLE
[BUG] Remove MP3 audio cover cause increasing in audio duration

### ISSUE THREAD

**Issue by dhng22** [taglib/taglib#1261]
This bug is observed on this mp3 file particularly:
[https://drive.google.com/file/d/1r9zoq7-6iCz29MLCKlpaciDG6ZitkYXM/view?usp=drivesdk](https://drive.google.com/file/d/1r9zoq7-6iCz29MLCKlpaciDG6ZitkYXM/view?usp=drivesdk)

Step to reproduce:

1. Set an audio cover for it
2. Remove the audio cover, then a part of the audio will be duplicated at the end, which make the audio longer

I've tried both method using setComplexProperties("PICTURE", {}); and id3v2->removeFrames("APIC");

**Comment by ufleisch** [comment]
Tried to reproduce this with your file:

```
$ examples/tagreader issue1261.mp3 | grep length
length      - 5:05
$ examples/tagwriter -p '' '' issue1261.mp3 
$ examples/tagreader issue1261.mp3 | grep length
length      - 5:05
```

As you can see, the length is still the same. The space of the removed picture is filled with zeros, not duplicated audio:

```
$ xxd -seek 0x2e0 -l 0x40 issue1261.mp3 
000002e0: 6f72 2061 2073 6f6e 6720 746f 6e69 6768  or a song tonigh
000002f0: 7400 0000 0000 0000 0000 0000 0000 0000  t...............
00000300: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000310: 0000 0000 0000 0000 0000 0000 0000 0000  ................
(..)
```

If you want to remove this padding, you have to strip the whole tag and then writing it anew.

**Comment by dhng22** [comment]
No you have to set the APIC first, then you remove the frame. That's when it occurs

**Comment by dhng22** [comment]
I use this code:

```
bool Tagger::tagAudioThumbnail(const std::string &filePath, const std::string &coverArtPath) {
    FileRef file(filePath.c_str());
    if (!file.isNull() && file.tag()) {
        if (coverArtPath.empty()) {
            file.setComplexProperties("PICTURE", {});
        } else {
            TagLib::FileStream coverStream(coverArtPath.c_str(), true);
            TagLib::ByteVector coverData = coverStream.readBlock(coverStream.length());

            file.setComplexProperties("PICTURE", {
                    {
                            {"data", coverData},
                            {"pictureType", "Front Cover"},
                            {"mimeType", "image/jpg" }
                    }
            });
        }
       return file.save();
    }
    return false;
}
```

**Comment by dhng22** [comment]
Switching cover between jpeg and png file also increase the length of the audio. Note that all these bug happened on that mp3 file only, others work great

**Comment by ufleisch** [comment]
> No you have to set the APIC first, then you remove the frame.

There is already a picture on your example file, but also if I add a new one, the length still remains the same.

```
$ examples/tagreader issue1261.mp3 | grep length
length      - 5:05
$ examples/tagwriter -p folder.jpg 'APIC description' issue1261.mp3
$ examples/tagwriter -p '' '' issue1261.mp3 
$ examples/tagreader issue1261.mp3 | grep length
length      - 5:05
```

Can you reproduce the problem with `tagreader` and `tagwriter`? If not, your code is doing it differently and you should provide a full buildable example how you set the tags and how you read the duration.

**Comment by dhng22** [comment]
@ufleisch My bad, my copy file from one to another place logic was messed up. Thank you
