### ISSUE TITLE
taglib leads to corrupted characters in mp3 files when using special characters (e.g. äÄöÖüÜß)

### ISSUE THREAD

**Issue by m00nraker** [taglib/taglib#129]
There seems to be a bug when reading and/or writing Id3 tags in mp3-files
with taglib based applications, like e.g. Kid3, Amarok,... This is when dealing
with special characters like the German Umlauts (äÄöÖüÜß) in the tag fields.
I don't know if this is distribution specific. I also put in a bug report for openSuse 12.3, my favorite distribution. Take a look:
https://bugzilla.novell.com/show_bug.cgi?id=814814#c0

I made a little screencast about the steps to reproduce (please
adjust quality level to see details):
http://youtu.be/XoAW1zmgSKA

Tested on openSuse 12.3 (x86-64), Kernel 3.7.10-1.1-Desktop, KDE 4.10.2.
taglib and libtag\* v1.8-3.2.1 (OSS Repo)
Also tested with:
taglib and libtag\* v1.8.55-7 (multimedia:lib Repo)

This setup leads into corrupted tag-fields when dealing with special
characters. I only tested with mp3-files. Don't know if other files formats are affected.
When using id3lib (ID3v2.3) applications, everything is fine, even with German special characters.

Can someone confirm or help?

**Comment by unxed** [comment]
> like the German Umlauts (äÄöÖüÜß) in the tag fields

Actually 1-byte charset for id3v1 tags should be detected by system locale for both German and for example Russian tags are processed correctly. Detecting example and locale->charset translateion table can be found in my 7zip patch for Debian:
https://salsa.debian.org/debian/7zip/-/commit/c9e7cf319db67ee58d27b90dba81832f6fb598a1

**Comment by unxed** [comment]
> 1-byte charset for id3v1 tags should be detected by system locale

Like this:
```
diff --git a/taglib/mpeg/id3v1/id3v1tag.cpp b/taglib/mpeg/id3v1/id3v1tag.cpp
index 8f55a16e..51dc5c85 100644
--- a/taglib/mpeg/id3v1/id3v1tag.cpp
+++ b/taglib/mpeg/id3v1/id3v1tag.cpp
@@ -29,6 +29,9 @@
 #include "tfile.h"
 #include "id3v1genres.h"
 
+#include <iconv.h>
+#include <cstring>
+
 using namespace TagLib;
 using namespace ID3v1;
 
@@ -57,6 +60,99 @@ class ID3v1::StringHandler::StringHandlerPrivate
 {
 };
 
+////////////////////////////////////////////////////////////////////////////////
+// Charset Conversion methods
+////////////////////////////////////////////////////////////////////////////////
+
+std::string getSystemCodepage() {
+    const char *lcToAnsiTable[] = {
+        "af_ZA", "CP1252", "ar_SA", "CP1256", "ar_LB", "CP1256", "ar_EG", "CP1256",
+        "ar_DZ", "CP1256", "ar_BH", "CP1256", "ar_IQ", "CP1256", "ar_JO", "CP1256",
+        "ar_KW", "CP1256", "ar_LY", "CP1256", "ar_MA", "CP1256", "ar_OM", "CP1256",
+        "ar_QA", "CP1256", "ar_SY", "CP1256", "ar_TN", "CP1256", "ar_AE", "CP1256",
+        "ar_YE", "CP1256","ast_ES", "CP1252", "az_AZ", "CP1251", "az_AZ", "CP1254",
+        "be_BY", "CP1251", "bg_BG", "CP1251", "br_FR", "CP1252", "ca_ES", "CP1252",
+        "zh_CN", "CP936",  "zh_TW", "CP950",  "kw_GB", "CP1252", "cs_CZ", "CP1250",
+        "cy_GB", "CP1252", "da_DK", "CP1252", "de_AT", "CP1252", "de_LI", "CP1252",
+        "de_LU", "CP1252", "de_CH", "CP1252", "de_DE", "CP1252", "el_GR", "CP1253",
+        "en_AU", "CP1252", "en_CA", "CP1252", "en_GB", "CP1252", "en_IE", "CP1252",
+        "en_JM", "CP1252", "en_BZ", "CP1252", "en_PH", "CP1252", "en_ZA", "CP1252",
+        "en_TT", "CP1252", "en_US", "CP1252", "en_ZW", "CP1252", "en_NZ", "CP1252",
+        "es_PA", "CP1252", "es_BO", "CP1252", "es_CR", "CP1252", "es_DO", "CP1252",
+        "es_SV", "CP1252", "es_EC", "CP1252", "es_GT", "CP1252", "es_HN", "CP1252",
+        "es_NI", "CP1252", "es_CL", "CP1252", "es_MX", "CP1252", "es_ES", "CP1252",
+        "es_CO", "CP1252", "es_ES", "CP1252", "es_PE", "CP1252", "es_AR", "CP1252",
+        "es_PR", "CP1252", "es_VE", "CP1252", "es_UY", "CP1252", "es_PY", "CP1252",
+        "et_EE", "CP1257", "eu_ES", "CP1252", "fa_IR", "CP1256", "fi_FI", "CP1252",
+        "fo_FO", "CP1252", "fr_FR", "CP1252", "fr_BE", "CP1252", "fr_CA", "CP1252",
+        "fr_LU", "CP1252", "fr_MC", "CP1252", "fr_CH", "CP1252", "ga_IE", "CP1252",
+        "gd_GB", "CP1252", "gv_IM", "CP1252", "gl_ES", "CP1252", "he_IL", "CP1255",
+        "hr_HR", "CP1250", "hu_HU", "CP1250", "id_ID", "CP1252", "is_IS", "CP1252",
+        "it_IT", "CP1252", "it_CH", "CP1252", "iv_IV", "CP1252", "ja_JP", "CP932",
+        "kk_KZ", "CP1251", "ko_KR", "CP949", "ky_KG", "CP1251", "lt_LT", "CP1257",
+        "lv_LV", "CP1257", "mk_MK", "CP1251", "mn_MN", "CP1251", "ms_BN", "CP1252",
+        "ms_MY", "CP1252", "nl_BE", "CP1252", "nl_NL", "CP1252", "nl_SR", "CP1252",
+        "nn_NO", "CP1252", "nb_NO", "CP1252", "pl_PL", "CP1250", "pt_BR", "CP1252",
+        "pt_PT", "CP1252", "rm_CH", "CP1252", "ro_RO", "CP1250", "ru_RU", "CP1251",
+        "sk_SK", "CP1250", "sl_SI", "CP1250", "sq_AL", "CP1250", "sr_RS", "CP1251",
+        "sr_RS", "CP1250", "sv_SE", "CP1252", "sv_FI", "CP1252", "sw_KE", "CP1252",
+        "th_TH", "CP874", "tr_TR", "CP1254", "tt_RU", "CP1251", "uk_UA", "CP1251",
+        "ur_PK", "CP1256", "uz_UZ", "CP1251", "uz_UZ", "CP1254", "vi_VN", "CP1258",
+        "wa_BE", "CP1252", "zh_HK", "CP950", "zh_SG", "CP936"};
+
+    char *lc = setlocale(LC_CTYPE, "");
+    if (!lc) {
+        //std::cerr << "setlocale failed" << std::endl;
+        return "";  // Return empty string to indicate failure
+    }
+
+    size_t lcLen = 0;
+    for (; lc[lcLen] != '.' && lc[lcLen] != ':' && lc[lcLen] != '\0'; ++lcLen);
+
+    for (size_t i = 0; i < sizeof(lcToAnsiTable) / sizeof(lcToAnsiTable[0]); i += 2) {
+       if (strncmp(lc, lcToAnsiTable[i], lcLen) == 0) {
+            return lcToAnsiTable[i + 1];
+        }
+    }
+
+    //std::cerr << "No matching ANSI codepage found for locale: " << lc << std::endl;
+    return ""; // Return empty to signal error
+}
+
+std::string convertEncoding(const std::string& input, const std::string& from, const std::string& to) {
+    iconv_t cd = iconv_open(to.c_str(), from.c_str());
+    if (cd == (iconv_t)(-1)) {
+        //std::cerr << "iconv_open failed: " << errno << std::endl;
+        return ""; 
+    }
+
+    size_t inbytesleft = input.size();
+    size_t outbytesleft = inbytesleft * 4 + 1; // increased for potential expansion
+    char* inbuf = const_cast<char*>(input.data());
+    char* outbuf = new char[outbytesleft];
+    char* outbuf_start = outbuf;
+
+    size_t converted = iconv(cd, &inbuf, &inbytesleft, &outbuf, &outbytesleft);
+
+    if (converted == (size_t)(-1)) {
+      delete[] outbuf_start;
+        //std::cerr << "iconv failed: " << errno << std::endl;
+        if (errno == EILSEQ) {
+          //std::cerr << "Invalid input sequence" << std::endl;
+        } else if (errno == E2BIG) {
+          //std::cerr << "Output buffer too small" << std::endl;
+        } else if (errno == EINVAL) {
+          //std::cerr << "Incomplete input sequence" << std::endl;
+        }
+        return "";
+    }
+
+    std::string output(outbuf_start, outbuf - outbuf_start);
+    delete[] outbuf_start;
+    iconv_close(cd);
+    return output;
+}
+
 ////////////////////////////////////////////////////////////////////////////////
 // StringHandler implementation
 ////////////////////////////////////////////////////////////////////////////////
@@ -67,14 +163,16 @@ StringHandler::~StringHandler() = default;
 
 String ID3v1::StringHandler::parse(const ByteVector &data) const
 {
-  return String(data, String::Latin1).stripWhiteSpace();
+  std::string systemCp = getSystemCodepage();
+  std::string utf8_string = convertEncoding(std::string(data.data(), data.size()), systemCp, "UTF-8");
+  return String(utf8_string, String::UTF8).stripWhiteSpace();
 }
 
 ByteVector ID3v1::StringHandler::render(const String &s) const
 {
-  if(s.isLatin1())
-    return s.data(String::Latin1);
-  return ByteVector();
+  std::string systemCp = getSystemCodepage();
+  std::string target_string = convertEncoding(s.to8Bit(true), "UTF-8", systemCp);
+  return ByteVector::fromCString(target_string.c_str());
 }
 
 ////////////////////////////////////////////////////////////////////////////////

```

**Comment by sbooth** [comment]
I'm not sure that using the system locale is the correct approach. Ignoring the fact that (AFAIK) ID3v1 explicitly uses ISO 8859-1, how would a file with an ID3v1 tag encoded in `windows-1251` be handled with on a system using locale `windows-1256`? This isn't to say that using the system locale isn't a good guess in the absence of knowledge on the actual encoding used, but I'm not sure this is within the realm of TagLib since files with an ID3v1 tag not using ISO 8859-1 are out of spec. Could your heuristic be applied in a custom `StringHandler` class?

**Comment by unxed** [comment]
> ID3v1 explicitly uses ISO 8859-1

Just like with legacy .zip archives that use single-byte encoding for filenames, there's a standard and a de facto standard. According to the standard, code page 437 should be used. In reality, users needed to archive files with names in their own languages, so all archivers on DOS and Windows used the OEM (DOS) encoding corresponding to the current locale.

The story is the same with ID3v1 tags: all players I know from the time when this tag format was popular used the system's ANSI (Windows) encoding for writing tags because there was no other way to write the name of an artist who wasn't born in an English-speaking country.

> how would a file with an ID3v1 tag encoded in windows-1251 be handled on a system using locale windows-1256

And how files with an ID3v1 tags encoded in windows-1251 are handled NOW? This change will not make the situation worse. The situation when a resident of Western Europe with a writing system that uses umlauts, for some reason set a Russian locale and received a crooked encoding, seems somewhat far-fetched to me.

> but I'm not sure this is within the realm of TagLib since files with an ID3v1 tag not using ISO 8859-1 are out of spec

If you feel problematic, can correct charset selection be enabled with a build option? If you do not want to decide, let distro makers do.

(can't imagine who could complain about non-compliance with the standard in this case, but let's leave that issue out of the discussion)

**Comment by ufleisch** [comment]
If you really want to detect the 8-bit encoding of a given text, you would have to go through all possible 8-bit encodings, decode the text and check if the result is a meaningful text in any of the languages which use that encoding. This requires a huge amount of data and is out of scope of TagLib. With a simple algorithm, you could just detect if the given 8-bit encoding follows some rules, e.g. if it is UTF-8 encoded. In the case of MP3 files of unknown origin, the system locale is probably a wrong guess.

**Comment by unxed** [comment]
> and check if the result is a meaningful text in any of the languages which use that encoding

You are right, this is one of the possible solutions.  This is actually the approach used by the [unar](https://theunarchiver.com/command-line) archiver. The problem with this method is that false positives are possible.  In archives, we often have many files, and the larger the volume of analyzed text, the higher the probability of accurate encoding detection using this method. The amount of textual information in an ID3v1 tag is significantly smaller, and therefore, the probability of correct detection is lower.

You are also right that determining the encoding in this way is outside the scope of taglib. However, it is not necessary to implement this logic in it. In the [far2l](https://github.com/elfmz/far2l) project, we use the [uchardet](https://www.freedesktop.org/wiki/Software/uchardet/) library for this purpose. It is available in most distributions, and, again, a build option without this feature could be offered. However, the probability of false positives remains, as the amount of text is too small.

Regarding mp3 files of unknown origin, my reasoning is as follows: there can be no perfect solution. With any approach, some users will have incorrect encoding, and the only option for them will be to manually recode tags from v1 to v2, specifying the correct encoding by hands. Therefore, we need to choose not the ideal option, which doesn't exist, but the option that will give a good result for the maximum number of users.

In my view, even in the case of mp3 files of unknown origin, it is most likely that a user with a German locale will listen to music in German, and perhaps English. A user with a Chinese locale will listen to music in Chinese. And a user with a Russian locale will listen to music in Russian. Yes, this logic will not cover all possible cases; we cannot exclude the existence of Chinese fans of Mylène Farmer. However, this approach will be correct in most cases, and, importantly, it will work predictably, unlike encoding detection based on text analysis.

**Comment by akruphi** [comment]
May be situation when autodetect return incorrect, may be situation when user locale not equivalent with mp3 charset.

I suggest make additional parameter, which to give applications more freedom of choice:
* udetect (by default)
* by user locale
* from charset list

It make possibility to applications ask users.

**Comment by scotchi** [comment]
I really don't think this belongs in TagLib itself.  But TagLib does have facilities for each application developer to decide how they want to handle it (`ID3v1::StringHandler`).  This also feels a little bit like flogging a dead horse since:

  - TagLib's made it possible to override the default behavior for more than 20 years
  - ID3v2 has been out for 26 years, and always explicitly supported unicode

**Comment by unxed** [comment]
Relevant qmmp issue:
https://sourceforge.net/p/qmmp-dev/tickets/924/

Relevant Ubuntu issue:
https://sourceforge.net/p/qmmp-dev/tickets/924/

**Comment by scotchi** [comment]
I understand the issue.  I wrote the code to work around it 20 years ago.  But introducing new code now to deal with broken files from multiple decades ago feels misplaced.  Again, this can be handled at the application level, however, if applications want to make it user configurable, or try the system encoding or whatever, but I don't believe that those workarounds for very old files belong in TagLib itself.

**Comment by unxed** [comment]
> Again, this can be handled at the application level

So every app would need to have its on locale->charset translation table. What if a bug is found in it? Every app should fix it in it's code, that a mess!

**Comment by scotchi** [comment]
Yes, basically.  Apps know a lot more about their users and can make things configurable in GUIs.  I don't think guessing at this in TagLib fits within the scope of the library.

When you write a library that deals with real world data this is always an issue -- you have to decide how far you want to go in dealing with broken files before saying, "This is out of scope."  TagLib's approach here was to say, "We'll make this possible, but working around the brokenness feels out of scope for the library itself."  There's a lot of possibility for errors there, and it's just a route that I don't really want to go down.  There are files that use multiple wrong encodings in the same file, there are languages that share words, but not charsets -- there's just a lot of possibility for this being a mess, and to some extent messing up people's files, which is something that isn't desirable in something like TagLib that effectively works as the reference implementation of a lot of tagging standards.

But also, if you want to ship a library that developers can also links to that solves this problem, you could literally make it where just compiling against that library in addition to TagLib would add the stuff you're suggesting.

**Comment by unxed** [comment]
> There's a lot of possibility for errors there. There are files that use multiple wrong encodings in the same file, there are languages that share words, but not charsets -- there's just a lot of possibility for this being a mess

How did developers of popular players (WinAmp etc) cope with this during the popularity of v1 tags? They certainly did not consider the encoding to always be ISO 8859-1

If you want to be a reference implementation without quircks, make detection-by-locale (just how it worked in WinAmp 2.95 for example) a build option disabled by default. Let's distro makers enable it if they want to take care not only of formal standards compliance, but also about user experience of real world users.

**Comment by unxed** [comment]
At the same time, of course, I made a [ticket in qmmp](https://sourceforge.net/p/qmmp-dev/tickets/1173/) too, and I will be glad if the author finds a way to solve the problem on his side.

**Comment by scotchi** [comment]
Just for the record, TagLib supports loads of quirks -- again, it's a question we've had to sit with and sometimes we add things, sometimes we don't, but as a general rule adding a quirk should never result in mis-parsing valid files (which is actually what this bug report was originally about -- it wasn't a plea to add codepage detection, it was a complaint that a distribution had done exactly what your patch does, and that was messing up parsing their files), and should be relatively well defined.  Like, when some taggers mess up field delimiters, or add nulls in wrong places or whatever, we can work around those things without degrading quality elsewhere, but choosing compromises that are guesses is a bit too fuzzy for a library like TagLib.

Again, this is literally a bug report about what happened when a distribution added a patch like yours.  windows-1251 and ISO-8859-1 overlap for English, but assuming windows-1251 when it's the system encoding breaks the extended characters in tags in non-English Western European languages.

I'm totally in favor of folks creating tools that clean these things up, add heuristics comparing against a corpus to guess encodings, look at whole tags or tag collections to guess at things, etc., and then write those back out in unicode.  But those things shouldn't be done at the TagLib level.

**Comment by unxed** [comment]
Okay, I understand the maintainers' position regarding the risks of incorporating encoding heuristics directly into the TagLib core and the preference for handling this at the application level using `ID3v1::StringHandler`. Repeatedly arguing for the patch inclusion seems unproductive at this point.

However, the problem of legacy ID3v1 encodings remains a practical issue for many users and applications, as evidenced by the related qmmp/Ubuntu tickets.

Perhaps we could explore ways to make the *recommended* application-level solution easier or more consistent?

1.  **Utility Data:** Would the maintainers consider adding the `locale -> codepage` mapping table (similar to the one I posted earlier) as utility data or a helper function within TagLib? This wouldn't force TagLib to *use* it automatically, but it would prevent every application developer from having to research, implement, and maintain their own potentially buggy version of this mapping when creating a custom `StringHandler`.
2.  **Documentation/Examples:** Could the documentation for `ID3v1::StringHandler` be enhanced with a clear example showing how an application *could* implement locale-based or even `uchardet`-based encoding detection for ID3v1 tags?
3.  **Helper Library:** As @scotchi suggested, a separate helper library might be the way to go. Would the TagLib project be open to potentially linking to or mentioning such a library in its documentation as a community resource for handling legacy encodings, if one were created?

This approach would keep the core library clean and standard-compliant, while still providing resources to help application developers address this common real-world issue more effectively using the intended mechanisms.
