### ISSUE TITLE
Trouble compiling taglib2 branch with libc++

### ISSUE THREAD

**Issue by sbooth** [taglib/taglib#196]
I've recently checked out the taglib2 branch and I'm not able to compile it on Mac OS X using clang and libc++ (not the default C++ standard library) .  It seems that `CMAKE_CXX_FLAGS` is ignored  by `check_cxx_source_compiles` and so cmake wants to use `tr1::shared_ptr` which is available in the system's default C++ standard library but not in the one I'm specifying in the flags (`-std=gnu++11 -stdlib=libc++`).  The end result is that `taglib_config.h` directs taglib to use the tr1 version of shared_ptr which doesn't exist in libc++:

```
In file included from /Volumes/Home/sbooth/Development/taglib/taglib/mpeg/mpegfile.cpp:26:
In file included from /Volumes/Home/sbooth/Development/taglib/taglib/tagunion.h:29:
In file included from /Volumes/Home/sbooth/Development/taglib/taglib/tag.h:30:
In file included from /Volumes/Home/sbooth/Development/taglib/taglib/toolkit/tstring.h:29:
In file included from /Volumes/Home/sbooth/Development/taglib/taglib/toolkit/tbytevector.h:31:
/Volumes/Home/sbooth/Development/taglib/taglib/toolkit/tsmartptr.h:34:11: fatal error: 'tr1/memory' file not found
# include <tr1/memory>
          ^
1 error generated.
```

**Comment by TsudaKageyu** [comment]
Can be closed.
