### ISSUE TITLE
ID3 tags are always created in TagLib::MPEG::File initialization

### ISSUE THREAD

**Issue by rbaulin** [taglib/taglib#250]
During initialization the read function is called:

    if(isOpen())
       read(readProperties, propertiesStyle);

In the end of read function both id3v1 and id2v2 are created

    ...
    ID3v2Tag(true);
    ID3v1Tag(true);
    }

This makes impossible to inspect whether the file really has these id3 tags or not. As an implication, non-mpeg files can be damaged during id3 tags check and save.
Seems like the bug was introduced 5 years ago from now in [this commit](https://github.com/taglib/taglib/commit/37e2d6293f6312fb1fa7383d42726dc10e733a27).

Please follow [this question of StackOverflow](http://stackoverflow.com/questions/4404705/unexpected-non-null-return).

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
