### ISSUE TITLE
APEv2 tag 'Cover Art (Front)' reading result in segfault

### ISSUE THREAD

**Issue by brunoleon** [taglib/taglib#261]
Taglib crashes when reading any Musepack with cover art in the tag.

I discovered this one by using Amarok which in turns crashes because of this issue.

Tried with taglib 1.8 and latest master (2013-07-13)

test@test-VirtualBox:~/taglib/taglib/examples$ ./framelist /media/sf_VboxShared/test.mpc 
******************** "/media/sf_VboxShared/test.mpc"********************
ID3v2.4.0, 0 bytes in tag

ID3v1
title   - ""
artist  - ""
album   - ""
year    - "0"
comment - ""
track   - "0"
genre   - ""

APE
ALBUM - "Headlines and Deadlines: The Hits of a-ha"
ALBUM ARTIST - "a-ha"
ALBUMARTISTSORT - "a-ha"
ARTIST - "a-ha"
ARTISTSORT - "a-ha"
ASIN - "B000006SA5"
BARCODE - "075992677325"
CATALOGNUMBER - "7599-26773-2"
COMMENT - "1980s (Songs-DB_Custom1)"
Segmentation fault (core dumped)

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
