### ISSUE TITLE
Removing album art doesn't reduce filesize for most file formats

### ISSUE THREAD

**Issue by dukeyin** [taglib/taglib#299]
I tested MP3, MP4, and FLAC with a 4 MB jpeg.  Removing art will cause TagLib and other programs to no longer see the embedded art, but the filesize remains at 4+ MB.

Only Ogg's filesize was reduced when art was removed:

```
TagLib::Ogg::Vorbis::File audioFile
TagLib::Ogg::XiphComment *tag = audioFile.tag();
tag->removeField("METADATA_BLOCK_PICTURE", TagLib::String::null);
```

(where the field was a base64 string)

It's possible I'm doing it wrong for MP3, MP4, and FLAC.  Just to verify, this is the essentially what code I'm running to remove:

MP4:

```
tag->itemListMap().erase("covr");
audioFile.save();
```

MP3:

```
tag->removeFrames("APIC");
audioFile.save();
```

FLAC:

```
audioFile.removePictures();
audioFile.save();
```

**Comment by beeb** [comment]
For MP3, saving non-image tags to temporary variables, then `strip`ping all tags and re-writing the saved ones effectively removes the image data from the file. Since other formats don't have the `strip` option, I couldn't find a way to do it.

**Comment by nightbirdsevolve** [comment]
@beeb dude, the issue is closed. They fixed in in v1.10! (Copy/Strip/Paste Back was a painful and dirty hack).

**Comment by beeb** [comment]
@nightbirdsevolve didn't find anything in the doc.. removing the `covr` tag in a m4a didn't shrink the file size for me, how do you do it?

**Comment by beeb** [comment]
@nightbirdsevolve wait actually i just checked and removing the `covr` item in a m4a doesn't shrink the file size (in 1.10)

**Comment by nightbirdsevolve** [comment]
@beeb my bad. Seems it was fixed for ID3 only. See #447
