### ISSUE TITLE
crash when reading flac file

### ISSUE THREAD

**Issue by nerijus** [taglib/taglib#308]
tagreader.cpp from examples crashes on http://sat.lt/test.flac :

Program received signal SIGSEGV, Segmentation fault.
0x0000003440f49276 in __memcpy_ssse3_back () from /lib64/libc.so.6
(gdb) bt
#0  0x0000003440f49276 in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x00007ffff7d568a2 in TagLib::ByteVector::replace(TagLib::ByteVector const&, TagLib::ByteVector const&) () from /lib64/libtag.so.1
#2  0x00007ffff7d28ac9 in TagLib::ID3v2::SynchData::decode(TagLib::ByteVector const&) ()
   from /lib64/libtag.so.1
#3  0x00007ffff7d2817d in TagLib::ID3v2::FrameFactory::createFrame(TagLib::ByteVector const&, TagLib::ID3v2::Header*) const () from /lib64/libtag.so.1
#4  0x00007ffff7d2c68f in TagLib::ID3v2::Tag::parse(TagLib::ByteVector const&) ()
   from /lib64/libtag.so.1
#5  0x00007ffff7d2c929 in TagLib::ID3v2::Tag::read() () from /lib64/libtag.so.1
#6  0x00007ffff7d2ca3b in TagLib::ID3v2::Tag::Tag(TagLib::File*, long, TagLib::ID3v2::FrameFactory const*) () from /lib64/libtag.so.1
#7  0x00007ffff7d5d2e4 in TagLib::FLAC::File::read(bool, TagLib::AudioProperties::ReadStyle) ()
   from /lib64/libtag.so.1
#8  0x00007ffff7d5d620 in TagLib::FLAC::File::File(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /lib64/libtag.so.1
#9  0x00007ffff7d85372 in TagLib::FileRef::create(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /lib64/libtag.so.1
#10 0x00007ffff7d86036 in TagLib::FileRef::FileRef(char const*, bool, TagLib::AudioProperties::ReadStyle) () from /lib64/libtag.so.1
#11 0x000000000040173b in main ()

OS Fedora 19.

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.

**Comment by nerijus** [comment]
It is fixed, but not in a taglib release. The bug should not be closed, as it will be reported again.

**Comment by lalinsky** [comment]
We have a practice of closing issues when they are merged, not released.
