### ISSUE TITLE
Cover art support for Xiph comments

### ISSUE THREAD

**Issue by sbooth** [taglib/taglib#336]
This would apply to Ogg Vorbis, Speex, Opus, and FLAC.

http://mail.kde.org/pipermail/taglib-devel/2013-December/002609.html
http://wiki.xiph.org/VorbisComment#Cover_art

This wouldn't entail too much work other than adding a base 64 encoder/decoder and the accompanying support in `Ogg::File` and friends.

**Comment by FestusHagen** [comment]
#540 closes this?

-Enjoy

**Comment by TsudaKageyu** [comment]
You're right. Thanks!
