### ISSUE TITLE
taglib 1.9.1 crashes on Windows on Amarok's first_run_jingle.ogg

### ISSUE THREAD

**Issue by bvdv** [taglib/taglib#342]
I first found this issue in my own project, but can reproduce it on the example tagreader.exe. first_run_jingle.ogg is part of Amarok.

When running "tagreader.exe first_run_jingle.ogg" taglib crashes with the following error:

Expression: string subscript out of range in xstring line 1440 (on MSVC 2010 SP1)

The offending line is
```
memcpy(&d->data[0], s, length * sizeof(wchar_t));
```
in the function String::copyFromUTF16(const wchar_t *s, size_t length, Type t)
When this function is called with an empty string in s, d->data is first resized to 0, and then in the memcpy, d->data[0] is accessed, which is not a very good idea.

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
