### ISSUE TITLE
byteswap.h not found when cross-compiling using mingw32

### ISSUE THREAD

**Issue by dbogdanov** [taglib/taglib#359]
I end up with an error when I try to cross-compile using mingw32 on my Linux machine:

    In file included from /home/dimi/mingw/taglib-1.9.1/taglib/toolkit/tstring.cpp:36:0:
    /home/dimi/mingw/taglib-1.9.1/taglib/toolkit/tutils.h:40:23: fatal error: byteswap.h: No such file or directory 

How can this be fixed? As I understand, this is due to mingw does not include byteswap.h, where should I get it?

**Comment by scotchi** [comment]
I can't reproduce this with the current master branch.
