### ISSUE TITLE
Missing AudioProperties::bitDepth() and sampleFormat()

### ISSUE THREAD

**Issue by risingballs** [taglib/taglib#360]
Two essential audio properties cannot be queried by TagLib:
- bit depth (8, 16, 32, 64)
- sample format (pcm, float)

It would be highly appreciated to have these available.

**Comment by kfieldi5** [comment]
I would love to see these as well (bitdepth moreso than sample format)

**Comment by TsudaKageyu** [comment]
I think I can add this feature (at least bit depth) to #506 and it wouldn't be so hard.

**Comment by TsudaKageyu** [comment]
Currently, some classes have their own "bit depth" features in different names. For example:
```
APE::Properties::bitsPerSample(); // APE, MP4, WavPack
AIFF::Properties::sampleWidth();  // AIFF, FLAC, WAV
```
So I suggest that we choose one of them and mark other one deprecated.

**Comment by TsudaKageyu** [comment]
I took a brief look at this issue.

AIFF, APE, FLAC, MP4, TrueAudio, WAV and WavPack classes already have the feature.
MPC, MPEG, Opus, Speex, Vorbis and MOD related formats don't have the bit depth information.
ASF is the only format we can actually add the feature.

I added ```bitsPerSample()``` property to ```ASF::Properties```. But I wonder if we need to add it to other classes.

Any thougts?

**Comment by TsudaKageyu** [comment]
Additionally, I already added ```WAV::Properties::format()``` to get the sample format.

**Comment by kfieldi5** [comment]
Very interesting! Thanks Tsuda! Can I still just use
TagLib::RIFF::AIFF:Properties for wav though?
