### ISSUE TITLE
Tests fail on BE machines(ppc64,...)

### ISSUE THREAD

**Issue by jcajka** [taglib/taglib#384]
Hi,
I have encountered problems with tests while building taglib on ppc64. I have looked in to it and managed to fix it. I have already posted more details on fedora bugzilla alongside with my patch (https://bugzilla.redhat.com/show_bug.cgi?id=1097109).

**Comment by TsudaKageyu** [comment]
Hmm, I'm still not sure whether or not the problem has been fixed on real PowerPC machines.
Should we wait for someone to test it on a PPC machine or we can close this?

**Comment by jcajka** [comment]
Sorry, missed your request last year..., I will test it tomorrow, and report back results.

**Comment by jcajka** [comment]
Tests pass on ppc64(Fedora 20).

There are slight differences between ppc64 and x86_64 test log outputs("TagLib: String::copyFromUTF16() - Invalid UTF16 string" around "*::testUTF16*" tests), but it seems caused by tests running in parallel(? tests run using "make check")(some subsequent runs yields same results as on x86). 

Seems fixed, so closing this issue.

Thanks for resolving this! And sorry for long delay...

**Comment by TsudaKageyu** [comment]
Nice to hear it. Thanks!
