### ISSUE TITLE
Empty title tag although the file contains a title

### ISSUE THREAD

**Issue by Davlog** [taglib/taglib#395]
I want to check whether a file contains a title or not and if not they should be added to a list.

        for( int i = 0; i < fileList.size(); i++ ){
            TagLib::MPEG::File f( fileList.at(i).toStdString().c_str() );
            TagLib::Tag* tag = f.tag();

            qDebug() << tag->title().toCString(true);

            if( tag == NULL || tag->title() == TagLib::String::null ){
                missingList->addItem( fileList.at(i) );
            }
        }

This code above shows me the titles of 90% of my files. However a few are shown as empty although they are not. I checked with a program called EasyTag if they contain a title and they always do. Since I get a title in 90 cases of 100 and every file contains a title, there must be a bug.

**Comment by scotchi** [comment]
Don't have the data available to debug this one further.
