### ISSUE TITLE
Crashes in TagLib::ByteVector::replace()

### ISSUE THREAD

**Issue by Hieper** [taglib/taglib#416]
Since we swithced to TagLib 1.9.1 we've been receiving reports on a relatively common crash in TagLib:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0  libsystem_platform.dylib          0x00007fff8fedd160 _platform_memmove$VARIANT$Nehalem + 384
1  *.TagLib                          0x000000010be2a13b TagLib::ByteVector::replace(TagLib::ByteVector const&, TagLib::ByteVector const&) + 583
2  *.TagLib                          0x000000010be6fb26 TagLib::ID3v2::SynchData::decode(TagLib::ByteVector const&) + 99
3  *.TagLib                          0x000000010be45aeb TagLib::ID3v2::FrameFactory::createFrame(TagLib::ByteVector const&, TagLib::ID3v2::Header*) const + 529
4  *.TagLib                          0x000000010be304be TagLib::ID3v2::Tag::parse(TagLib::ByteVector const&) + 440

I've noticed that taglib / toolkit / tbytevector.cpp has seen some development since the 1.9.1 release. Would it be possible to patch 1.9.1 by updating just this file and its header?

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
