### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [taglib/taglib#442]
Would you like to [replace any double quotes](https://github.com/taglib/taglib/blob/a6f759cc9a8e2529ab15fc41790621b2af658ec0/taglib/fileref.h#L29 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by scotchi** [comment]
I'm going to close this one since at present I've not been convinced of the utility in making a change.  We may switch to prefixing the includes in TagLib 2.x, but that's not something we can change in the current series.
