### ISSUE TITLE
taglib as a cocoapod on OS X

### ISSUE THREAD

**Issue by DamienSirkis** [taglib/taglib#446]
I'm still trying to find the best way to integrate tag lib into Xcode projects. cmake is nice for portability but it doesn't make it trivial to drop tag lib into an Xcode project.

Does a cocoapod version of taglib already exist somewhere?

If not, would anyone be against me creating a fork for the sole purpose of checking in the xcode project (created by cmake) alongside the branch and creating a cocoapod from it? I could then update the pod when new versions of tag lib are available.

Thoughts?

**Comment by liaogang** [comment]
"https://github.com/DidierMalenfant/taglib-pod" , is a invalid address now.

**Comment by DidierMalenfant** [comment]
The repo is not maintained anymore as I stopped using cocapods. Unfortunately, there does not seem to be any way to remove pods once they are added to the trunk.
