### ISSUE TITLE
Removing album art doesn't reduce filesize, how do you force taglib in doing so ?

### ISSUE THREAD

**Issue by nightbirdsevolve** [taglib/taglib#447]
So it seems taglib uses a method called *padding* (zeroing-out bytes), when "erasing" data.
In consequence file-size is increased when necessary, but never decreased.

My question is, **can you force Taglib to free disk space and not use padding ?**
I haven't found a way through basic framework usage.

It would be most welcome for taglib to automatically reduce filesize when, say, new image size (be it 0 if the image is removed) is below half the size of the one previously in place, or say when a significant amount of bytes have been freed.

what do you guys think ?

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
