### ISSUE TITLE
Tag release 1.9.2 / 1.10.0

### ISSUE THREAD

**Issue by xhochy** [taglib/taglib#465]
Over a year has passed and no taglib release ;)

Especially https://github.com/taglib/taglib/commit/4a7d31c87bf41c1de21cb725176d5b34c2a95720 would be worth making a release as this fixes a lot of crashes in FLAC files.

Not sure about the version number as I did not see if there were any (breaking) API changes.

**Comment by tgurr** [comment]
Please do, it seems a bunch of useful fixes have landed in master since the latest release.

**Comment by MBach** [comment]
I agree :+1:

**Comment by bromix** [comment]
:+1:

**Comment by lalinsky** [comment]
No need to :+1:, I know this needs to be done. :)

I just don't want to release a version with more bugs than we are fixing, so I need to find a few days to thoroughly review all the changes we have in master. I realize this doesn't sound like something that should delay the release for so long, but unfortunately it does. Perhaps it shows that I'm not the best person to do the releases anymore.

**Comment by scotchi** [comment]
Cleaning up the list of issues at the moment, and this isn't actually a bug.
