### ISSUE TITLE
Divide by zero with fuzzed file 

### ISSUE THREAD

**Issue by tholin** [taglib/taglib#469]
Parsing the following file with the tagreader example results in a divide by zero.
https://www.dropbox.com/s/8onq93nsbo055dl/taglib_musepack_fpe.mpc

<pre>
$ gdb --args ~/repository/taglib/build/examples/tagreader taglib_musepack_fpe.mpc 
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/taglib/build/examples/tagreader...done.
(gdb) r
Starting program: /home/cocobo/repository/taglib/build/examples/tagreader taglib_musepack_fpe.mpc
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
******************** "taglib_musepack_fpe.mpc" ********************
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.

Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7a4ad4d in TagLib::MPC::Properties::readSV8 (this=this@entry=0x612290, file=file@entry=
    0x611d00) at /home/cocobo/repository/taglib/taglib/mpc/mpcproperties.cpp:220
220           d->length = (d->sampleFrames - begSilence) / d->sampleRate;
(gdb) print d->sampleRate
$1 = 0
(gdb) bt full
#0  0x00007ffff7a4ad4d in TagLib::MPC::Properties::readSV8 (this=this@entry=0x612290, 
    file=file@entry=0x611d00) at /home/cocobo/repository/taglib/taglib/mpc/mpcproperties.cpp:220
        data = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x6131c0}
        pos = 12
        begSilence = <optimized out>
        packetType = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
          static null = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x613160}
        packetSizeLength = 1
        packetSize = <optimized out>
        dataSize = <optimized out>
        readSH = true
        readRG = false
#1  0x00007ffff7a4bfe3 in TagLib::MPC::Properties::Properties (this=0x612290, file=0x611d00, 
    streamLength=204, style=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/mpc/mpcproperties.cpp:86
        magic = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
          static null = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x611df0}
#2  0x00007ffff7a49197 in TagLib::MPC::File::read (this=this@entry=0x611d00, 
    readProperties=readProperties@entry=true)
    at /home/cocobo/repository/taglib/taglib/mpc/mpcfile.cpp:320
No locals.
#3  0x00007ffff7a495af in TagLib::MPC::File::File (this=0x611d00, file=<optimized out>, 
    readProperties=<optimized out>, propertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/mpc/mpcfile.cpp:98
No locals.
#4  0x00007ffff7b98813 in TagLib::FileRef::create (
    fileName=0x7fffffffde70 "taglib_musepack_fpe.mpc", readAudioProperties=<optimized out>, 
    audioPropertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:255
        it = <optimized out>
        ext = {_vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, static null = {
            _vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, 
            static null = <same as static member of an already seen type>, 
            static WCharByteOrder = TagLib::String::UTF16LE, d = 0x610af0}, 
          static WCharByteOrder = TagLib::String::UTF16LE, d = 0x611da0}
#5  0x00007ffff7b99f72 in TagLib::FileRef::FileRef (this=0x7fffffffd8b0, fileName=<optimized out>, 
    readAudioProperties=<optimized out>, audioPropertiesStyle=<optimized out>)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:83
No locals.
#6  0x0000000000401d80 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/cocobo/repository/taglib/examples/tagreader.cpp:41
        f = {_vptr.FileRef = 0x7ffff7dd6690 <vtable for TagLib::FileRef+16>, d = 0x7ffff6d31b60}
        i = <optimized out>
#7  0x00007ffff6d4adc5 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#8  0x0000000000405341 in _start ()
No symbol table info available.
</pre>

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
