### ISSUE TITLE
Infinite loop with fuzzed file (musepack)

### ISSUE THREAD

**Issue by tholin** [taglib/taglib#470]
Parsing the following file with the tagreader example results in an infinite loop.
https://www.dropbox.com/s/jk5pjvrqw5omu0o/taglib_musepack_infloop.mpc

I'm going to hold off reporting more problems in musepack until the reported are fixed.

<pre>
$ gdb --args ~/repository/taglib/build/examples/tagreader taglib_musepack_infloop.mpc
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/taglib/build/examples/tagreader...done.
(gdb) r
Starting program: /home/cocobo/repository/taglib/build/examples/tagreader taglib_musepack_infloop.mpc
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
******************** "taglib_musepack_infloop.mpc" ********************
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff6e11740 in __lseek_nocancel () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff6e11740 in __lseek_nocancel () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff6d9df36 in _IO_file_seekoff () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff6d9b837 in fseek () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff7a9fa4f in TagLib::FileStream::seek (this=0x611da0, <b>offset=-3,</b>
    p=TagLib::IOStream::Current) at /home/cocobo/repository/taglib/taglib/toolkit/tfilestream.cpp:396
        whence = <optimized out>
#4  0x00007ffff7a4af58 in TagLib::MPC::Properties::readSV8 (this=this@entry=0x612220, 
    file=file@entry=0x611d00) at /home/cocobo/repository/taglib/taglib/mpc/mpcproperties.cpp:243
        packetType = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
          static null = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x612ef0}
        packetSizeLength = 1
        packetSize = <optimized out>
        dataSize = 18446744073709551613
        readSH = false
        readRG = false
#5  0x00007ffff7a4bfe3 in TagLib::MPC::Properties::Properties (this=0x612220, file=0x611d00, 
    streamLength=147, style=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/mpc/mpcproperties.cpp:86
        magic = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
          static null = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x612f50}
#6  0x00007ffff7a49197 in TagLib::MPC::File::read (this=this@entry=0x611d00, 
    readProperties=readProperties@entry=true)
    at /home/cocobo/repository/taglib/taglib/mpc/mpcfile.cpp:320
No locals.
#7  0x00007ffff7a495af in TagLib::MPC::File::File (this=0x611d00, file=<optimized out>, 
    readProperties=<optimized out>, propertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/mpc/mpcfile.cpp:98
No locals.
#8  0x00007ffff7b98813 in TagLib::FileRef::create (fileName=0x7fffffffde6e "taglib_musepack_infloop.mpc", 
    readAudioProperties=<optimized out>, audioPropertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:255
        it = <optimized out>
        ext = {_vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, static null = {
            _vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, 
            static null = <same as static member of an already seen type>, 
            static WCharByteOrder = TagLib::String::UTF16LE, d = 0x610af0}, 
          static WCharByteOrder = TagLib::String::UTF16LE, d = 0x611d70}
#9  0x00007ffff7b99f72 in TagLib::FileRef::FileRef (this=0x7fffffffd8b0, fileName=<optimized out>, 
    readAudioProperties=<optimized out>, audioPropertiesStyle=<optimized out>)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:83
No locals.
#10 0x0000000000401d80 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/cocobo/repository/taglib/examples/tagreader.cpp:41
        f = {_vptr.FileRef = 0x7ffff7dd6690 <vtable for TagLib::FileRef+16>, d = 0x7ffff6d31b60}
        i = <optimized out>
#11 0x00007ffff6d4adc5 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#12 0x0000000000405341 in _start ()
No symbol table info available.
(gdb) up 4
#4  0x00007ffff7a4af58 in TagLib::MPC::Properties::readSV8 (this=this@entry=0x612220, 
    file=file@entry=0x611d00) at /home/cocobo/repository/taglib/taglib/mpc/mpcproperties.cpp:243
243           file->seek(dataSize, File::Current);
(gdb) print dataSize
$1 = 18446744073709551613
print (int)dataSize
<b>$3 = -3</b>
</pre>

**Comment by TsudaKageyu** [comment]
Already fixed. Should be closed.
