### ISSUE TITLE
Xiph tags containing dashes get truncated

### ISSUE THREAD

**Issue by HessiJames** [taglib/taglib#497]
Xiph tags containing dashes get truncated before the dash by TagLib::Tag::title() and other methods returning strings (artist, album, comment, genre).
Those strings get split by the dash and the tags show up multiple times in the TagLib::Tag's property map. See the output of the tagreader example reading the test file linked below:

```
-- TAG (basic) --
title   - "Title, Included part"
artist  - "Artist: Included part"
album   - "Album"
year    - "2015"
comment - ""
track   - "1"
genre   - "Other"
-- TAG (properties) --
ALBUM       - "Album"
ALBUM       - "Truncated part"
ARTIST      - "Artist: Included part"
ARTIST      - "Truncated part"
DATE        - "2015"
GENRE       - "Other"
TITLE       - "Title, Included part"
TITLE       - "Truncated part"
TRACKNUMBER - "01"
-- AUDIO --
bitrate     - 94
sample rate - 44100
channels    - 1
length      - 0:30
```

Instead e. g. the title tag should be: "Title, Included part - Truncated part".
I tested this with an ogg file as well with the same result, mp3 works fine.
The used taglib version is 1.9.1.

Here is the original report by @jpalaciosdev from: https://github.com/HessiJames/soundkonverter/issues/20

> In some circumstances, when a tag includes the substring " - ", the tag is truncated at the start of that substring. This happens always if some punctuation characters are present in the preceding string.
For example, in the string "Title: this part is included - This is not included", the substring " - This is not included" is not transferred to the destination tag of the converted file.
I created a test file with some tags (download it from here [1]). Please, note that in this case, the tag 'ALBUM' is also affected, although there are no other precedent punctuation symbols.
> 
> [1] https://dl.dropboxusercontent.com/u/66933796/test.flac

**Comment by sbooth** [comment]
I ran `metaflac` on the file:

````
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 1072 bytes
  maximum framesize: 1323 bytes
  sample_rate: 44100 Hz
  channels: 1
  bits-per-sample: 16
  total samples: 1323000
  MD5 signature: b668fb56f6dbeee3c330e32f38ba0b3d
METADATA block #1
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 236
  vendor string: reference libFLAC 1.3.1 20141125
  comments: 9
    comment[0]: TITLE=Title, Included part
    comment[1]: TITLE=Truncated part
    comment[2]: ARTIST=Artist: Included part
    comment[3]: ARTIST=Truncated part
    comment[4]: ALBUM=Album
    comment[5]: ALBUM=Truncated part
    comment[6]: DATE=2015
    comment[7]: TRACKNUMBER=01
    comment[8]: GENRE=Other
METADATA block #2
  type: 1 (PADDING)
  is last: true
  length: 149
````

so it actually contains multiple `TITLE` comments.  I believe that TagLib handles the file correctly.

**Comment by jpalaciosdev** [comment]
I was using Easytag to tag the files, and.... it turns out that this splitting 'thing' (that i was unaware until now) is an Easytag 'feature' that is enabled by default. Luckyly, this behaviour can be disabled in the options. You can read more of this here: https://github.com/stsquad/easytag/issues/19

My mistake, sorry for the inconvenience.
