### ISSUE TITLE
Reserved bit set

### ISSUE THREAD

**Issue by albertxing** [taglib/taglib#498]
I'm using taglib to set some tags:

    TagLib::MP4::File fr(filename.c_str());
	fr.tag()->setTitle(name.c_str());
	fr.tag()->setArtist(artist.c_str());
	fr.tag()->setAlbum(album.c_str());
	fr.tag()->setTrack(track_num);
	fr.save();

Pretty self-explanatory.
Running VS2013. Built Taglib with MSVC with no special options passed to `cmake` except path. No zlib.

Funny thing happens when I compile. Running the program from VS (clicking Local Windows Debugger button, set to Release) results in no issues, the program works perfectly.

However, if I run the program from the command line (separate from VS), the tags are written (they appear properly in Windows Explorer), but the M4A file is corrupted. If I try to play the file using ffplay, it gives:

````
[aac @ 00000000044bdb80] Reserved bit set.
[aac @ 00000000044bdb80] Number of bands (3) exceeds limit (1).
[aac @ 00000000044bdb80] channel element 3.4 is not allocated
[aac @ 00000000044bdb80] channel element 2.5 is not allocated
[aac @ 00000000044bdb80] Reserved bit set.
[aac @ 00000000044bdb80] Sample rate index in program config element does not match the sa
mple rate index configured by the container.
[aac @ 00000000044bdb80] Inconsistent channel configuration.f=0/0
[aac @ 00000000044bdb80] get_buffer() failed
[aac @ 00000000044bdb80] Inconsistent channel configuration.
[aac @ 00000000044bdb80] get_buffer() failed
[aac @ 00000000044bdb80] Inconsistent channel configuration.
[aac @ 00000000044bdb80] get_buffer() failed
...
````

Any ideas or suggestions?

**Comment by TsudaKageyu** [comment]
Hi @albertxing, it's weird and needs to be fixed. So I have some things to ask you.

What version of TagLib you tried? Some official release or the latest GitHub snapshot? 
Could you provide us with both correct and corrupt files you created?

**Comment by albertxing** [comment]
@TsudaKageyu I'm using 1.9.1 from the site (the official release).
I played around with some more audio files that I generated using Audacity, but all the ones I generated worked fine with both VS and in the command line.
This made me suspect that the files I were working with were somehow corrupted or poorly encoded...

Working file:
https://db.tt/gAedZQNp

Broken file:
https://db.tt/fRYLJ2tG

Generated tone:
https://db.tt/lovxN1g7

In case this helps, here's the output of ffprobe for the tone I generated (that works with the command line program):
````
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tone2.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: isomiso2
    track           : 42
    artist          : Octocat
    album           : Taglib test tones
    title           : Sine waves
    encoder         : Lavf55.33.100
  Duration: 00:00:01.04, start: 0.000000, bitrate: 210 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 197 kb/
s (default)
    Metadata:
      handler_name    : SoundHandler
````

And for the broken file:
````
[aac @ 0000000002dc7060] Reserved bit set.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '10 Wild Winds - broken.m4a':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    track           : 10
    artist          : The Honey Trees
    album           : Bright Fire
    title           : Wild Winds
    creation_time   : 2014-12-14 09:52:06
  Duration: 00:04:02.42, start: 0.000000, bitrate: 320 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 317 kb/
s (default)
    Metadata:
      creation_time   : 2014-12-14 09:52:06
      handler_name    : SoundHandler
````

**Comment by albertxing** [comment]
Okay, good news. I tried compiling and using the current snapshot from master, and everything works as it should. So it seems this was somehow fixed?

Feel free to close the issue if you feel it is obsolete.

**Comment by TsudaKageyu** [comment]
Good news. We have fixed a lot of bugs including MSVC and Windows specific ones since v1.9.1 was released. It looks like one of those bugs caused this issue.

**Comment by albertxing** [comment]
Great, I'm going to close the issue then.
