### ISSUE TITLE
QStringToTString macro uses non-existing QString::utf8() method

### ISSUE THREAD

**Issue by flaviotordini** [taglib/taglib#499]
Using QStringToTString causes a compile-time error. The macro uses QString::utf8() which doesn't exist instead of QString::toUtf8()

**Comment by sbooth** [comment]
It looks like `utf8()` is a QT 3 function that was replaced by `toUtf8()` in QT 4.  From a quick glance at the QT 4 source it looks like `#define QT3_SUPPORT` might fix the problem.

**Comment by flaviotordini** [comment]
QT3_SUPPORT is not present in Qt 5, so I don't think it is an option. Just replace utf8() with toUtf8() and it will work with Qt 4 & 5.

**Comment by TsudaKageyu** [comment]
I remember @lalinsky said that those macros are kind of obsolete and will be removed in the future.

Privately, I recommend doing like ```QString::fromWCharArray(s.toCWString(), s.size());``` as a simple and efficient way of converting ```TagLib::String``` into ```QString```. ```QStringToTString``` is not efficient due to useless conversion to and from UTF-8.

**Comment by sbooth** [comment]
Removal is probably the best answer, especially if they are inefficient.  Is QT3 still in widespread use or would it make sense to make the change suggested by @flaviotordini for QT5 compatibility?

**Comment by scotchi** [comment]
Why not use QT_VERSION to check which version is in use?  For the master branch (i.e. 1.x), I'd consider it breaking the compatibility guarantees to remove a macro that is probably no longer used, but is part of the public API.

**Comment by sbooth** [comment]
That's a good idea, maybe something like:

```c++
#if QT_VERSION >= 0x040000
# define QStringToTString(s) TagLib::String(s.toUtf8().data(), TagLib::String::UTF8)
#else
# define QStringToTString(s) TagLib::String(s.utf8().data(), TagLib::String::UTF8)
#endif
```

and do something analogous for `TStringToQString`
