### ISSUE TITLE
Add support for .aac files (AAC in ADTS)

### ISSUE THREAD

**Issue by ghost** [taglib/taglib#508]
For .AAC files, is there a way to create an audio header so I can edit tags and whatnot?

**Comment by TsudaKageyu** [comment]
.AAC files are already supported by ```MP4::File``` class, but ```FileRef``` doesn't recognize the extension. Should we add ```".aac"``` to ```FileRef```?

**Comment by lalinsky** [comment]
`MP4::File` only supports AAC-in-MP4, not AAC-in-ADTS (which is basically just raw AAC with extra synchronization headers).

**Comment by TsudaKageyu** [comment]
I see, I'd like to look for further information. Thanks.

**Comment by shaforostoff** [comment]
i have extended audio attribute parsing, now samplerate is read correctly, and it even provides an estimate for bitrate and length

**Comment by kluszon** [comment]
As I see aac files still aren't support and recognized by `FileRef`. Can we do sth with it?

**Comment by shaforostoff** [comment]
> As I see **.aac** files still aren't support and recognized by `FileRef`. Can we do sth with it?

taglib author seems to be reluctant to add new stuff to mainline, i have a bunch of fixes since 2018 and none of them has been included. so this projects needs to be forked, I guess.

as for aac support, you are welcome to use my patch: https://github.com/taglib/taglib/pull/856/

**Comment by ufleisch** [comment]
Implemented with #856.
