### ISSUE TITLE
TagLib::MPEG::File::ID3v1Tag() returns random pointers

### ISSUE THREAD

**Issue by amethystAnt** [taglib/taglib#509]
I am trying to open tags in an MPEG file. When I call TagLib::MPEG::File::ID3v1Tag() or TagLib::MPEG::File::Id3v2Tag() or TagLib::MPEG::File::APETag(), sometimes it returns a valid pointer to the tag, sometimes it doesn't. Calling TagLib::MPEG::has*() has the same effect. When it returns a valid pointer of the tag, I can successfuly read all the properties such as artist, album etc. But sometimes it returns nothing when I run exactly the same code. And when I use TagLib::FileRef instead, it always works. I have tried to find a bug in my code, but the only result is that it is a bug of TagLib.

Perhaps my source code can be helpful (see AudioFile::open() ):  https://github.com/amethystAnt/openMusicTagger/blob/master/src/audiofile.cpp

**Comment by amethystAnt** [comment]
I wonder... is it really a bug or am I idiot? I forgot to mention that when I call TagLib::MPEG::File::ID3v2Tag(), I pass 'true' as the second parameter, because I want to create a new tag if it doesn't exist. But in some cases, it returns pointer to the existing tag, and in other cases it returns a new one. That's really confusing. I am sorry if I do something wrong in my code.

**Comment by lalinsky** [comment]
I'm sorry, but it's not really clear to me what is happening. Do you mean that if you run your code on the same file multiple times, you get different results?

**Comment by lalinsky** [comment]
This is probably unrelated, but you should not use `path.toStdString().c_str()` for handling file names, if you want to be able to open non-ascii file names.

See https://bitbucket.org/acoustid/acoustid-fingerprinter/src/fb80fb843fd25d51b4d5334f22b31121fa3db677/tagreader.cpp?at=master#cl-227

**Comment by amethystAnt** [comment]
Probably this is the mistake. I corrected the string conversion and it seems that it works now. Thank you for the answer.

**Comment by scotchi** [comment]
That's not actually what fixed your bug.  From your code:

    TagLib::FileName fileName = path.toStdString().c_str();

The result `c_str()` becomes invalid as soon as the object it belongs to is destroyed.  In the case of that line, that happens as soon as the temporary value created by `toStdString()` has been destroyed (i.e. before moving on to the next line of code).

This would have worked as well, though also been incorrect in terms of opening non-ASCII file names:

    std::string s = path.toStdString();
    TagLib::FileName fileName = s.c_str();

**Comment by scotchi** [comment]
And incidentally, you'd have had the exact same issue if you'd written this in your updated version:

    TagLib::FileName fileName = QFile::encodeName(path).constData();

Storing the temporary value is what made the difference, not using the right conversion function.

**Comment by amethystAnt** [comment]
I'm gonna fix it. Thank you very much.

**Comment by amethystAnt** [comment]
The bug I reported is happening again. I realised that that it couldn't be caused by the temporary values, because it returns me a valid pointer to the ID3v2 tag and invalid pointers to the ID3v1 and APE tags. (In fact, it returns me a pointer to an empty tag, because I set true as the first parameter to the function TagLib::MPEG::File::ID3v1Tag() )
