### ISSUE TITLE
Invalid rendering of empty fields in ID3v2

### ISSUE THREAD

**Issue by EvilSquirrel** [taglib/taglib#512]
The ID3v2 spec clearly states: `A frame must be at least 1 byte big, excluding the header.`
Frames with a zero length are thus not allowed; this is handled by TagLib when reading ID3v2 frames (although it completely stops parsing of the remaining frames, as reported by others already).

The problem lies here:
``` c++
ByteVector Frame::render() const
{
  ByteVector fieldData = renderFields();
  d->header->setFrameSize(fieldData.size());
  ByteVector headerData = d->header->render();

  return headerData + fieldData;
}
```
When rendering an empty frame, in my case an empty WOAF, renderFields() returns empty data and the frame size is set to zero. As a result, TagLib generates invalid data and is unable to re-read its own output.

Original frame data read from MP3 file:
`57 4F 41 46 00 00 00 01 00 00 00`
Data saved by TagLib back to the file:
`57 4F 41 46 00 00 00 00 00 00`

**Comment by sbooth** [comment]
I don't think that an empty `WOAF` frame is valid even if the URL is empty.  The way I read the spec there should be a null byte separating the description and URL text regardless of content:

> <Header for 'User defined URL link frame', ID: "WXXX">
>     Text encoding     $xx
>     Description       <text string according to encoding> $00 (00)
>     URL               <text string>

Could this be a bug in `UserUrlLinkFrame::renderFields()`?

**Comment by scotchi** [comment]
The change here looks fine, but the unit test seems wrong.  It doesn't seem to actually test if the frame is discarded.

**Comment by TsudaKageyu** [comment]
You are right, it's a silly omission.
