### ISSUE TITLE
ID3v2 chapter frame parsing fails with no sub-frames

### ISSUE THREAD

**Issue by EvilSquirrel** [taglib/taglib#513]
The code in ChapterFrame::parseFields() looks like this:
``` c++
size -= pos;
while((uint)embPos < size - header()->size()) {
    Frame *frame = FrameFactory::instance()->createFrame(data.mid(pos + embPos), d->tagHeader);
    [...]
```
When there are no sub-frames in the chapter, `size` will at that point be zero and since all the ints are unsigned, the right side of the test will rollover. At the very least, an extra test should be added in front of the while: `if (size > 0)` Note that the test will still fail if size is less than `header()->size()`, so an even better idea would be to stop using unsigned ints in calculations!

**Comment by FestusHagen** [comment]
My math is a little fuzzy so help me out ...

At that point `size` is at least 18 bytes.
`pos` is 4x4=16 bytes.
18-16=2

**Comment by EvilSquirrel** [comment]
No, at that point pos is 16 + the size of the element ID.
``` c++
int pos = 0, embPos = 0;
d->elementID = readStringField(data, String::Latin1, &pos).data(String::Latin1);
[...]
size -= pos;
```
If there are no sub-frames, `pos` will be equal to `size` and thus `size` will be set to zero.

**Comment by FestusHagen** [comment]
Whoops ... Missed the fact that `readStringField()` modifies `pos`.

Told ya my math was fuzzy, should of said my brain though!
