### ISSUE TITLE
amarokcollectionscanner crashed with SIGSEGV in TagLib::ByteVector::replace() 

### ISSUE THREAD

**Issue by Clonewayx** [taglib/taglib#519]
while scanning the collection...

ProblemType: Crash
DistroRelease: Ubuntu 14.04
Package: amarok-utils 2:2.8.0-0ubuntu3
ProcVersionSignature: Ubuntu 3.13.0-35.62-generic 3.13.11.6
Uname: Linux 3.13.0-35-generic x86_64
ApportVersion: 2.14.1-0ubuntu3.3
Architecture: amd64
CrashCounter: 1
CurrentDesktop: KDE
Date: Sat Sep 6 14:08:12 2014

at: https://bugs.launchpad.net/ubuntu/+source/taglib/+bug/1366317

**Comment by TsudaKageyu** [comment]
It seems like the same error as #518 and #308 which has been fixed at #309. Unfortunately, we caught the bug after the latest version of TagLib was released.
I'd like to confirm if it has actually been fixed. Could you provide the file that caused the error?

**Comment by Clonewayx** [comment]
https://bugs.launchpad.net/ubuntu/+source/taglib/+bug/1433319/+attachment/4348416/+files/American%20Beauty.flac

**Comment by TsudaKageyu** [comment]
Thanks!
I confirmed that the bug is the same as the ones I mentioned. The next release of TagLib will work fine.

**Comment by AOrobator** [comment]
Is there some sort of release schedule posted anywhere?

**Comment by scotchi** [comment]
There's not a release schedule yet, but we realize that it's something that should happen soon.
