### ISSUE TITLE
TrueAudio(.tta)  bitrate "arithmetic overflow"

### ISSUE THREAD

**Issue by billlin0904** [taglib/taglib#520]
/*
d->streamLength = 503215768;
d->length = 4337;

((503215768 * 8) / 4337) / 1000
*/

d->bitrate = d->length > 0 ? ((d->streamLength * 8L) / d->length) / 1000 : 0;

d->bitrate => 0xFFFFFFC2 (-62)

So... 

My solution below ... : )

d->bitrate = d->length > 0 ? (((long long)d->streamLength * 8L) / d->length) / 1000 : 0;

**Comment by TsudaKageyu** [comment]
I think that changing ```8L``` to ```8LL``` is a simpler solution.
Actually, pull request #506 has already fixed it by calculating it in ```double```. However, it's a big change to review and merge soon...

**Comment by billlin0904** [comment]
Awesome ~

**Comment by TsudaKageyu** [comment]
Is it better to fix those possible arithmetic overflows apart from #506? Any thoughts?

**Comment by lalinsky** [comment]
No, I'll try to merge the pull request soon. Sorry for not getting to it sooner.
