### ISSUE TITLE
Android NDK: fatal error: tstring.h: No such file or directory

### ISSUE THREAD

**Issue by imrankhanandroid** [taglib/taglib#523]
I am trying to compile Taglib for Android but getting following error:

[armeabi] Compile++ arm  : my_own_shared_lib <= tag_lib_personal.cpp
In file included from /home/extramarks/workspace_05_03_2015/AndroidNDKTagLib/jni/tag_lib_personal.cpp:5:0:
/home/extramarks/workspace_05_03_2015/AndroidNDKTagLib/jni/taglib/taglib/tag.h:30:21: fatal error: tstring.h: No such file or directory
compilation terminated.
make: *** [/home/extramarks/workspace_05_03_2015/AndroidNDKTagLib/obj/local/armeabi/objs/my_own_shared_lib/tag_lib_personal.o] Error 1

<b>Android.mk :<b>

MY_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := taglib_module
LOCAL_C_INCLUDES := $(MY_PATH)/taglib/
LOCAL_PATH := $(LOCAL_PATH)/taglib/taglib
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)\
		$(LOCAL_PATH)/tsss/include/taglib\
        $(LOCAL_PATH)/ape\
        $(LOCAL_PATH)/tsss\
        $(LOCAL_PATH)/toolkit\
        $(LOCAL_PATH)/asf\
        $(LOCAL_PATH)/flac\
        $(LOCAL_PATH)/it\
        $(LOCAL_PATH)/mod\
        $(LOCAL_PATH)/mp4\
        $(LOCAL_PATH)/mpc\
        $(LOCAL_PATH)/mpeg\
        $(LOCAL_PATH)/mpeg/id3v1\
        $(LOCAL_PATH)/mpeg/id3v2\
        $(LOCAL_PATH)/mpeg/id3v2/frames\
        $(LOCAL_PATH)/ogg\
        $(LOCAL_PATH)/ogg/flac\
        $(LOCAL_PATH)/ogg/opus\
        $(LOCAL_PATH)/ogg/speex\
        $(LOCAL_PATH)/ogg/vorbis\
        $(LOCAL_PATH)/riff\
        $(LOCAL_PATH)/riff/aiff\
        $(LOCAL_PATH)/riff/wav\
        $(LOCAL_PATH)/s3m\
        $(LOCAL_PATH)/trueaudio\
        $(LOCAL_PATH)/wavpack\
        $(LOCAL_PATH)/xm
        

FILE_LIST := $(foreach dir, $(LOCAL_EXPORT_C_INCLUDES), $(wildcard $(dir)/*.cpp))
LOCAL_SRC_FILES := $(FILE_LIST:$(LOCAL_PATH)/%=%)

LOCAL_EXPORT_CFLAGS := -DFOO=1
LOCAL_EXPORT_LDLIBS := -llog

LOCAL_ARM_MODE := arm

include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_PATH := $(MY_PATH)
LOCAL_MODULE := my_own_shared_lib
LOCAL_SHARED_LIBRARIES := taglib_module
LOCAL_SRC_FILES := tag_lib_personal.cpp

LOCAL_ARM_MODE := arm

include $(BUILD_SHARED_LIBRARY)

<b>tag_lib_personal.cpp :<b>

#include <jni.h> 
#include <stdio.h>
#include <taglib/taglib/fileref.h>
#include <taglib/taglib/tag.h>
#ifdef __cplusplus
extern "C"
{
#endif
    jstring Java_com_mindtherobot_samples_ndkfoo_NdkFooActivity_invokeNativeFunction(JNIEnv* env, jobject javaThis) {
      return "taglib";
}
#ifdef __cplusplus
}
#endif

Please help me

**Comment by scotchi** [comment]
Sorry, but for whatever reason the project you have set up isn't finding the include directory for taglib/toolkit.  I do see that in what you posted, however.  Since that's an issue with your project though, rather than specifically with TagLib (and I don't think any of us are experienced in building for Android) I'm afraid that's something we can't really help with.
