### ISSUE TITLE
WMA file with GUID information generates corrupted files

### ISSUE THREAD

**Issue by bromix** [taglib/taglib#524]
We have a wma file here and wondered why the file was corrupt after storing it with new information. After some investigation we found out that the GUID information (e.g. **WM/MediaClassPrimaryID, WM/MediaClassSecondaryID, ...**) will be read correctly, but if it comes to write the data to file, the file will get corrupt. Only the VLC player can play those audio files after that.

Our workaround for now is to iterate all information of the map and remove every information of the type GUID. After that everything is fine.

**Comment by TsudaKageyu** [comment]
Hi @bromix, 
I'm going to take a look at this problem. Although I'm going to try to reproduce it on my side, could you provide us with the file that causes it?

**Comment by bromix** [comment]
I try to provide a file tomorrow on monday.

**Comment by bromix** [comment]
@TsudaKageyu you've got mail :)

**Comment by TsudaKageyu** [comment]
Thanks @bromix, I received the files. Give me some more time to fix it.
