### ISSUE TITLE
OGG files corrupted after storing

### ISSUE THREAD

**Issue by bromix** [taglib/taglib#529]
I thought I was finished with wma #524 :)

But the test for Oggs failed. I just open an OGG file and store the file again. After that taglib can't read any meta data. I compared the test with a taglib from a year ago (2014.04-24) and the test is working, the file is okay and the meta data can be read.

Something you need to confirm this bug?

**Comment by TsudaKageyu** [comment]
OK, please send me the file like yesterday and give me some time. Thanks.

**Comment by TsudaKageyu** [comment]
I confirmed that something's going terribly wrong. This is obviously a bug which we should fix immediately. Thank for the catch, @bromix.

**Comment by bromix** [comment]
Thanks again ;) everything is working again on my side :+1: you rock!
