### ISSUE TITLE
Symbols not found for architecture x86_64 on OSX Yosemite

### ISSUE THREAD

**Issue by kfieldi5** [taglib/taglib#547]
I have tried (with my project using g++):

kevinbook:taglib kevin$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_ARCHITECTURES="x86_64" -DENABLE_STATIC=ON -DCMAKE_INSTALL_PREFIX="/usr/local/Qt5/5.4/clang_64" -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_CXX_FLAGS="-stdlib=libc++" .

as well as with clang being the compiler (and switching my project to build using clang++):

kevinbook:taglib kevin$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_ARCHITECTURES="x86_64" -DENABLE_STATIC=ON -DCMAKE_INSTALL_PREFIX="/usr/local/Qt5/5.4/clang_64" -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++" .

No matter what arguments I change, which compilers I use, I still get 

Symbols not found for architecture x86_64

Please help!!! 

TagLib::String::find
std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >::find(wchar_t const*, unsigned long, unsigned long) const

**Comment by kfieldi5** [comment]
I think the cause of this was because I had used homebrew to install a version of tablib (a while ago) and it was messing with the linkage

**Comment by scotchi** [comment]
Homebrew and your project are probably using different C++ compilers (clang vs. gcc) and / or you're not linking to the appropriate C++ lib (libc++ vs. libstdc++)
