### ISSUE TITLE
MPEG::File::findID3v2()?

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#609]
The implementation of ```MPEG::File::findID3v2()``` is very different from the counterparts in other classes. I wonder what is the purpose of the function. 

As far as I recognize, the function looks for the ID3v2 signature placed before the first MPEG frame. However, it looks like it returns only 0 or -1 in practice. Its counterparts in other classes (for example, ```MPC::File::findID3v2()```) definitely returns only 0 or -1. Is there some MP3 specific reason to have a special search algorithm?

**Comment by scotchi** [comment]
An ID3v2 tag is almost always at the very beginning of a file, but that's neither required nor specified, so the implementation looks for the ID3v2 tag using the signature from the ID3v2 spec.

**Comment by TsudaKageyu** [comment]
I see thanks.
By the way, an ID3v2.4 tag can be placed at the end of a file. Does somebody know some software writes an ID3v2 tag at the end of a file?

**Comment by TsudaKageyu** [comment]
Hmm, I found that ```MPEG::File::findID3v2()``` sometimes fails to skip an ID3v2 tag located after MPEG frames.
I fixed it and added a test in #601
