### ISSUE TITLE
Allow generating taglib.pc on Windows

### ISSUE THREAD

**Issue by noscript** [taglib/taglib#613]
Due to this condition ```taglib.pc``` is not generated:
```
if(NOT WIN32 AND NOT BUILD_FRAMEWORK)
  configure_file("${CMAKE_CURRENT_SOURCE_DIR}/taglib.pc.cmake" "${CMAKE_CURRENT_BINARY_DIR}/taglib.pc")
  install(FILES "${CMAKE_CURRENT_BINARY_DIR}/taglib.pc" DESTINATION "${LIB_INSTALL_DIR}/pkgconfig")
endif()
```
`pkg-config` works on Windows just fine. Please remove ```NOT WIN32``` condition to allow generating ```taglib.pc``` on Windows.

**Comment by TsudaKageyu** [comment]
Sounds good.
There will be no harm for someone doesn't have ```pkg-config```, except for the fact that useless ```taglib.pc``` is generated.

**Comment by TsudaKageyu** [comment]
We can close this one.

**Comment by noscript** [comment]
Thanks!
