### ISSUE TITLE
File::strip() and properties() may cause a segfault.

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#626]
```properties()``` of some ```File``` classes may cause a segfault in the case like this:
```
APE::File f("...");             // Open a file with an APE tag.
f.strip(APE::File::APE); 
PropertyMap m = f.properties(); // Segfault!
```
This is because, ```d->hasAPE``` is still true after an in-memory tag is deleted in ```strip()```.
```
PropertyMap APE::File::properties() const
{
  if(d->hasAPE)
    // d->tag.access<APE::Tag>(ApeAPEIndex, false) returns null.
    return d->tag.access<APE::Tag>(ApeAPEIndex, false)->properties();
```
So I think we should change the implementation of ```properties()``` like this:
```
  if(d->tag.access<APE::Tag>(ApeAPEIndex, false))
    return d->tag.access<APE::Tag>(ApeAPEIndex, false)->properties();
```
Though we have another option to change the behavior of ```strip()``` to remove the tag in file immediately. It would affect a lot of users.

Any thoughts?

**Comment by TsudaKageyu** [comment]
Oops! We can't use ```APETag()``` in ```properties()```, but you can see what I mean...

**Comment by TsudaKageyu** [comment]
A solution I came up with is like:

Add this function to ```TagUnion```
```
bool TagUnion::isEmpty(int index) const
{
  return (!d->tags[index] || d->tags[index]->isEmpty());
}
```
and modify ```properties()``` like this.
```
PropertyMap APE::File::properties() const
{
  if(!d->tag.isEmpty(ApeAPEIndex))
    return d->tag.access<APE::Tag>(ApeAPEIndex, false)->properties();
  if(!d->tag.isEmpty(ApeID3v1Index))
    return d->tag.access<ID3v1::Tag>(ApeID3v1Index, false)->properties();
  return PropertyMap();
}
```

**Comment by supermihi** [comment]
What's wrong with your initial solution? To me, it seems favorable because it does not involve changing TagUnion.

**Comment by TsudaKageyu** [comment]
I thought the case that an APE tag is empty, but not null.
If a file has an empty APE tag and filled ID3v1 tag, ```tag()``` returns a ```TagUnion``` that can access an ID3v1 tag, but ```properties()``` will return an empty ```PropertyMap```. TagLib may write such a file.

**Comment by TsudaKageyu** [comment]
Alternatively, we may create a non-member function like this instead of adding a function to ```TagUnion```.
```
bool isTagEmpty(const TagUnion &tagUnion, int index)
{
  return (!tagUnion[index] || tagUnion[index]->isEmpty());
}
```
