### ISSUE TITLE
FilePrivate* d is NULL

### ISSUE THREAD

**Issue by achabill** [taglib/taglib#633]
This code http://pastebin.com/Ngtzv8VY produes segfault.
Debug info: http://picpaste.com/pics/error-kCRehYaY.1437658765.PNG
Windows 10 Insider preview, taglib 1.9, Visual Studio 2012

**Comment by FestusHagen** [comment]
Please see example ```tagreader```, please build examples and run ```tagreader C:\Users\Bill\Desktop\Wrong.mp3```.

I have tested your code with master and v1.9, No issues, on the following OS's
WinXP, Win7, Win8.1, FreeBSD-8.2, FreeBSD-10.1, OSx10.5.8
and the following tools
MSVC2010, MSVC2012, various versions of GNU GCC and Qt.

FYI, Github comments support [Markdown](https://guides.github.com/features/mastering-markdown/)(Code Tags), Code posted remotely will soon die leaving this Issue report worthless for future reference.

**Comment by shadow-code** [comment]
same error when using `c:\Users\Bill\Desktop\Wrong.mp3`. I installed qt 5.0.2 prequilt mingw and built taglib with mingw and now it works. Why wouldn't it work with my own MSVC2012?
