### ISSUE TITLE
Segmentation fault, reading flac file (Ubuntu Trusty) 

### ISSUE THREAD

**Issue by daschuer** [taglib/taglib#635]
We have a found a flac file, that makes Mixxx crash. 
https://bugs.launchpad.net/mixxx/+bug/1411479
The effected file and backtraces are attached to the Launchpad bug. 
Form the back-traces, it looks like the segfault is caused by Taglib. 

Do you have any idea to avoid this crash? 
Thank you!

**Comment by TsudaKageyu** [comment]
It looks the same as #308. We fixed it at #309.
The next release of TagLib will work fine. Some software like [Clementine] (https://www.clementine-player.org/) incorporated that patch separately.

**Comment by daschuer** [comment]
I have noticed from you test data that you have fixed a lot more potential crashers since Version 1.9.1.
Which version, branch or commit would you recommend to include in our upcoming  release?

**Comment by TsudaKageyu** [comment]
Though I'm not sure of the exact schedule, we are going to release v1.10 soon.
So I recommend you to use it.

**Comment by daschuer** [comment]
Thank you for the answer. Does it mean just take the recent master or tag v1.10beta?

**Comment by lalinsky** [comment]
We should really release 1.10 in the next few days, so if you can wait for that, that would be the best option.

**Comment by daschuer** [comment]
Cool, thank you.

**Comment by daschuer** [comment]
Hi, 
we want to publish a release candidate of Mixxx now, including a recent Taglib version, that does not suffer the FLAC crasher. 
Can one of you point us to a Taglib commit which suits for that? 

Is it still realistic to release Mixxx with a 1.10 release version of Taglib before Christmas? 

Thank you very much.

**Comment by lalinsky** [comment]
Yes, I'll do the release today. Sorry about that.
