### ISSUE TITLE
Cannot remove ID3 tags from FLAC files.

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#646]
I got an email from a user that ```FLAC::File``` can remove neither ID3v1 nor v2 tags.
I realized the issue when working on #612, and I now think we should add the functionality to remove ID3 tags from FLAC files after v1.10 will be released.

I privately thinking of adding ```FLAC::File::strip()``` just like ```APE::File::strip()```.

**Comment by beeb** [comment]
One thing you could do (untested) for ID3v1 and APE tags would be to open the file with `APE::File` and use the `APE::File::strip()` function. Not sure it works for FLAC though.
