### ISSUE TITLE
Compiler warnings QT_VERSION is not defined

### ISSUE THREAD

**Issue by ufleisch** [taglib/taglib#650]
TagLib 1.10beta:

When including tstring.h I get compiler warnings like this:
```
.../include/taglib/tstring.h:45:5: warning: "QT_VERSION" is not defined [-Wundef]
 #if QT_VERSION >= 0x040000
     ^
```

Maybe the code in tstring.h `#if QT_VERSION >= 0x040000` could be changed to something like
```
#if defined QT_VERSION && QT_VERSION >= 0x040000
```

**Comment by TsudaKageyu** [comment]
Thanks. Fixed it.
Privately, I think we may surround ```QStringToTString``` and ```TStringToQString``` by ```#if defined(QT_VERSION)```. But it can be a kind of API breakage.
