### ISSUE TITLE
Ogg::XiphComment::setComment() doesn't remove field when empty

### ISSUE THREAD

**Issue by MBach** [taglib/taglib#653]
Hi,

I've just compiled Taglib 1.10 beta and it seems that I cannot remove standard field Comment on Opus Files with XiphComment block.

I've tried all others and they're working (title, artist, album, track, year and genre).

Regards,

**Comment by TsudaKageyu** [comment]
I guessing the cause... Does it still occur if you use ```comment()``` function before ```setComment()```? If my guess is correct, you can remove the comment if you use ```comment()``` before ```setComment()```.

**Comment by MBach** [comment]
You are right! That's quite weird but calling ```comment()``` before ```setCommet()``` actually clears the field.

**Comment by TsudaKageyu** [comment]
Thanks, I have located the cause.
