### ISSUE TITLE
Feature request. Custom tag suport

### ISSUE THREAD

**Issue by gerchicov-bp** [taglib/taglib#665]
TagLib implementation is not full! But you could make the situation better by providing a possibility to handle custom tags (reading/writing). For example I didn't found:
1)"singer" - it is not the same as "artist". Doesn't exist at all
2)"lyrics" - it exists somehow and somewhere but not in ```Tag``` class. Why?

P.S. I use FLAC but it is independent from this problem

**Comment by supermihi** [comment]
It's already there - please read the documentation of `File::properties()`and `File::setProperties()`.

**Comment by gerchicov-bp** [comment]
there is still something wrong. I added lyrics to flac file via MediaMonkey but it doesn't even show that such tag exists. Here is that file:
http://www.filedropper.com/01-fergalicious111232

I use the following code:
```String s = _file.tag()->properties().toString();
    NSString *str = [NSString stringWithCString:s.toCString(true) encoding:[NSString defaultCStringEncoding]];```

Result:
```ALBUM=4
ARTIST=2
COMMENT=comment
DATE=6000
GENRE=7
TITLE=1
TRACKNUMBER=5```

The lyrics is missed at all. And again ```ARTIST != SINGER```

**Comment by gerchicov-bp** [comment]
I forgot, I use 1.10BETA

**Comment by gerchicov-bp** [comment]
Oh sorry, I confused with ```Tag::properties()```. But it is really strange because all the properties are tag properties too

**Comment by supermihi** [comment]
Sorry, I can not reproduce your problem. Using `taglib/examples/tagreader` compiled with 1.10BETA on your file prints out the complete lyrics:
```
$ ./tagreader ~/Downloads/01\ -\ Fergalicious\ 11.12.32.flac 
******************** "/home/helmling/Downloads/01 - Fergalicious 11.12.32.flac" ********************
-- TAG (basic) --
title   - "1"
artist  - "2"
album   - "4"
year    - "6000"
comment - "comment"
track   - "5"
genre   - "7"
-- TAG (properties) --
ALBUM        - "4"
ALBUM ARTIST - "2"
ALBUMARTIST  - "2"
ARTIST       - "2"
COMMENT      - "comment"
COMPILATION  - "0"
DATE         - "6000"
ENSEMBLE     - "2"
GENRE        - "7"
LYRICS       - "Four, tres, two, uno

[Will I Am]
...
D to the E, to the L I C I O U S, to the D, to the E, to the, to the, to the, to the, to the....."
TITLE        - "1"
TRACKNUMBER  - "5"
YEAR         - "6000"
-- AUDIO --
bitrate     - 953
sample rate - 44100
channels    - 2
length      - 4:52
```
