### ISSUE TITLE
Taglib doesn't fully support art images?

### ISSUE THREAD

**Issue by gerchicov-bp** [taglib/taglib#666]
I have a flac file and I found only the following way:
http://stackoverflow.com/questions/4752020/how-do-i-use-taglib-to-read-write-coverart-in-different-audio-formats

But it describes the way for id3v2 only. But at least ogg vorbis exists which requires another way other from this one because in this way the tag/file becomes null or returns nulls on function calls.

On the other hand taglib has inner classes which are similar to images but in their own format. How to read/write these data?

**Comment by gerchicov-bp** [comment]
I have found a solution. The problem is ogg vorbis (and other formats) says to create a tag for picture. But in fact it is just a recommendation and so some apps just save the images into an image list with some information but without tags at all

**Comment by gerchicov-bp** [comment]
I still don't understand - I have found how to read pictures but the similar way doesn't work for their writing. Could you give an example how to do it?

There is no appropriate example in tests: they write something like "proxy image" but not real data from UIImage!

**Comment by gogglesguy** [comment]
For inspiration: https://github.com/gogglesmm/gogglesmm/blob/master/src/GMTag.cpp#L1097

**Comment by ufleisch** [comment]
Implemented with #1156.
