### ISSUE TITLE
Adding Images Permanently Increases File Size Even After Removing The Frame

### ISSUE THREAD

**Issue by kwilson7770** [taglib/taglib#67]
I discovered a song corrupting related issue when you add pictures to the ID3 tag. I added a 10 MB picture to a song and saved it. I noticed 10 MB size increase to the song (as expected). I then deleted the picture by setting the Taglib.File.Tag.Pictures to nothing. The file size stayed at 10 MB bigger than it originally was even though it could not find a picture when the program loaded. I thought the picture was still there, but could not be read. So I tried multiple different ID3 readers (even ones that show raw data) and I could not find the picture in this song. 

This means any program that uses this library to add pictures will become permanently bigger. Please help me on this one! I am not sure if it is because of padding or if it is a glitch with your library

**Comment by FestusHagen** [comment]
Got ghosts ... Yesterday there was 19 Issues, Today there are 20, this issue (#67) was not here yesterday and no delete/restore log entries!

This is a non issue ... Removing ID3 frames reduces the file size.

IMO it can be closed ...

-Enjoy

**Comment by TsudaKageyu** [comment]
Right, this should be closed anyway.

**Comment by kwilson7770** [comment]
This isn't because of a ghost. My account was flagged as a bot and everything was hidden... it wasn't until now that I deiced to use this account again and get my account back in order. So that is why it randomly showed up
