### ISSUE TITLE
No self assignment check in operator=

### ISSUE THREAD

**Issue by garima-g** [taglib/taglib#673]
In file taglib/ape/apeitem.cpp : 87 

There is no self-assignment check in method 'operator=' and absence of this check can result unpredictable behaviour. 

Solution: 
Method 'operator=' should check its argument with 'this' pointer. 
  
Same check is required in these source files: 
taglib/mp4/mp4coverart.cpp at #55 
taglib/mp4/mp4item.cpp at #65
taglib/asf/asfattribute.cpp at #73

**Comment by garima-g** [comment]
diff -Naur a/taglib-1.10beta/taglib/ape/apeitem.cpp b/taglib-1.10beta/taglib/ape/apeitem.cpp
--- a/taglib-1.10beta/taglib/ape/apeitem.cpp	2015-11-02 11:04:40.535734239 +0530
+++ b/taglib-1.10beta/taglib/ape/apeitem.cpp	2015-11-03 12:00:46.868923686 +0530
@@ -86,8 +86,11 @@
 
 Item &APE::Item::operator=(const Item &item)
 {
-  delete d;
-  d = new ItemPrivate(*item.d);
+  if(&item != this)
+  {
+   delete d;
+   d = new ItemPrivate(*item.d);
+  }
   return *this;
 }
 
diff -Naur a/taglib-1.10beta/taglib/asf/asfattribute.cpp b/taglib-1.10beta/taglib/asf/asfattribute.cpp
--- a/taglib-1.10beta/taglib/asf/asfattribute.cpp	2015-11-02 11:04:40.531734239 +0530
+++ b/taglib-1.10beta/taglib/asf/asfattribute.cpp	2015-11-03 12:03:46.816918052 +0530
@@ -72,10 +72,13 @@
 
 ASF::Attribute &ASF::Attribute::operator=(const ASF::Attribute &other)
 {
-  if(d->deref())
-    delete d;
-  d = other.d;
-  d->ref();
+  if(&other != this)
+  {
+   if(d->deref())
+     delete d;
+   d = other.d;
+   d->ref();
+  }
   return *this;
 }
 
diff -Naur a/taglib-1.10beta/taglib/mp4/mp4coverart.cpp b/taglib-1.10beta/taglib/mp4/mp4coverart.cpp
--- a/taglib-1.10beta/taglib/mp4/mp4coverart.cpp	2015-11-02 11:04:40.551734238 +0530
+++ b/taglib-1.10beta/taglib/mp4/mp4coverart.cpp	2015-11-03 12:26:58.820874469 +0530
@@ -54,11 +54,13 @@
 MP4::CoverArt &
 MP4::CoverArt::operator=(const CoverArt &item)
 {
-  if(d->deref()) {
-    delete d;
+  if(&item != this)
+  {
+   if(d->deref())
+     delete d;
+   d = item.d;
+   d->ref();
   }
-  d = item.d;
-  d->ref();
   return *this;
 }
 
diff -Naur a/taglib-1.10beta/taglib/mp4/mp4item.cpp b/taglib-1.10beta/taglib/mp4/mp4item.cpp
--- a/taglib-1.10beta/taglib/mp4/mp4item.cpp	2015-11-02 11:04:40.551734238 +0530
+++ b/taglib-1.10beta/taglib/mp4/mp4item.cpp	2015-11-03 12:26:42.296874987 +0530
@@ -64,11 +64,13 @@
 MP4::Item &
 MP4::Item::operator=(const Item &item)
 {
-  if(d->deref()) {
-    delete d;
+  if(&item != this)
+  {
+   if(d->deref())
+     delete d;
+   d = item.d;
+   d->ref();
   }
-  d = item.d;
-  d->ref();
   return *this;
 }

**Comment by garima-g** [comment]
For detail information please check the attached patch file.

![patch1](https://cloud.githubusercontent.com/assets/10647613/10904458/52bc684a-8239-11e5-8c5d-3ffd0052a584.jpg)

![patch2](https://cloud.githubusercontent.com/assets/10647613/10904460/53193f34-8239-11e5-8ee6-6ce7252871d0.jpg)

**Comment by TsudaKageyu** [comment]
Hi @garima-g, Thanks for the catch. I agree with you that we need the self-assignment checks.
I can make changes like you have suggested on my side, or will you do it on your side and create a pull request?

**Comment by garima-g** [comment]
Created pull request #675
