### ISSUE TITLE
Not reachable statement in bindings/c/tag_c.cpp

### ISSUE THREAD

**Issue by g-coder** [taglib/taglib#674]
In bindings/c/tag_c.cpp :98
statement 'return 0' is unreachable.
This statement can be removed.

Reason:
In function taglib_file_new_type(), all cases in switch block have return statements.

**Comment by garima-g** [comment]
![patch](https://cloud.githubusercontent.com/assets/10647613/10935189/5a616510-830a-11e5-9e15-997e5107b941.jpg)

I can create pull request also.

**Comment by TsudaKageyu** [comment]
I removed it. Thanks!
