### ISSUE TITLE
Can't install Taglib# using NuGet.

### ISSUE THREAD

**Issue by TheNiels1997** [taglib/taglib#677]
Today i tried to install TagLib# using the Package Manager Console but it didn't work, instead of installing i got this error:

Install-Package : Unable to find package 'taglib'
At line:1 char:1
+ Install-Package
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Is this fixable or does this have to be fixed?

**Comment by scotchi** [comment]
Hi, sorry, this is the wrong project:  TagLib (C++, this project) is different from TagLib# (C#)

**Comment by TheNiels1997** [comment]
I apologize, i thought that this was the correct page :3
