### ISSUE TITLE
taglib fails to build: call of overloaded ‘endian_reverse(TagLib::ulonglong&)’ is ambiguous

### ISSUE THREAD

**Issue by cmacq2** [taglib/taglib#678]
Building taglib as part of a kdesrc-build update fails today with this error message:

> error: call of overloaded ‘endian_reverse(TagLib::ulonglong&)’ is ambiguous

```
<snip>taglib/taglib/toolkit/tutils.h: In function ‘TagLib::ulonglong TagLib::Utils::byteSwap(TagLib::ulonglong)’:
<snip>taglib/taglib/toolkit/tutils.h:141:45: error: call of overloaded ‘endian_reverse(TagLib::ulonglong&)’ is ambiguous
       return boost::endian::endian_reverse(x);
                                             ^
```

This can probably be hacked around by casting to (uint64_t) but this problem may need more careful evaluation. Related: for some reason the if-deffery prefers boost templates to compiler built-ins, or indeed typical C library calls, c.f.:http://www.yolinux.com/TUTORIALS/Endian-Byte-Order.html#LIBRARIES

Compiler used by the kdesrc-build frontend is GCC 5: gcc --version
gcc (Debian 5.2.1-23) 5.2.1 20151028
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by TsudaKageyu** [comment]
Thanks! I will check it today.

**Comment by TsudaKageyu** [comment]
Fixed it. And confirmed that it work fine on either x86/x86_64 Linux box or 64-bit PowerPC emulator too.
