### ISSUE TITLE
Include static lib into Xcode project

### ISSUE THREAD

**Issue by chrs1885** [taglib/taglib#679]
Hi everyone,

I've managed to build the static lib for both archs. However after linking the static lib and adding the appropriate header search paths, I'm not able to even run the project. Building my Objective-C project gives me `string file not found` for taglib.h. Are there any compiler flags missing in order to get it work properly?

Thanks in advance.

**Comment by chrs1885** [comment]
OK, defining the header files as C++ rather than default C headers did the trick.

**Comment by chrs1885** [comment]
I get this error for importing `taglib.h` in my Objective C class.

**Comment by sbooth** [comment]
Since TagLib is written in C++ you'll need to use Objective-C++.  If your Obj-C++ header files `#include` any C++ headers they will be unusable from other plain Obj-C files.
