### ISSUE TITLE
Possible ambiguity errors on integer types

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#692]
In some environments, C/C++ standard header defines ```ushort```, ```uint``` and ```ulong``` types. Any TagLib public headers can be used with the standard headers, and they may conflict with the integer types defined in ```taglib.h```. I'd like to fix it, and we have some ways to do it.

* Add ```TagLib::``` to all such types.
* Replace such types with standard types (and keep the types in ```taglib.h``` for compatibility).

Privately, I prefer the second option, since the standard types will work fine with all C++ programmers. Currently, those types are used mixedly. For example, ```String::operator[]()``` returns ```TagLib::wchar```, but other functions take ```wchar_t``` and so forth. Changing ```TagLib::wchar``` to standard ```wchar_t``` won't break the ABI, and other types are the same things.

I'd like to ask some people's opinions.

**Comment by lalinsky** [comment]
I'd very much prefer to get rid of the custom types. We can keep the types defined for backward compatibility, but if it's possible to change the source code without breaking the ABI, let's use the standard types.

**Comment by TsudaKageyu** [comment]
I have done it. Thanks.
