### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by sbooth** [taglib/taglib#693]
TagLib is available under LGPL 2.1 or MPL 1.1.  I know that MPL 2.0 allows static linking for closed-source/proprietary apps, but I couldn't find anything stating whether this was permissible under MPL 1.1  Obviously LGPL does not permit static linking except in open source projects.  What is the position of @scotchi as the original author of TagLib- is static linking of TagLib allowed in closed source projects? Legalese aside, I'd like to respect the intent of the authors.

**Comment by scotchi** [comment]
We moved to using dual LGPL / MPL (originally TagLib was LGPL only) specifically to allow static linking from closed-source applications as long as the changes were contributed back.

**Comment by sbooth** [comment]
Awesome, thanks.
