### ISSUE TITLE
Bad allocation on mp3 file load

### ISSUE THREAD

**Issue by Razzeee** [taglib/taglib#697]
We bumped Kodi to taglib 1.10 and it seems, like we found a regression.

When we try to access this file: http://saraev.ca/01%20-%20Eternity.mp3
via 
```
file = mpegFile = new MPEG::File(stream, ID3v2::FrameFactory::instance());
```
it fails with a ```bad allocation```
If you need any more info, please let me know.

![image](https://cloud.githubusercontent.com/assets/5943908/11639466/5c251bac-9d2d-11e5-8e34-029d2a98f1dd.png)

**Comment by TsudaKageyu** [comment]
Hi @Razzeee, I have located the cause of this issue.
I will create a pull request soon, and describe the cause there.
Thanks!

**Comment by Razzeee** [comment]
Do you guys do hotfix releases for such things or should we just patch our version of 1.10 when this hits master?

**Comment by silverhammermba** [comment]
Ah, you beat me! I found the same crash on Linux. Downgrading taglib to 1.9.1 got Kodi working agian.

**Comment by Razzeee** [comment]
So will there be a hotfix or should be cherry pick the PR?
