### ISSUE TITLE
Saving MP3 tag on Windows XP results in AccessViolation

### ISSUE THREAD

**Issue by radioboss** [taglib/taglib#700]
Saving MP3 tag under Windows XP (SP3) results in a crash. The issue does not happen under newer OS'es, or at least it's not visible.

The MP3 file to reproduce the issue: http://dl.djsoft.net/beta/test.zip

Error message: Access violation at address 026E6BD8, read of address 00000008.

Looks like a null pointer access to me.

**Comment by FestusHagen** [comment]
Unable to reproduce ... More info needed!

Please build the examples and test with them.

Thank you
-Enjoy

**Comment by radioboss** [comment]
I'll try to give more information on the issue soon. C++ is not my primary expertise, and Visual Studio remote debugging is not available under Windows XP - it will take some time to extract call stacks and other info about this. Just tried with the latest commits and the issue is still there...

**Comment by radioboss** [comment]
Recompiling it with VS 2012 somehow "fixed" the issue. When it was compiled with the latest VS 2015, it didn't work correctly. The issue can be closed.

**Comment by FestusHagen** [comment]
Thank you!

-Enjoy
