### ISSUE TITLE
support for static build with MXE Crosscompiler Environment?

### ISSUE THREAD

**Issue by selli69** [taglib/taglib#708]
Hi there!

First of all: Thanks for the good work!

My Problem: I want to "update" the support for taglib in the MXE Crosscompiler Environment (mxe.cc). There is already ver 1.7.2 supported (mxe takes sources from http://developer.kde.org/~wheeler/files/src/ , latest sources there: 1.7.2), but my project uses 1.10. Now i tried to make changes to the mxe configfiles and stumbled over a patch on CMakeLists.txt:

```
This file is part of MXE.
See index.html for further information.

This patch has been taken from:
https://bugs.kde.org/show_bug.cgi?id=268441

diff --git a/bindings/c/CMakeLists.txt b/bindings/c/CMakeLists.txt
index 79c7a6b..fa4056d 100644
--- a/bindings/c/CMakeLists.txt
+++ b/bindings/c/CMakeLists.txt
@@ -19,9 +19,11 @@ INCLUDE_DIRECTORIES( ${CMAKE_CURRENT_SOURCE_DIR}/../../taglib
 configure_file(${CMAKE_CURRENT_SOURCE_DIR}/taglib_c.pc.cmake ${CMAKE_CURRENT_BINARY_DIR}/taglib_c.pc )
 ########### next target ###############
 
-ADD_LIBRARY(tag_c SHARED tag_c.cpp)
 if(ENABLE_STATIC)
+    add_library(tag_c STATIC tag_c.cpp)
     set_target_properties(tag_c PROPERTIES COMPILE_DEFINITIONS TAGLIB_STATIC)
+else(ENABLE_STATIC)
+    add_library(tag_c SHARED tag_c.cpp)
 endif(ENABLE_STATIC)
 
 TARGET_LINK_LIBRARIES(tag_c  tag )
```
This patch maybe have to do with the static binding. Now i have read, that the ENABLE STATIC is completely removed and I have no clue what has to be done that:

1. static binding is possible,
2. taglib is availiable in MXE in ver 1.10

Sorry, my programming skills are not far enough to solve that problem by myself.

Hope you can help!

Thanks in advance.!

**Comment by FestusHagen** [comment]
The ENABLE_STATIC option has been replaced with the BUILD_SHARED_LIBS option.

`-DENABLE_STATIC=ON` becomes`-DBUILD_SHARED_LIBS=OFF` to build a static library.

However as of TagLib v1.10 a static library is built by default, previously a shared library was the default.

-Enjoy

**Comment by selli69** [comment]
Thanks Festus!

i'll give my efforts to integrate 1.10 in MXE another try! ;)

**Comment by selli69** [comment]
Hi again,

I removed the ENABLE_STATIC in the MXE build reciepe, now taglib compiles fine. But when i crosscompile my project i get linker errors like this:

```
./release/tagprocessortaglib.o:tagprocessortaglib.cpp:(.text+0x84): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
./release/tagprocessortaglib.o:tagprocessortaglib.cpp:(.text+0x197): undefined reference to `_imp___ZN6TagLib7FileRefC1Ev'
./release/tagprocessortaglib.o:tagprocessortaglib.cpp:(.text+0x238): undefined reference to `_imp___ZN6TagLib8FileNameC1EPKc'
......... (some more of that) .....
```

after a sight of the link in the patch in my original post

https://bugs.kde.org/show_bug.cgi?id=268441

mabrand wrote there:

```
Support for ENABLE_STATIC didn't seem to be completely implemented for the C bindings.
The attached patch seems to help.
Used in mingw-cross-env.
```

The mentioned mingw-cross-env is MXE i use. Is it possible that the (now) missing lines

```
add_library(tag_c STATIC tag_c.cpp)
set_target_properties(tag_c PROPERTIES COMPILE_DEFINITIONS TAGLIB_STATIC)

and

add_library(tag_c SHARED tag_c.cpp)
```

cause my errors? if so, it would be nice, these lines were added again in CMakeList.txt

Thanks in advance!

**Comment by FestusHagen** [comment]
Are you using `-DBUILD_BINDINGS=ON ` in your cmake command?

In the build `$(PKG)_BUILD` section of MXE's taglib.mk if you are updating that ...

-Enjoy

**Comment by selli69** [comment]
Hi Festus,

thanks for the quick answer. I tried using -DBUILD_BINDINGS=ON and -DBUILD_SHARED_LIBS=OFF
in the $(PKG)_BUILD section of MXE .md file. Seems compiled correctlay and installed the libs in the according mxe subdirs.

My project wont compile anyway.. :( Same linker errors. The problem is probably in my project configuration in .pro Qt Project file. Taglib is added with:

```
CONFIG += link_pkgconfig
PKGCONFIG += taglib
```

Think the problem is there... Anyway, thanks for the help!

**Comment by FestusHagen** [comment]
Right or wrong I do not know, I add TagLib to my Qt projects by adding a line something like
`LIBS += -L"/home/fh/taglib" -ltag -lz`.

-Enjoy

**Comment by selli69** [comment]
I assume that you cmake taglib with 

     -DCMAKE_INSTALL_PREFIX=/home/fh/taglib

I think native linux compilation works this way, same with my pkg-config approach (as mentioned in the taglib doc).

Problems only occour with crosscompilation.. I'll try further and publish results here, maybe somebody has the samme issue..

**Comment by FestusHagen** [comment]
You assume correct ... `/home/fh/taglib` is where TagLib is installed in this example.

I do not know what linux does ...

-Enjoy

**Comment by selli69** [comment]
> I do not know what linux does ...

I assumed you are using linux as your native environment. ;) Anyway..

Ive tried now the master branch, the v1.10 and anything else i could imagine, but crosscompile wont work :( As far as i can see everything  seems alright, Taglib is included in the linker run:

 ```
i686-w64-mingw32.static-g++ -Wl,-s -Wl,-subsystem,windows -mthreads -o release/untitled.exe object_script.untitled.Release  -lglu32 -lmingw32 -L/home/hal/projects/mxe/usr/i686-w64-mingw32.static/qt5/lib -lqtmain -L/home/hal/projects/mxe/usr/i686-w64-mingw32.static/lib -ltag_c -ltag -lQt5Widgets -L/home/hal/projects/mxe/usr/i686-w64-mingw32.static/lib/../lib -L/home/hal/projects/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms -lqwindows -lwinspool -lQt5PlatformSupport -lQt5DBus -ldbus-1 -liphlpapi -lnetapi32 -L/home/hal/projects/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats -lqdds -lqicns -lqico -lqjp2 -lqmng -lmng -llcms2 -lm -lqtga -lqtiff -ltiff -llzma -lqwbmp -lqwebp -lQt5Gui -lcomdlg32 -loleaut32 -limm32 -lopengl32 -ljpeg -lharfbuzz -lcairo -lgobject-2.0 -lfontconfig -lusp10 -lmsimg32 -lgdi32 -lpixman-1 -lffi -lexpat -lfreetype -lbz2 -lpng16 -lharfbuzz_too -lglib-2.0 -lwinmm -lshlwapi -lpcre -lintl -liconv -lpng -lQt5Core -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -lz -lpcre16
```
for today i resign... :(  Maybe one of the other devs reads this and is able to give a hint. Thank you Festus for your efforts anyway...

**Comment by FestusHagen** [comment]
OS Environment is irrelevant.

I do believe there is some confusion happening here, Your project appears to be C++, thus the C bindings are not needed. (`-ltag_c` and can even use `-DBUILD_BINDINGS=OFF`).

The `undefined reference to` errors indicate that TAGLIB_STATIC is not defined in your project ...

-Enjoy

**Comment by selli69** [comment]
the c bindings are not necessary, thats right.

dont call me a fool... where in my project i have to make this TAGLIB_STATIC definition? Sry for my unawareness..

**Comment by FestusHagen** [comment]
There is no way I'm going to call you a fool and give up my status of being the only fool here!

Just add something like `DEFINES += TAGLIB_STATIC` to your projects .pro.

-Enjoy

**Comment by selli69** [comment]
;)

like said, a #define TAGLIB_STATIC in my header file did the job.
But i think the definition in the .pro file is the better place, as this is a central place. Thanks for the hint!

> -Enjoy

Oh, yeah! now i enjoy!!! 

Ah.. btw: I'll send my updated taglib.mk file to the MXE maintainers. So taglib-1.10 will be availiable in the MXE master trunk soon.

**Comment by FestusHagen** [comment]
Awesome!

I use the following technique in my .pro
`CONFIG(static, static|shared):DEFINES += TAGLIB_STATIC`

Please close this issue it it is resolved ...

-Enjoy

**Comment by FestusHagen** [comment]
Thank you.
