### ISSUE TITLE
MPEG APE Tag deleting itself after saving twice

### ISSUE THREAD

**Issue by amethystAnt** [taglib/taglib#709]
I think I found a bug. When I try to edit and save an APE tag in a MPEG file, everything is OK. But When I edit it, save it, then edit it and save it again, something goes wrong, the APE tag is then completely deleted from the file as well as the ID3v1 tag, if there was one. You have to open the file using another object in order to notice it. Don't worry, I used multiple types of software to prove this.
Try this little program (edit it to suit your needs):
```
   #include <taglib/mpegfile.h>
   #include <taglib/apetag.h>
   #include <taglib/id3v1tag.h>
   #include <stdio.h>
   int main() {
           TagLib::MPEG::File* f = new TagLib::MPEG::File ("/home/karel/Megadeth---Trust.mp3");
           TagLib::APE::Tag *tag = f->APETag(true);
           tag->setArtist("Megadeath");
           f->save();
           tag->setArtist("Megadeth");
           f->save();
           TagLib::MPEG::File *f1 = new TagLib::MPEG::File ("/home/karel/Megadeth---Trust.mp3");
           tag = f1->APETag(true);
           printf ("%s\n", tag->artist().toCString());
           delete f;
           return 0;
   }
```
The result is, it doesn't print anything. Run it again and it prints what it's supposed to print. Then again and it prints nothing. This is probably because this bug happens only when the APE tag was in the file before we opened it. Of course I did not found the bug using this program, I wrote it to test it.

**Comment by TsudaKageyu** [comment]
That is one of the several bug we fixed in #684. Our up-to-date code should work fine.
