### ISSUE TITLE
TagLib::RIFF::AIFF::File::hasID3V2Tag() missing

### ISSUE THREAD

**Issue by michihenning** [taglib/taglib#712]
`TagLib::RIFF::AIFF::File::hasID3V2Tag()` appears to be missing from the library (1.9.1):

```
TagLib::RIFF::AIFF::File const* file = dynamic_cast<TagLib::RIFF::AIFF::File const*>(fileref_.file());
if (file->hasID3v2Tag())
{
    // ...
}
```
```
undefined reference to `TagLib::RIFF::AIFF::File::hasID3v2Tag() const'
```

Note that the equivalent code links fine for `TagLib::RIFF::WAV::File`.

Looks like someone forgot to define/export that function?

**Comment by TsudaKageyu** [comment]
It used to be missing, we implemented it since v
1.10, and the test code is working fine with the function.

**Comment by michihenning** [comment]
Thanks for letting me know!
