### ISSUE TITLE
Is this problem related to here?

### ISSUE THREAD

**Issue by Stamimail** [taglib/taglib#714]
https://trac.videolan.org/vlc/ticket/9935

**Comment by scotchi** [comment]
As noted there, this is in relation to an incorrectly encoded file.  TagLib has a mechanism for working around those (using the Latin1StringHander), but apparently VLC isn't using that.  (Which is not a bug in their system; again, the fundamental problem here is that the file is broken.)

**Comment by Stamimail** [comment]
Thank you for your answer.
Please, can you tell me if there is a software or an utility to fix such incorrectly encoded files?
