### ISSUE TITLE
Wrong text encoding in the id3v2.3 format

### ISSUE THREAD

**Issue by CyberSinh** [taglib/taglib#717]
Hi,

According to the id3v2.4 specifications (http://id3.org/id3v2.4.0-structure), “frames that allow different types of text encoding contains a text encoding description byte. Possible encodings:
•	$00   ISO-8859-1 [ISO-8859-1]. Terminated with $00.
•	$01   UTF-16 [UTF-16] encoded Unicode [UNICODE] with BOM. All strings in the same frame SHALL have the same byteorder. Terminated with $00 00.
•	$02   UTF-16BE [UTF-16] encoded Unicode [UNICODE] without BOM. Terminated with $00 00.
•	$03   UTF-8 [UTF-8] encoded Unicode [UNICODE]. Terminated with $00.”

According to the id3v2.3 specifications (http://id3.org/id3v2.3.0), “frames that allow different types of text encoding have a text encoding description byte directly after the frame size. If ISO-8859-1 is used this byte should be $00, if Unicode is used it should be $01.” So, there is no UTF-8 option in the id3v2.3 format.

The issue with taglib is that the Frame::createTextualFrame method implemented in the id3v2frame.cpp file always uses UTF8 encoding. And the encoding doesn’t seem to be changed if the MP3 is saved according to the id3v2.3 format.

This non-compliance with standards leads to compatibility issues for reading tags written with taglib. For example, the lyrics frame is ignored by many softwares or devices. 

I hope a solution could be found for that issue.

Thank you very much for your help.

Best regards,

Cyber Sinh

**Comment by TsudaKageyu** [comment]
I couldn't reproduce it. Can you provide us some sample code to reproduce it?

I wrote a short program like this:
```
MPEG::File file("taglib-test.mp3");
file.ID3v2Tag(true)->setArtist(L"日本語アーティスト");
file.save(MPEG::File::ID3v2, true, 3);
```
and the output was UTF-16.
![utf-16](https://cloud.githubusercontent.com/assets/2161941/13033330/a38e34ce-d356-11e5-84fc-f1bf9624dede.png)

**Comment by CyberSinh** [comment]
Hi Tsuda,

1. Add a "LYRICS" tag in a PropertyMap.
2. Pass the PropertyMap to the ID3v2 setProperties method.
3. Save the MP3 in the v2.3 format.

**Comment by TsudaKageyu** [comment]
You are right @CyberSinh, I could reproduce it and locate the cause.

According to the history of the repository, we tried to fix the same bug at this commit: https://github.com/taglib/taglib/commit/061b381ea835edd14c8a2e86cf26c97dba00f68f 
It looks like he overlooked 'USLT' frame at that time.

I will fix it soon. Thanks for your good catch!

**Comment by TsudaKageyu** [comment]
Fixed. Thank you so much again!
