### ISSUE TITLE
ByteVector::replace is O(n!)

### ISSUE THREAD

**Issue by fcartegnie** [taglib/taglib#718]
ByteVector::replace is doing in the worst case O(n!) memcpy.

This is a big issue with ID3V2 tags when synch code is in use and content is really large.

Neverending decoding with 50MB cover :/
Conversion only on tag use, is also probably a better way.

**Comment by TsudaKageyu** [comment]
You are right, @fcartegnie. I admit that my implementation is poor, or even broken.
I will replace it with an O(n) algorithm.

**Comment by fcartegnie** [comment]
As the private data is replaced each time, that even like ~O(n²)

The sync conversion should probably also be done in an optimized, non generic, method.
(that would avoid duplicating the array prior decoding)

**Comment by TsudaKageyu** [comment]
Your point makes sense. Currently, TagLib always copies an entire array when decoding an unsynchronized ID3v2 frame and we can avoid it.

Well, can I ask you a favor? Could you provide me with your file that takes a long time to decode? It will help me a lot.

**Comment by fcartegnie** [comment]
File is available there.
https://trac.videolan.org/vlc/ticket/16623
You'll need to rename it to mpeg/mp3 extension to have it parsed.
(as I use an extension to map/parse aac)

**Comment by fcartegnie** [comment]
The ultimate performance fix would be conversion on Tag use only, but that would require far more changes to the lib, than fixing ByteVector//ID3V2Tag

**Comment by TsudaKageyu** [comment]
I agree with you that we should have a special method to decode synchronized ID3v2 frames.
Anyway, I will try find the best way to decode your file in reasonable time.

**Comment by TsudaKageyu** [comment]
I have written a quick and dirty optimization for `SynchData::decode()`.
Now it can decode your file in around 0.4 seconds. I will refactor the code and commit it soon.

Thanks again.

**Comment by fcartegnie** [comment]
please mention target release (1.11 ?) with that commit to enable parsing those files

**Comment by lalinsky** [comment]
We actually used to have a optimized version of `SynchData::decode()` until @scotchi removed it. :)

https://github.com/taglib/taglib/commit/2644c529a57375072cdb0397d4dac6bc9eb7e2bc

**Comment by TsudaKageyu** [comment]
Hmm, it's almost the same method as I wrote. 
Anyway, I think that it's worth it to do it again since it makes a great difference.

**Comment by TsudaKageyu** [comment]
`ByteVector::replace` is still O(n!), but actually it's not used in TagLib now.
So I'd like to avoid touching it in this "beta period", and will refactor it after we release the next stable version.
