### ISSUE TITLE
Version OGG field mismatch

### ISSUE THREAD

**Issue by davidgfnet** [taglib/taglib#720]
Hello!

I'm running a custom program that scans OGG properties or fields and prints them. In my computer, which ships taglib 1.9 (Fedora) I get 29 properties (vorbis_tag->fieldListMap().size()) whereas in another machine that runs taglib 1.11 I get 28, the missing one being our beloved METADATA_BLOCK_PICTURE.

Any ideas? As a hint I might add that the machine missing one property is an ARM based device.

Thanks!

**Comment by TsudaKageyu** [comment]
Hi @davidgfnet, sorry the for inconvenience.

`XiphComment` now handles `METADATA_BLOCK_PICTURE` separately from other fields. Please try `XiphComment::pictureList()`.

**Comment by davidgfnet** [comment]
Is that a change in the API? What version is the first one to change this?
Thanks!!

**Comment by TsudaKageyu** [comment]
The new API has been introduced since v1.11 BETA.
It is designed to enable us to get/set pictures handily without decoding/encoding base64 texts.

**Comment by davidgfnet** [comment]
Thanks!
