### ISSUE TITLE
TagLib 2 release plan

### ISSUE THREAD

**Issue by sbooth** [taglib/taglib#721]
The taglib2 branch has been around for quite a while but development on the 1.0 branch continues.  Is there a timeline to cease development on the 1.0 branch (except perhaps for crashing bugs) and finally make the breaking ABI changes and transition taglib2 to master?

**Comment by TsudaKageyu** [comment]
Privately, I think that we need to list the pending issues on taglib2 branch first. 
For example, `ID3v2::FrameFactory` is not usable for some reasons, `EBML` support is incomplete, duplicate overloads, and so forth...

**Comment by sbooth** [comment]
I've lost track of the differences between the two branches.  I've been using taglib2 for quite a while and don't pay as much attention to master as I should.

I suppose the best way to list the issues is to open them here with a taglib2 label?

**Comment by CyberSinh** [comment]
Any news about the taglib2 roadmap?

**Comment by sbooth** [comment]
Would a project be more appropriate to keep track of the items for 2.0?

**Comment by tattwamasi** [comment]
Is taglib2 stable… ish? I've used taglib for a while, but don't mind a little work to update any breaking API/ABI changes.  But if it's still too early or if it looks like the plans for the branch are changing / stale, I'd hold off.

**Comment by sbooth** [comment]
I would say that taglib2 is more or less stable.  I'm sure there are some corner cases that haven't been as thoroughly tested as in 1.x. but @TsudaKageyu has done a great job keeping the branches roughly in sync.  If it were completely up to me I'd freeze 1.x for bug fixes only and recommend all users upgrade to 2.0.

**Comment by FestusHagen** [comment]
I totally agree with @sbooth, I personally only test the 1.x branch, however use the 2.x branch exclusively.

Just keep in mind that the 2.x branch API could change.

And because it needs to be said ... Thanks @TsudaKageyu!

-Enjoy
fh : )_~
