### ISSUE TITLE
Next beta release of v1.11

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#722]
We released v1.11 BETA on Jan 30, and we have fixed several bugs since then.
I think we'd better to have some more beta period to make sure if it works, however, at the same time, I'd like to offer users the current version to try.
So I'm thinking about releasing the next beta version (v1.11 BETA 2), for example, at the beginning of March.

Any thoughts?

**Comment by CyberSinh** [comment]
Hi Tsuda,

I agree. 
The issue #717 is a very annoying bug and a new release would be very useful.

To my mind, the sooner the better.

Thanks.

**Comment by TsudaKageyu** [comment]
I will release v1.11 BETA 2 in a few days.
