### ISSUE TITLE
Global size in RIFF files is not updated when stripping tags

### ISSUE THREAD

**Issue by ufleisch** [taglib/taglib#724]
When removing tags (ID3v2 or INFO) from a WAV file, the global size (bytes 4..8 in the file, just after the "RIFF" FourCC) is not reduced. When such a file is opened with RIFFPad, it is reported as corrupt.

**Comment by TsudaKageyu** [comment]
Right. It's definitely a bug that we should fix immediately.
Thank you for your report.

**Comment by TsudaKageyu** [comment]
Fixed at the commit: 520da50bc52bd6cecff5e9c4840682809bd591b6
