### ISSUE TITLE
Some ID3 text frames are not readable by taglib

### ISSUE THREAD

**Issue by MordredKLB** [taglib/taglib#728]
I found an album that had certain text frames which can't be read by taglib. Here's a(n unfortunately large) [test file](https://dl.dropboxusercontent.com/u/23987869/Various%20Artists%20-%2008%20-%20Road%20Racin%27%20%5BBad%20Tags%5D.mp3) with a Album and Title frames that can't be read.

Unfortunately, this file was originally tagged about 3.5 years ago, and I'm not 100% sure which one. My guess is they were originally tagged using a tagger I wrote using id3lib, although it might have been fb2k. They can still be read correctly by id3lib, foobar2000 and mp3tag. Taglib and AudioShell can't read the tags. AudioShell sees them as Chinese(?) and Taglib returns blank strings of what appears to be actual_length - 1.

![AudioShell View](http://i.imgur.com/hUJLyUn.png)

![Taglib](http://i.imgur.com/N3c5X27.png)

Rewriting the files using id3lib fixes the issue, as does changing the fields in mp3tag. Sometimes updating the tags in foobar causes the frames to be readable by taglib, but not always.

**Comment by TsudaKageyu** [comment]
The ID3v2 tag of the file has **Unsynchronisation** flag, but the actual frames are not unsynced.
According to the spec (http://id3.org/id3v2.3.0#sec5):
> all the $FF 00 combinations have to be replaced with the $FF 00 00 combination during the unsynchronisation

However, the `TIT2` and `TALB` frames of the tag are not compliant to that.
![sync](https://cloud.githubusercontent.com/assets/2161941/13606238/a37e2526-e58e-11e5-8066-b8c3aefeb359.png)

**Comment by MordredKLB** [comment]
Okay, I'm remembering now that I discovered some issues with id3lib not working properly with the Unsynchronisation flag (it could have been my implementation), and I was forced to turn it off. I think it was miscalculating frame sizes which would make sense with it not replacing $FF 00 properly. 

Should I assume that foobar2k, and mp3tag are just ignoring the unsync flag, or possibly checking to see if $FF 00 00 doesn't exist?

**Comment by TsudaKageyu** [comment]
Can they read properly unsynced UTF-16 frames?

**Comment by MordredKLB** [comment]
I don't know how to create a test tag to even try that out. My id3tag implementation was written in a non-unicode environment.

**Comment by TsudaKageyu** [comment]
I don't know how either of them works. Anyway, this is not a bug of TagLib, and I don't think we have to devise a workaround for this issue.
It's an exceptional case that UTF-16 strings are stored in big-endian format (it's much more likely to have `$FF $00` patterns than little-endian, and AFAIK little-endian is widely used) and the unsynchronisation flag was set by mistake.

**Comment by scotchi** [comment]
I agree that it's not worth handling in TagLib.  In general, unless invalid tags are caused by some widely used application (e.g. iTunes) I think ignoring is a fine policy.

**Comment by MordredKLB** [comment]
I'm totally cool with that. Closing.
