### ISSUE TITLE
Synchronized lyrics frames are not read if the description is empty

### ISSUE THREAD

**Issue by ufleisch** [taglib/taglib#729]
If the description is empty, the synchronized lyrics are not read. This can be reproduced by writing a synchronized lyrics frame with an empty description and then reading it back. The `synchedText()` will be empty.

This bug was introduced in commit c4fe6578 

```
--- a/taglib/mpeg/id3v2/frames/synchronizedlyricsframe.cpp
+++ b/taglib/mpeg/id3v2/frames/synchronizedlyricsframe.cpp
@@ -159,7 +159,7 @@ void SynchronizedLyricsFrame::parseFields(const ByteVector &data)
   int pos = 6;
 
   d->description = readStringField(data, d->textEncoding, &pos);
-  if(d->description.isNull())
+  if(d->description.isEmpty())
     return;
```

The `isNull()` check was meant to stop parsing when the frame is invalid. Now it stops whenever the description is empty.

**Comment by ufleisch** [comment]
If `readStringField()` succeeds, `pos` is larger than before the call, so a possible fix could be:
```
   int pos = 6;

   d->description = readStringField(data, d->textEncoding, &pos);
-  if(d->description.isEmpty())
+  if(pos == 6)
     return;
```

**Comment by TsudaKageyu** [comment]
Thanks for the catch, @ufleisch. I will fix it and add a unit test.

**Comment by TsudaKageyu** [comment]
Fixed.
