### ISSUE TITLE
Odd error on Windows XP when used from a DLL

### ISSUE THREAD

**Issue by radioboss** [taglib/taglib#738]
**Test environment**
- A "tl.dll" that uses taglib and exports a function (the function reads tag info form a file using TagLib::FileRef)
- A "ConsoleApplication1.exe" program that calls that function from a DLL.
- Both DLL and EXE are compiled using Visual Studio 2015, static debug build (/MTd) (crashes on release build too)

Access Violation occurs when this is launched on Windows XP SP3 (not sure if other XP's are affected). Works fine on later Windows OSes.

**Details on the error**
The information is extracted from the crash dump file.

Error message:
```
Unhandled exception thrown: read access violation.
__guard_check_icall_fptr was 0x1110112.
```

Call stack:
```
	tl.dll!TagLib::ID3v2::FrameFactory::instance() Line 111	C++
 	tl.dll!`anonymous namespace'::createInternal<TagLib::FileName>(TagLib::FileName arg, bool readAudioProperties, TagLib::AudioProperties::ReadStyle audioPropertiesStyle) Line 139	C++
 	tl.dll!TagLib::FileRef::FileRef(TagLib::FileName fileName, bool readAudioProperties, TagLib::AudioProperties::ReadStyle audioPropertiesStyle) Line 211	C++
 	tl.dll!ReadTagTest3() Line 12	C++
 	ConsoleApplication1.exe!main() Line 24	C++
```

Source codes of those test applications:
DLL:
```
#define EXPORT extern "C" __declspec(dllexport)

using namespace TagLib;

EXPORT void ReadTagTest3()
{
	FileRef *f = new FileRef(L"1.mp3", false); //<------- LINE 12 FROM CALL STACK
	if (f)
	{
		MessageBox(0, L"tag loaded", L"All good.", MB_OK | MB_ICONINFORMATION);
		Tag *T = f->tag();
		if (T)
			MessageBox(0, T->artist().toCWString(), L"artist info", MB_OK | MB_ICONINFORMATION);
	}
	return;
}
```

EXE:
```
int main()
{
	MessageBox(0, L"Reading using DLL", L"2", MB_OK | MB_ICONINFORMATION);
	HMODULE dll = LoadLibrary(L"tl.dll");
	TestType TestPtr = NULL;
	TestPtr = (TestType)GetProcAddress(dll, "ReadTagTest3");
	TestPtr(); //<------- LINE 24 FROM CALL STACK

    return 0;
}
```

The crash only occurs when current source code is used and does not happen on current TagLib release (1.10).

Please let me know if more information is needed on this.

**Comment by radioboss** [comment]
Investigating this further, I think that crash is caused by this commit: https://github.com/taglib/taglib/commit/25ffbcb4b9b04326edd1d25a785b686951a0f235 

Reverting the change made there, the problem disappears.

**Comment by TsudaKageyu** [comment]
Hi @radioboss,

Thanks for your report. I have reverted the commit you pointed out. Could you try that?

**Comment by radioboss** [comment]
Yes, it works. I suppose the problem was that "static" was used inside a function?

**Comment by TsudaKageyu** [comment]
I'm not sure what is the true cause. It's weird.
