### ISSUE TITLE
A table of contents frame with more than 127 children will crash (loop forever)

### ISSUE THREAD

**Issue by thomasthiriez** [taglib/taglib#742]
When a table of contents frame is parsed, when the entryCount is read, if there are more than 127 entries, a negative value is converted to a huge unsigned int, and taglib loops almost forever.

This can be fixed by declaring entryCount as an unsigned char instead of an unsigned int on this line:

https://github.com/taglib/taglib/blob/master/taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp#L277

Here is a sample file that will crash taglib:

http://twistedwave.com/taglib_crash.mp3

**Comment by TsudaKageyu** [comment]
Thanks for your report. I confirmed that. I'm going to fix it soon.

**Comment by TsudaKageyu** [comment]
Fixed.
