### ISSUE TITLE
Taglib Crashes on OSX El Capitan 10.11.5 w/ pytaglib

### ISSUE THREAD

**Issue by rmurph20** [taglib/taglib#744]
OS: OSX El Capitan 10.11.5
taglib: 1.11
pytaglib: 1.20
Python: 3.5.1

The install of taglib/pytaglib is fine, I can import the library without issue...

$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release .
$ make
$ sudo make install
$ sudo pip3 install pytaglib
$ python3

> > > import taglib

However, once I try to load a file, I get an immediate crash and "Segmentation Fault: 11"

> > f = taglib.File("/Users/me/Documents/audiofile.mp3")
> > Segmentation Fault: 11

Crash Report:
Process:               Python [2454]
Path:                  /Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.5.1 (3.5.1)
Code Type:             X86-64 (Native)
Parent Process:        bash [415]
Responsible:           Terminal [412]
User ID:               501

Date/Time:             2016-06-04 02:41:40.648 -0400
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11

Time Awake Since Boot: 2100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libtag.1.dylib                  0x000000010130d84b TagLib::ListTagLib::String::~List() + 91
1   libtag.1.dylib                  0x000000010130d365 TagLib::StringList::~StringList() + 21
2   libtag.1.dylib                  0x000000010130cfc5 TagLib::StringList::~StringList() + 21
3   libtag.1.dylib                  0x000000010131e866 TagLib::PropertyMap::~PropertyMap() + 38
4   libtag.1.dylib                  0x000000010131e8c5 TagLib::PropertyMap::~PropertyMap() + 21
5   taglib.cpython-35m-darwin.so    0x00000001003ece14 **pyx_f_6taglib_4File_readProperties(__pyx_obj_6taglib_File*) + 292
6   taglib.cpython-35m-darwin.so    0x00000001003ee9eb __pyx_pw_6taglib_4File_3__init**(_object_, _object_, _object*) + 235
7   org.python.python               0x0000000100078f24 type_call + 212
8   org.python.python               0x000000010000d643 PyObject_Call + 99
9   org.python.python               0x00000001000e9fa6 PyEval_EvalFrameEx + 7654
10  org.python.python               0x00000001000f1cf0 _PyEval_EvalCodeWithName + 2368
11  org.python.python               0x00000001000f1e51 PyEval_EvalCode + 81
12  org.python.python               0x000000010011fa4a PyRun_InteractiveOneObject + 474
13  org.python.python               0x000000010011fdce PyRun_InteractiveLoopFlags + 110
14  org.python.python               0x000000010012073c PyRun_AnyFileExFlags + 76
15  org.python.python               0x0000000100139289 Py_Main + 3785
16  org.python.python               0x0000000100000e32 0x100000000 + 3634
17  org.python.python               0x0000000100000c84 0x100000000 + 3204

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000001030024e0  rbx: 0x00000001011dd648  rcx: 0x00000001013abd31  rdx: 0x0000000101700328
  rdi: 0x00000001030024e0  rsi: 0x00000001030024e0  rbp: 0x00007fff5bfff170  rsp: 0x00007fff5bfff150
   r8: 0x0000000000000004   r9: 0x0000000000000000  r10: 0x0000000000000005  r11: 0x0000000103000000
  r12: 0x0000000000000000  r13: 0x00000001011e1990  r14: 0x00007fff5bfff2a8  r15: 0x00000001011e1920
  rip: 0x000000010130d84b  rfl: 0x0000000000010202  cr2: 0x0000000103007000

Logical CPU:     1
Error Code:      0x00000000
Trap Number:     13

Binary Images:
       0x100000000 -        0x100000ff7 +org.python.python (3.5.1 - 3.5.1) <16087962-95EF-B9B7-A634-47CA97FED0B7> /Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python
       0x100003000 -        0x100212fff +org.python.python (3.5.1, [c] 2001-2015 Python Software Foundation. - 3.5.1) <F6BC2DC9-D79C-2A35-E71B-043D17CCE520> /Library/Frameworks/Python.framework/Versions/3.5/Python
       0x1003e2000 -        0x1003e4fff +readline.cpython-35m-darwin.so (???) <6F7E084B-66F8-8B09-14FB-1A4EF6A86822> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload/readline.cpython-35m-darwin.so
       0x1003eb000 -        0x1003f5ff7 +taglib.cpython-35m-darwin.so (???) <3F789BF7-1F54-345F-98A8-F8E74F0E5F4A> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/taglib.cpython-35m-darwin.so
       0x101211000 -        0x101265fe7 +libncursesw.5.dylib (5) <C8E576B8-5149-DA8D-CD7A-E319C5E8FA9A> /Library/Frameworks/Python.framework/Versions/3.5/lib/libncursesw.5.dylib
       0x101276000 -        0x1013a8fff +libtag.1.dylib (0) <632FBFE6-4E0D-397D-8C3E-FE0D578C3772> /usr/local/lib/libtag.1.dylib
    0x7fff65626000 -     0x7fff6565d25f  dyld (360.22) <A468D85E-D8D6-3461-8C99-49D3B9ACFC63> /usr/lib/dyld
    0x7fff83c52000 -     0x7fff83c69ff7  libsystem_asl.dylib (323.50.1) <41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib
    0x7fff83c6b000 -     0x7fff83c98fff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff83f36000 -     0x7fff83f37ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib
    0x7fff83ff6000 -     0x7fff8401ffff  libsystem_info.dylib (477.50.4) <FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib
    0x7fff84235000 -     0x7fff84235ff7  liblaunch.dylib (765.50.8) <834ED605-5114-3641-AA4D-ECF31B801C50> /usr/lib/system/liblaunch.dylib
    0x7fff8442e000 -     0x7fff84439ff7  libcommonCrypto.dylib (60075.50.1) <93732261-34B4-3914-B7A2-90A81A182DBA> /usr/lib/system/libcommonCrypto.dylib
    0x7fff866a8000 -     0x7fff866d9ff7  libncurses.5.4.dylib (46) <D4C10699-3E8F-3F42-A695-7490EA4B6B32> /usr/lib/libncurses.5.4.dylib
    0x7fff86718000 -     0x7fff8677eff7  libsystem_network.dylib (583.50.1) <B52DAB73-92DC-3DA7-B9F4-B899D66445C1> /usr/lib/system/libsystem_network.dylib
    0x7fff87ab0000 -     0x7fff87ad9ff7  libxpc.dylib (765.50.8) <54D1328E-054E-3DAA-89E2-375722F9D18F> /usr/lib/system/libxpc.dylib
    0x7fff87c3f000 -     0x7fff87c5dff7  libsystem_kernel.dylib (3248.50.21) <78E54D59-D2B0-3F54-9A4A-0A68D671F253> /usr/lib/system/libsystem_kernel.dylib
    0x7fff884da000 -     0x7fff884e2ffb  libsystem_dnssd.dylib (625.50.5) <4D10E12B-59B5-386F-82DA-326F18028F0A> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff88977000 -     0x7fff88979ff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff89209000 -     0x7fff89209ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff8a02e000 -     0x7fff8a02ffff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8a6a5000 -     0x7fff8a6adfff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff8cbc5000 -     0x7fff8cbeefff  libc++abi.dylib (125) <DCCC8177-3D09-35BC-9784-2A04FEC4C71B> /usr/lib/libc++abi.dylib
    0x7fff8ce8b000 -     0x7fff8ce8cfff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8d78f000 -     0x7fff8d797fff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff8d900000 -     0x7fff8dc62f3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff8e066000 -     0x7fff8e06bff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff8eacc000 -     0x7fff8eacfffb  libdyld.dylib (360.22) <CC088C2A-D407-33E7-A6B6-B06E0D4AD999> /usr/lib/system/libdyld.dylib
    0x7fff8ecbd000 -     0x7fff8ecbfff7  libquarantine.dylib (80) <0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib
    0x7fff8ecc0000 -     0x7fff8ed13ff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff8eeec000 -     0x7fff8ef0affb  libedit.3.dylib (43) <1D3E3152-4001-3C19-B56A-7543F1BBA47C> /usr/lib/libedit.3.dylib
    0x7fff8f111000 -     0x7fff8f11aff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff8f61d000 -     0x7fff8f62eff7  libsystem_trace.dylib (201.10.3) <F00E92E4-DBDA-3749-B5B3-0C3FBBABA1CB> /usr/lib/system/libsystem_trace.dylib
    0x7fff8fa8f000 -     0x7fff8fa93fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff8fb77000 -     0x7fff8fb7cff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff900d7000 -     0x7fff9014efeb  libcorecrypto.dylib (335.50.1) <B5C05FD7-A540-345A-87BF-8E41848A3C17> /usr/lib/system/libcorecrypto.dylib
    0x7fff901bf000 -     0x7fff903ccfff  libicucore.A.dylib (551.51.3) <5BC80F94-C90D-3175-BD96-FF1DC222EC9C> /usr/lib/libicucore.A.dylib
    0x7fff90546000 -     0x7fff90594ff7  libstdc++.6.dylib (104.1) <76E2AFB1-07E5-3F19-B692-F6E21B7E470D> /usr/lib/libstdc++.6.dylib
    0x7fff90595000 -     0x7fff905c4ffb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff906d5000 -     0x7fff90b4bfff  com.apple.CoreFoundation (6.9 - 1258.1) <943A1383-DA6A-3DC0-ABCD-D9AEB3D0D34D> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff91730000 -     0x7fff91731fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff93e3e000 -     0x7fff93e3eff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff93e89000 -     0x7fff93ea0ff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff9524f000 -     0x7fff95295ff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff955cf000 -     0x7fff955d1fff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff95cc8000 -     0x7fff95ccbfff  libsystem_sandbox.dylib (460.50.4) <150A9D3D-F69E-32F7-8C7B-8E72CAAFF7E4> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff95eba000 -     0x7fff95f47fff  libsystem_c.dylib (1082.50.1) <B552D565-B798-3B9B-AE63-F623B42A5F01> /usr/lib/system/libsystem_c.dylib
    0x7fff9642a000 -     0x7fff96433ff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff96bd6000 -     0x7fff96bddff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff97a2c000 -     0x7fff97a48ff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff995af000 -     0x7fff995b0ffb  libSystem.B.dylib (1226.10.1) <C5D09FE1-CC70-383E-AC27-18602F2EDEC4> /usr/lib/libSystem.B.dylib
    0x7fff99972000 -     0x7fff99983ff7  libz.1.dylib (61.20.1) <B3EBB42F-48E3-3287-9F0D-308E04D407AC> /usr/lib/libz.1.dylib
    0x7fff99984000 -     0x7fff9998cfef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1441
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=110.9M resident=0K(0%) swapped_out_or_unallocated=110.9M(100%)
Writable regions: Total=67.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=67.2M(100%)

```
                            VIRTUAL   REGION 
```

REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            48.3M       16 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)            512K        3         reserved VM address space (unallocated)
VM_ALLOCATE                          4K        2 
__DATA                            3528K       55 
__LINKEDIT                        92.6M        9 
__TEXT                            18.3M       54 
__UNICODE                          552K        2 
__UNIXSTACK                       16.0M        2 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                            181.7M      142 
TOTAL, minus reserved VM space   181.2M      142 

Model: MacBookPro11,4, BootROM MBP114.0172.B09, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f23
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.5f3 17904, 3 services, 18 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: Hub
USB Device: USB Receiver
USB Device: USB Optical Mouse
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by kdog1425** [comment]
I'm getting the same error, python 2.7, El Capitan. pytaglib 1.3.0 seems to be installed fine, but as soon as I try to open a file, I get seg fault. On another machine, with Yosemite, it works fine.

**Comment by scotchi** [comment]
I'm not able to reproduce this, unfortunately.  Do you see problems also with the examples that ship with TagLib (i.e. tagreader) or only with pytaglib?  (Note that pytaglib is not maintained by the TagLib project.)

**Comment by kdog1425** [comment]
Actually, working fine now. After cleaning up python installations,
reinstalling taglib and pytaglib. thanks --
