### ISSUE TITLE
MP4 files with zero-length boxes/atoms are not supported

### ISSUE THREAD

**Issue by obs1dium** [taglib/taglib#746]
TagLib treats MP4 files with a zero-length box as invalid.
Quoting from chapter 4.2 of the ISO specification:

> if size is 0, then this box is the last one in the file, and its contents extend to the end of the file

The problematic code resides in the MP4::Atom::Atom constructor and the checkValid function in mp4file.cpp

**Comment by TsudaKageyu** [comment]
Hi @obs1dium, 
Sorry for being late, but I'm now working on this issue.

It will be easy to fix this issue. However, I couldn't find a sample MP4 file which has a box with zero length.
So I created a file manually, but I think it's better to use a file created by a real encoder.

Do you know some encoder which creates such files? Or could you provide us with a sample file?

**Comment by obs1dium** [comment]
I encountered this in files downloaded through a streaming service, so I cannot share them here. 

According to the encoder atom they were created using "Dolby Pulse Encoder 1.1.4".
