### ISSUE TITLE
taglib id3tag don't support Chinese code

### ISSUE THREAD

**Issue by huakucha** [taglib/taglib#755]
I use taglib In the Xcode platform
tag->setArtist([@"中文" UTF8String]);
(Or tag->setArtist("中文");)
 self.nsArtist = [NSString stringWithCString:tag->artist().toCString(true) encoding:NSUTF8StringEncoding];

After saving,I can't get the right string except garbled string

**Comment by TsudaKageyu** [comment]
How about this one?
```
tag->setArtist(String([@"中文" UTF8String], String::UTF8));
```
