### ISSUE TITLE
Does "taglib" support to parse out album cover from an audio file ?

### ISSUE THREAD

**Issue by 283958849** [taglib/taglib#763]
I need the **album cover** of a music file, and it seems that "taglib" can not do this.
If it supports, how can I get the PNG image file, some example being best, thank you!!

**Comment by 283958849** [comment]
I'll appreciate if someone helps.

**Comment by sbooth** [comment]
TagLib does support cover art.  Do you need support for a specific file format or something more general?

**Comment by 283958849** [comment]
I **do not** need support for a specific file. 
I even do not know what the format is of the audio files providing by users.
Just for general audio format is OK.  (for example mp3, wma, ogg, aac and so on)

**Comment by scotchi** [comment]
Sorry, but bug reports are not the place to ask about features.  There are both docs for this, and a mailing list.
