### ISSUE TITLE
GitHub page on taglib.github.io is 404

### ISSUE THREAD

**Issue by nirbheek** [taglib/taglib#764]
Seems to be 404 since yesterday; is this on purpose or did someone accidentally wipe it? This breaks all tarball downloads: https://taglib.github.io/releases/taglib-1.7.2.tar.gz

**Comment by scotchi** [comment]
We moved to taglib.org yesterday.  Unfortunately, since we're using GitHub pages, I don't believe that there's any way to do redirects from the old to the new.

**Comment by nirbheek** [comment]
Would be nice if taglib.github.io had a message linking to the new website, and if the old tarballs were preserved on the github page. :)

Right now if you google for taglib you get the old website and there's no way to know what happened to it.

**Comment by scotchi** [comment]
Unfortunately that's also not possible with GitHub pages.  Once you enter a custom domain, only that domain works.  It has me considering, at least temporarily, moving the hosting off of GitHub pages so that we can set up redirects at the old location (which is possible).

**Comment by TsudaKageyu** [comment]
Additionally, please fix the link at the top page of this project.

**Comment by scotchi** [comment]
Ok, so after renaming the repository to `taglib.github.io`, as suggested in the report noted above, redirects do seem to be working properly.
