### ISSUE TITLE
Fehlermeldung beim nutzen in App

### ISSUE THREAD

**Issue by Ollowain87** [taglib/taglib#767]
Hallo,

ich will eine UWP App programmieren in der ich die Metadaten von Musikdateien auslesen. Ich habe taglip eingebunden und in einem normalen Programm funktioniert der Code auch aber in der App nicht.

Hier der Code, der Fehler tritt "Dim Musikdatei As TagLib.File = TagLib.File.Create(Datei.Path)" hier auf.

    Dim folder As StorageFolder
    Private Async Sub menuItem_Open_Explorer()
        Dim ordnerAuswählen = New Pickers.FolderPicker()
        ordnerAuswählen.SuggestedStartLocation = Pickers.PickerLocationId.Desktop
        ordnerAuswählen.FileTypeFilter.Add("*")
        folder = Await ordnerAuswählen.PickSingleFolderAsync()
        txtOrdner.Text = folder.Path
    End Sub

    Private Async Sub Button_Click(sender As Object, e As RoutedEventArgs)
        Dim titel, Interpret, Jahr As String
        Dim Dateienliste As IReadOnlyList(Of StorageFile)
        Dateienliste = Await folder.CreateFileQuery(1).GetFilesAsync()

        For Each Datei As StorageFile In Dateienliste
           ##  **Dim Musikdatei As TagLib.File = TagLib.File.Create(Datei.Path)**
            titel = Musikdatei.Tag.Track

            lblDateien.Items.Add(Datei.Name)
        Next
    End Sub

End Class

Es kommt folgende Fehlermeldung:
Eine Ausnahme vom Typ "System.UnauthorizedAccessException" ist in taglib-sharp.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.

Gibt es hierfür eine Lösung? Oder kann man die Bibliothek nicht in Apps nutzen?

**Comment by scotchi** [comment]
Das ist [TagLib#](https://github.com/mono/taglib-sharp), nicht TagLib.  Diese Projekt ist die C++ Bibliothek.
