### ISSUE TITLE
Problems to Build the Makefiles

### ISSUE THREAD

**Issue by Ollowain87** [taglib/taglib#769]
Hallo,

i have Problems to Build the Makefiles. I have use cmake and as I Build the Makefiles. I get this message ========== Erstellen: 4 erfolgreich, 0 fehlerhaft, 0 aktuell, 3 übersprungen ==========
5>c:\neuer ordner - kopie (2)\taglib-1.10\taglib\toolkit\tiostream.h(53): warning C4251: "TagLib::FileName::m_name": class "std::basic_string<char,std::char_traits<char>,std::allocator<char>>" erfordert eine DLL-Schnittstelle, die von Clients von class "TagLib::FileName" verwendet wird
5>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstring(2633): note: Siehe Deklaration von "std::basic_string<char,std::char_traits<char>,std::allocator<char>>"
5>c:\neuer ordner - kopie (2)\taglib-1.10\taglib\toolkit\tiostream.h(54): warning C4251: "TagLib::FileName::m_wname": class "std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>" erfordert eine DLL-Schnittstelle, die von Clients von class "TagLib::FileName" verwendet wird
5>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstring(2635): note: Siehe Deklaration von "std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>"
5>C:\Neuer Ordner - Kopie (2)\taglib-1.10\bindings\c\tag_c.cpp(135): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
5>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(530): note: Siehe Deklaration von "strdup"
5>C:\Neuer Ordner - Kopie (2)\taglib-1.10\bindings\c\tag_c.cpp(144): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
5>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(530): note: Siehe Deklaration von "strdup"
5>C:\Neuer Ordner - Kopie (2)\taglib-1.10\bindings\c\tag_c.cpp(153): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
5>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(530): note: Siehe Deklaration von "strdup"
5>C:\Neuer Ordner - Kopie (2)\taglib-1.10\bindings\c\tag_c.cpp(162): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
5>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(530): note: Siehe Deklaration von "strdup"
5>C:\Neuer Ordner - Kopie (2)\taglib-1.10\bindings\c\tag_c.cpp(171): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
5>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(530): note: Siehe Deklaration von "strdup"
5>     Bibliothek "C:/Neuer Ordner - Kopie (2)/taglib-1.10/bindings/c/Debug/tag_c.lib" und Objekt "C:/Neuer Ordner - Kopie (2)/taglib-1.10/bindings/c/Debug/tag_c.exp" werden erstellt.
5>  tag_c.vcxproj -> C:\Neuer Ordner - Kopie (2)\taglib-1.10\bindings\c\Debug\tag_c.dll
6>------ Erstellen gestartet: Projekt: ALL_BUILD, Konfiguration: Debug Win32 ------
6>  Building Custom Rule C:/Neuer Ordner - Kopie (2)/taglib-1.10/CMakeLists.txt
6>  CMake does not need to re-run because C:\Neuer Ordner - Kopie (2)\taglib-1.10\CMakeFiles\generate.stamp is up-to-date.
7>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: Debug Win32 ------
7>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt.

**Comment by scotchi** [comment]
There's no error there, only warnings.  And again, please stop posting these things to our bug tracker.  This is a system for reporting problems with TagLib, not for providing support for how to use your compiler.
