### ISSUE TITLE
TagLib getAlbumArt()

### ISSUE THREAD

**Issue by AOrobator** [taglib/taglib#773]
Is there a way to get album art from a file without specifically casing on the kind of file that it is? Preferably I'd get a `byte[]` from the `TagLib::Tag` by `tag->albumArt()`. Or does such a method not exist and will I have to case on all supported formats?

**Comment by FestusHagen** [comment]
There is no unified picture interface in TagLib v1.x branch and likely never will be due to ABI breakage.

There has been some work on this in the TagLib2 branch.

-Enjoy
fh : )_~

**Comment by AOrobator** [comment]
Thanks for the update! How far along are you with this? Would be happy to help with existing issues :)

**Comment by fillobotto** [comment]
I think this could be closed as of branch 2 updates.

**Comment by supermihi** [comment]
See also #397

**Comment by ufleisch** [comment]
Implemented with #1156.
