### ISSUE TITLE
Add Zlib git repository as submodule in the taglib repo for easier building

### ISSUE THREAD

**Issue by CyberSinh** [taglib/taglib#780]
For example, the chomaprint repo added kissfft library as submodule, and if ffmpeg is not detected during CMaking, the kissfft is used as a fallback for building.

**Comment by TsudaKageyu** [comment]
Your point makes sense, however, Git submodule is not very handy with GitHub. For example, Git submodules are not included in tarballs.

I added `ZLIB_SOURCE` option for the same reason. (#392) I know it's not the best solution, but I think it's a good option for Windows users.

**Comment by CyberSinh** [comment]
Hi Tsuda,
For your tarballs issue, have you tried this?
http://stackoverflow.com/questions/17847892/download-git-submodules-for-tarball
Thanks.

**Comment by scotchi** [comment]
I'd prefer not to add this.  It'd only be useful for Windows (since zlib is part of standard Linux and OS X installs) and it means that e.g. in the case of zlib security issues being found that TagLib would need to build a new release immediately.

**Comment by scotchi** [comment]
Maybe this could be handled with a Windows-specific build step that downloads the latest zlib?  (Perhaps we could even put a redirect up on taglib.org so that it automatically went to the latest zlib.)  Something like:

http://stackoverflow.com/questions/8153519/how-to-automatically-download-c-dependencies-in-a-cross-platform-way-cmake

**Comment by CyberSinh** [comment]
Using [vcpkg](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration) as dependencies manager seems to be a good option with taglib2: `vcpkg install utfcpp zlib`
