### ISSUE TITLE
Tagreader can't read this file, but vlc and foobar is ok. 

### ISSUE THREAD

**Issue by zhjb7** [taglib/taglib#788]
Tagreader can't read this file, but vlc and foobar can read.
I was confused that vlc is used Taglib?
https://www.dropbox.com/s/mftcq69lkw0tb4m/01%20Iiro%20Rantala%20%26%20Lars%20Danielsson%20-%20Aria%20-%20DEA891200960%20%2888kHz%2024bit%29.flac?dl=0

**Comment by zhjb7** [comment]
I have found it. The file has a zero size in one block. I n the file -- taglib/flacfile.cpp, scan() function, "if(blockLength == 0 && blockType != MetadataBlock::Padding)" makes the file invalid. 
I continue it in this function and then read the full tag.

**Comment by TsudaKageyu** [comment]
I think this is similar to the issue #98. It looks like some software actually writes zero-sized `METADATA_BLOCK_SEEKTABLE` blocks despite that it violates the FLAC specification.
TagLib doesn't use seektables so it can safely ignore the error. Should it be tolerant of such blocks?
