### ISSUE TITLE
Clear PropertyMap TagLib::File::properties Description

### ISSUE THREAD

**Issue by Stoyvo** [taglib/taglib#789]
http://taglib.org/api/classTagLib_1_1File.html#a7b9714be64e20ffc0ded89ed1bfc98fe

> For files that contain more than one tag (e.g. an MP3 with both an ID3v2 and an ID3v2 tag) only the most "modern" one will be exported (ID3v2 in this case).

Can we get a better definition of this or should this be documented as ID3v2.3 and ID3v2.4 ?

**Comment by supermihi** [comment]
Thanks for reporting the issue. Should have been ID3v1 and ID3v2; I just commited a fix to master, should appear on the API doc pages soon.
