### ISSUE TITLE
NDEBUG is not a macro defined in Release mode by MSVC

### ISSUE THREAD

**Issue by CyberSinh** [taglib/taglib#790]
Hi,

Even if you set TRACE_IN_RELEASE to OFF, the debug tracing is enabled with Visual Studio under Release mode.

It seems that MSVC doesn't define the NDEBUG macro under Release mode so the preprocessor condition in the tdebug.cpp file is always true:
```C
#if !defined(NDEBUG) || defined(TRACE_IN_RELEASE)

#endif
```

Perhaps we could use defined(_DEBUG) instead of !defined(NDEBUG), at least when the compiler is MSVC?

Regards,

Cyber Sinh

**Comment by CyberSinh** [comment]
It appears that NDEBUG is not meant to be defined by MSVC, but by CMake. So, if you don't build the code with CMake, we have to define NDEBUG ourselves.

**Comment by TsudaKageyu** [comment]
Basically, NDEBUG should be defined by programmers. Neither GCC or Clang doesn't define NDEBUG automatically too.

**Comment by CyberSinh** [comment]
Hi Tsuda,

I agree with you, macros should not be defined by compiler directly. 
But IDE, like Visual Studio, has several predefined macros (eg.: based on options/configurations chosen by the developer like _DEBUG):
https://msdn.microsoft.com/en-us/library/b0084kay.aspx
