### ISSUE TITLE
Non free files unicode.{h,cpp}

### ISSUE THREAD

**Issue by cypriani** [taglib/taglib#793]
Hi there,

The automated testing tools in Debian warned me that the files `unicode.h` and `unicode.cpp` from the `taglib/toolkit/` directory are not released under a free software license. See the corresponding lintian tag description for more information: [license-problem-convert-utf-code](https://lintian.debian.org/tags/license-problem-convert-utf-code.html).

With the upcoming Debian release, I had to act quickly, so I repacked the taglib tarball to remove the incriminated files, and wrote a patch that uses ICU (as lintian suggests). Here is the link to that patch:
https://sources.debian.net/src/taglib/1.11.1+dfsg.1-0.1/debian/patches/icu.patch/

The downside is obviously a new external dependency, but libicu is a well recognised library and should be safe to use. I made sure the unit tests still pass with the patch.

As you can see, I used a naive character by character copy to convert between `wchar_t` and `UChar` buffers, which is certainly not ideal. For some reason, the ICU functions that perform this conversion did not give the same results, and made the unit tests fail (see comments in the patch). I did not investigate for too long, because I think the best way to solve this would be to use ICU types and functions in the whole taglib code base, which would suppress the need for these conversions altogether. In my opition, it would be far better than relying on the size of `wchar_t` (which, as you know, can be either bigger or smaller than 16 bits) as is currently the case. ICU works on Windows, and using it would also allow you to get rid of the windows-specific Unicode code.

As is, my patch requires cmake >= 3.7, because the FindICU.cmake module was not shipped with prior cmake releases. It would be trivial to vendor that file if needed, or you could just document that cmake >= 3.7 is needed to build.

Please let me know your thoughts. If you're willing to integrate my patch, I'd be happy to turn it into a pull request if more convenient for you.

  Matteo

**Comment by scotchi** [comment]
The license seems very permissive:

     * Unicode, Inc. hereby grants the right to freely use the information
     * supplied in this file in the creation of products supporting the
     * Unicode Standard, and to make copies of this file in any form
     * for internal or external distribution as long as this notice
     * remains attached.

I can't see how that could be labeled "non-free".  It doesn't use a standard license, but it does meet the Free Software definition.

**Comment by cypriani** [comment]
Hi Scott,

My first link above, as well as  https://bugs.debian.org/823100 explain the reasons. The problems is, mainly, that the license doesn't grant permission to modify the file – unless you assume that “freely use the information supplied in this file” includes distributing modified copies of the file. Also, the permission is limited to “products supporting the Unicode Standard”, which is a problem. I would bet that it does not meet the FSF's free software definition, and it for sure does not meet the Debian Free Software Guideline (DFSG) definition.

From what I understand, and assuming your `unicode.cpp` is derived from Unicode's `convertUTF8.c`, Unicode themselves [retired this code for being buggy](http://unicode.org/forum/viewtopic.php?f=9&t=90); they advise using ICU instead. Taking this and the license problem into account, I see very little reason to keep this vendored code in taglib.

**Comment by TsudaKageyu** [comment]
How about adopting another library like [UTF8-CPP](https://github.com/nemtrif/utfcpp)?
Its license seems to be Boost Software License and we can replace `unicode.h` and `unicode.cpp` without adding a new external dependency.

**Comment by sbooth** [comment]
I agree with @TsudaKageyu that ICU might be a bit heavy for our needs.  It's a great library and is probably the de facto standard when it comes to Unicode but might be overkill for TagLib.

**Comment by cypriani** [comment]
> How about adopting another library like UTF8-CPP?
> 
Sure, if utfcpp works better for you, go for it. It's already packaged in Debian, so it doesn't matter to me.

> Its license seems to be Boost Software License and we can replace unicode.h and unicode.cpp without adding a new external dependency.
> 
If I were you, I would not vendor an external library, but rather depend on it. It forces people building the library from source to get an external dependency, but you won't have to worry about keeping up to date the copy on your repository. In fact `unicode.cpp` is a good (bad) example: the current version in the taglib repo is not the last version published by Unicode. utfcpp seems fairly mature, but bugs could still be found in the future.

That being said, this is just my opinion. In any case, the Debian package will have to use the packaged version of the library in order to respect the Policy.

My apologies for bringing up another license issue, I know this is not very fun but we Debian folks are pretty picky about that. Hopefully this will be the last one!

**Comment by TsudaKageyu** [comment]
Those files have been replaced.
