### ISSUE TITLE
Lyrics Synchronisation frame

### ISSUE THREAD

**Issue by lemonboy999** [taglib/taglib#804]
Many .lrc files contain a timestamp with no text. This is good for a space between e.g. space between verse and chorus.
Currently taglib handles this by ignoring everything after an  entry with no text.
 
I have a fix for this. 
synchronizedlyricsframe.cpp  line 192 to read;
if(pos + 4 > end)
rather than
if(text.isEmpty() || pos + 4 > end)

I have made this adjustment and compiled it on windows and linux and tested with more than 4000 files containing a SYLT frame generated from a .lrc file, and have not encountered a problem. However I do not understand the original reason for the text.IsEmpty check in the original code.
I would suggest removing the test, unless there is a reason for including it that I have missed.

**Comment by TsudaKageyu** [comment]
I think that we can remove the check safely because the original author used `text.isNull()` which can never be true.

**Comment by TsudaKageyu** [comment]
Done. Thanks @lemonboy999!
