### ISSUE TITLE
Cannot read this OGG file

### ISSUE THREAD

**Issue by fillobotto** [taglib/taglib#806]
Trying to read this ogg file with TagLib 2 results in `isNull()` to be true, however the file is playable and I can successfully inspect it with Exiftool.

```
TagLib::FileRef f(nativeString);
if(f.isNull())
     return 1;
```
[Domino.zip](https://github.com/taglib/taglib/files/801286/Domino.zip)

**Comment by scotchi** [comment]
That's a Theora file (i.e. not Ogg Vorbis), which TagLib does not support.

**Comment by fillobotto** [comment]
Thanks for the info. Can you please give me direction about how to verify that so I won't open useless issues anymore?

**Comment by scotchi** [comment]
I actually initially checked with a hex editor, but this also works:

    $ file Domino.ogg 
    Domino.ogg: Ogg data, Theora video
