### ISSUE TITLE
NuGet - Cannot install to any v. of .NET

### ISSUE THREAD

**Issue by vincentjenks** [taglib/taglib#819]
Regardless of target .NET version, I'm unable to install taglib. I've tried .NET 4 through 4.7 and always get this error:

> install-package : Could not install package 'taglib 2.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Googling revealed that it may be the NuGet package and have nothing to do w/ the version of .NET being used:

http://stackoverflow.com/questions/34463262/nugets-install-in-visual-studio-2015

I've tried both VS 2015 and 2017 and the result is the same.

**Comment by scotchi** [comment]
This project is the C++ version of TagLib.  TagLib# was based on it many years ago (and unfortunately did not change the name when porting to C#.)  We don't have any influence on the C# project.
