### ISSUE TITLE
Taglib2 Is Not Full Support for Wav Format

### ISSUE THREAD

**Issue by yanxijian** [taglib/taglib#826]
Hi, I am using taglib2 currently. I found that taglib2 could not read the length for some wav files, and the meta-data info(in Chinese) was not showed properly in Windows 10.
![Display](https://user-images.githubusercontent.com/9412262/27362798-593a2f7c-5663-11e7-9171-982126794f9b.png)
![Tag Version](https://user-images.githubusercontent.com/9412262/27365391-79105cf4-5672-11e7-8e8f-f7508e18dffa.png)

But it is all right when I use Mp3tag V2.82 to edit it. The following is the difference in binary of the two wav files.
![Difference](https://user-images.githubusercontent.com/9412262/27362867-b18cf704-5663-11e7-87bf-35160f67152b.png)
Here are the two [sample files](https://drive.google.com/open?id=0B0TpaScvUJpNUnQxUk80THBGaEk).

What's more, I once used taglib1, too. But after editing meta-data with it, the meta-data info was not visible in Windows.

**Comment by FestusHagen** [comment]
Windows does not support ID3v2.4.

-Enjoy
fh : )_~

**Comment by yanxijian** [comment]
@FestusHagen I think Windows supports ID3v2.4, but the content of "**RIFF::Info::Tag**(LIST chunk)" should be in ANSI, not UTF-8(ID3v2.4) or UCS-2(IDV3v2.3). [Wiki](https://en.wikipedia.org/wiki/ID3#ID3v2)
A sample here: **测**  **B2E2** (GBK)   **E6 B5 8B** (UTF-8) 
![c](https://user-images.githubusercontent.com/9412262/27396349-5f91dbcc-56e5-11e7-9261-ac5244b5f306.png)
![d](https://user-images.githubusercontent.com/9412262/27396351-61255edc-56e5-11e7-9532-f38a350c2080.png)
The normal one is edited by Mp3tag. And I tested that I could not use Japanese in tags. I would check all above mentioned at work tomorrow.
The other question: The taglib2 could not read the length for some wav files. The reason may be
![a](https://user-images.githubusercontent.com/9412262/27396923-31819c20-56e7-11e7-8ee2-3fa820b37ecd.png)

**Comment by FestusHagen** [comment]
I stand corrected, It appears Microsoft has finally updated Win10 to include support for ID3v2.4. ;)

**Comment by yanxijian** [comment]
The first question(can not read the length): I have push a request.
The second question: the reason is that the tag info should be written in ANSI.
