### ISSUE TITLE
ID3v2::Tag setTitle(String::null) restores original value

### ISSUE THREAD

**Issue by framtk** [taglib/taglib#838]
In the documentation it's written that passing a string s to setTitle:  
 
**"Sets the title to s. If s is String::null then this value will be cleared. "**  

I was expecting the value of the title to be removed or at least be set to empty string, in practice using String::null "resets" the value to the one it was the first time it was set and the only way to remove the title is to remove its frame.
  
As an example, let's assume that the tag doesn't have a title frame the first time the program is run. Think of this code as the same program just changing the title to set each time it's run:
```
tag->setTitle("A");
f.save();
std::cout << tag->title(); // prints A
```
```
tag->setTitle("B");
f.save();
std::cout << tag->title(); // prints B
```
```
tag->setTitle("C");
f.save();
std::cout << tag->title(); // prints C
```
```
tag->setTitle("D");
f.save();
std::cout << tag->title(); // prints D
```
```
tag->setTitle(String::null);
f.save();
std::cout << tag->title(); // prints A again
```

I think this is either an error in the code or in the documentation (the same happens for all other setters)

**Comment by scotchi** [comment]
I understand that this is confusing, but the source of the confusion is that MP3 files can contain multiple tags, and TagLib tries to keep them all consistent, unless you specifically tell it not to.  So if that value still exists in the ID3v1 tag, saving the file will duplicate the value from the ID3v1 tag into the ID3v2 tag.  It is possible to override that behavior, however:

https://taglib.org/api/classTagLib_1_1MPEG_1_1File.html#a6615fd8f9dfd1f932d5a2994b52a6595
