### ISSUE TITLE
Memory error using String's to8Bit method in a MSVC build

### ISSUE THREAD

**Issue by dbogdanov** [taglib/taglib#845]
I am using Taglib in my project on windows. Everything is build with MSVC (VS 2017) including Taglib (following the instructions in INSTALL.md).

There's a memory error when running the String's ```to8Bit``` method: 

Simple example:
```
TagLib::String x("TEST");
cerr << "String size =" << x.size() << endl;
cerr << "String =" << x << endl;
cerr << "String (toCString) =" << x.toCString() << endl;
cerr << "String (to8Bit) size =" << x.to8Bit(true).size() << endl;
cerr << "String (to8Bit) =" << x.to8Bit(true) << endl;
```

Output:
```
String size =4
String =TEST
String (toCString) =TEST
String (to8Bit) size =98290984
String (to8Bit) =<some memory junk here>
```

What can be a reason for that?

**Comment by scotchi** [comment]
This is presumably because of the temporary object lifetimes.  You probably need to assign both the value to a temporary variable for it to work, e.g.:

    std::string s = x.to8Bit();
    cerr << s;

**Comment by dbogdanov** [comment]
This ends up with the same error. I am linking to taglib dll if that matters.

**Comment by scotchi** [comment]
Are you able to create a testcase where you can reproduce this?  (See the `/tests` dir.)

`PropertyMap` is just a relatively thing wrapper around `std::map<String, StringList>`, so my inclination would be that you may have memory corruption somewhere else in your app.  (And I personally don't develop on Windows at all, so I don't have the ability to check things out there; some of the other TagLib developers do, however.)

**Comment by dbogdanov** [comment]
Actually, the most basic code that fails is 

```
// just trying to open a non-existing file
wchar_t *hello = L"hello";
TagLib::FileRef f(hello);
```
Might be some linking issues?

I also get warnings:

```
c:\users\user\dev\essentia\packaging\win32_3rdparty\builds\taglib-1.11.1\include\taglib\tiostream.h(53): warning C4251: 'TagLib::FileName::m_name': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'TagLib::FileName'
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.11.25503\include\xstring(4079): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
c:\users\user\dev\essentia\packaging\win32_3rdparty\builds\taglib-1.11.1\include\taglib\tiostream.h(54): warning C4251: 'TagLib::FileName::m_wname': class 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>' needs to have dll-interface to be used by clients of class 'TagLib::FileName'
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.11.25503\include\xstring(4080): note: see declaration of 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>'

```

**Comment by scotchi** [comment]
This certainly sounds like an issue with your build set up; obviously the code above works in normal cases.  May I suggest asking on the mailing list?  taglib-devel@kde.org  You're likely to find more people with a similar setup there, and possibly that recognize the specific error that you're hitting.  (The list is read by probably 100 people, whereas the issue tracker is only read by about 4.)

I don't know Windows development particularly, but my guess from the above is that you're building Essentia / TagLib with mingw, and then trying to link that into a Visual Studio project?  I know that mixing compilers for C++ interfaces can be problematic on Windows.

**Comment by dbogdanov** [comment]
@scotchi  Sure, I'll ask the dev mailing list. I am building everything in Visual Studio, including Taglib.

**Comment by dbogdanov** [comment]
Solved.  It appears I was using Debug version of the library while my project wasn't compiled in Debug mode, without realizing it.
