### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [taglib/taglib#847]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by scotchi** [comment]
I'd be open to a patch for this, but since there haven't been any other folks asking for this thusfar, I'm going to close it for now.

**Comment by mariaTaboadaPena** [comment]
I need use taglib with conan, could you please reopen this?

**Comment by AmateurECE** [comment]
I also wanted to package taglib for one of my projects that uses it as a dependency, so I created this repository here: https://github.com/AmateurECE/conan-taglib/
If you have Conan installed, you can clone this repository and build the package to your local cache from source with:
```
conan create . taglib/1.11.1
```
