### ISSUE TITLE
Visual Studio 15 2017 error link

### ISSUE THREAD

**Issue by AlzoxX76** [taglib/taglib#849]
Hi,

I compiled in static mode taglib for Visual Studio 15 2017 ( `cmake -G "Visual Studio 15 2017"  -DCMAKE_INSTALL_PREFIX=C:\Libraries\taglib -DBUILD_SHARED_LIBS=OFF -DENABLE_STATIC_RUNTIME=ON` ) and when I link (tag.lib) and include header of taglib I get this error : 

`
1>main.obj : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: virtual __thiscall TagLib::FileRef::~FileRef(void)" (__imp_??1FileRef@TagLib@@UAE@XZ)
1>main.obj : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __thiscall TagLib::FileRef::FileRef(class TagLib::FileName,bool,enum TagLib::AudioProperties::ReadStyle)" (__imp_??0FileRef@TagLib@@QAE@VFileName@1@_NW4ReadStyle@AudioProperties@1@@Z)
1>main.obj : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __thiscall TagLib::FileName::FileName(char const *)" (__imp_??0FileName@TagLib@@QAE@PBD@Z)
1>main.obj : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __thiscall TagLib::FileName::~FileName(void)" (__imp_??1FileName@TagLib@@QAE@XZ)
`

**Comment by FestusHagen** [comment]
define TAGLIB_STATIC in your project.

-Enjoy
fh : )_~

**Comment by AlzoxX76** [comment]
Thank you it's work :)
