### ISSUE TITLE
Genre Won

### ISSUE THREAD

**Issue by ubbrownjr** [taglib/taglib#851]

**Comment by ubbrownjr** [comment]
Setting the genre to "Gospel" does not work ... it always sets it to the numerical 38 for some reason
$media.Tag.Genres = "Gospel"

although the powershell will show the genre updated to "Gospel" under properties it will show the number 38

**Comment by scotchi** [comment]
Hi - it sounds like you're describing an issue with TagLib#, which is a separate project from TagLib (though it was originally based on TagLib).
