### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by HappenOoo** [taglib/taglib#861]
02-01 03:26:29.323 18595 18595 F DEBUG   : backtrace:
02-01 03:26:29.323 18595 18595 F DEBUG   :     #00 pc 001f0000  /dev/ashmem/dalvik-main space (deleted) (offset 0x210000)
02-01 03:26:29.323 18595 18595 F DEBUG   :     #01 pc 00037fc3  /system/lib/libtaglib.so (_ZN6TagLib4MPEG10Properties4readEv+478)
02-01 03:26:29.323 18595 18595 F DEBUG   :     #02 pc 00037dd9  /system/lib/libtaglib.so (_ZN6TagLib4MPEG10PropertiesC2EPNS0_4FileENS_15AudioProperties9ReadStyleE+76)
02-01 03:26:29.323 18595 18595 F DEBUG   :     #03 pc 00035ed5  /system/lib/libtaglib.so (_ZN6TagLib4MPEG4File4readEbNS_15AudioProperties9ReadStyleE+292)
02-01 03:26:29.323 18595 18595 F DEBUG   :     #04 pc 00035d9d  /system/lib/libtaglib.so (_ZN6TagLib4MPEG4FileC2EPKcbNS_15AudioProperties9ReadStyleEb+124)
02-01 03:26:29.323 18595 18595 F DEBUG   :     #05 pc 0004f7db  /system/lib/libtaglib.so (_ZN6TagLib7FileRef6createEPKcbNS_15AudioProperties9ReadStyleEb+214)
02-01 03:26:29.323 18595 18595 F DEBUG   :     #06 pc 0004f6ef  /system/lib/libtaglib.so (_ZN6TagLib7FileRefC1EPKcbNS_15AudioProperties9ReadStyleEb+38)
02-01 03:26:29.324 18595 18595 F DEBUG   :     #07 pc 00000fc7  /system/priv-app/Music/Music.apk (offset 0x3d3000)

////////////////////////////////////////////////////////////////////////////////
// private members
////////////////////////////////////////////////////////////////////////////////

void MPEG::Properties::read()
{
  // Since we've likely just looked for the ID3v1 tag, start at the end of the
  // file where we're least likely to have to have to move the disk head.

  long last = d->file->lastFrameOffset();

  if(last < 0) {
    debug("MPEG::Properties::read() -- Could not find a valid last MPEG frame in the stream.");
    return;
  }

  d->file->seek(last);
  Header lastHeader(d->file->readBlock(4));

  long first = d->file->firstFrameOffset();

  if(first < 0) {
    debug("MPEG::Properties::read() -- Could not find a valid first MPEG frame in the stream.");
    return;
  }

  if(!lastHeader.isValid()) {

    long pos = last;

    while(pos > first) {

      pos = d->file->previousFrameOffset(pos);

      if(pos < 0)
        break;

      d->file->seek(pos);
      Header header(d->file->readBlock(4));

      if(header.isValid()) {
        lastHeader = header;
        last = pos;
        break;
      }
    }
  }

  // Now jump back to the front of the file and read what we need from there.

  d->file->seek(first);
  Header firstHeader(d->file->readBlock(4));

  if(!firstHeader.isValid() || !lastHeader.isValid()) {
    debug("MPEG::Properties::read() -- Page headers were invalid.");
    return;
  }

  // Check for a Xing header that will help us in gathering information about a
  // VBR stream.

  int xingHeaderOffset = MPEG::XingHeader::xingHeaderOffset(firstHeader.version(),
                                                            firstHeader.channelMode());

  d->file->seek(first + xingHeaderOffset);
  d->xingHeader = new XingHeader(d->file->readBlock(16));

  // Read the length and the bitrate from the Xing header.

  if(d->xingHeader->isValid() &&
     firstHeader.sampleRate() > 0 &&
     d->xingHeader->totalFrames() > 0)
  {
      double timePerFrame = firstHeader.sampleRate() > 0 ? double(firstHeader.samplesPerFrame()) / firstHeader.sampleRate() : 0;
      d->length = int(timePerFrame * d->xingHeader->totalFrames());
      d->bitrate = d->length > 0 ? d->xingHeader->totalSize() * 8 / d->length / 1000 : 0;
  }
  else {
    // Since there was no valid Xing header found, we hope that we're in a constant
    // bitrate file.

    delete d->xingHeader;   
    d->xingHeader = 0;

    // TODO: Make this more robust with audio property detection for VBR without a
    // Xing header.

    if(firstHeader.frameLength() > 0 && firstHeader.bitrate() > 0) {
      int frames = (last - first) / firstHeader.frameLength() + 1;

      d->length = int(float(firstHeader.frameLength() * frames) /
                      float(firstHeader.bitrate() * 125) /*+ 0.5*/); // Not add 0.5s as offset to reduce the difference with MediaPlayer.getDuration()
      d->bitrate = firstHeader.bitrate();
    }
  }

  d->sampleRate = firstHeader.sampleRate();
  d->channels = firstHeader.channelMode() == Header::SingleChannel ? 1 : 2;
  d->version = firstHeader.version();
  d->layer = firstHeader.layer();
  d->protectionEnabled = firstHeader.protectionEnabled();
  d->channelMode = firstHeader.channelMode();
  d->isCopyrighted = firstHeader.isCopyrighted();
  d->isOriginal = firstHeader.isOriginal();
}

delete d->xingHeader;      !!!"?? any issue.   help.

**Comment by FestusHagen** [comment]
I don't develop on Android, however, have you tried one of the examples like ```tagreader.cpp``` or ```tagwriter.cpp``` to ensure the setup is good to go.

Backtrace looks skimpy.

FYI: Including Taglib source is unnecessary ...

-Enjoy

**Comment by scotchi** [comment]
As @FestusHagen noted, there's not enough information in this report to do anything with.
