### ISSUE TITLE
Track Total information is missing / removed from tags

### ISSUE THREAD

**Issue by timusus** [taglib/taglib#866]
There's currently no way in TagLib to retrieve the 'track total' (total number of tracks on an album) from a file.

According to the id3v2.3.0 spec:
> `TRCK  [#TRCK Track number/Position in set]`

It's my understanding that 'position in set' represents the total number of tracks. So, a `TRCK` string such as `02/12` represents Track 02, of 12 Total Tracks. If there is no `/`, then it can be assumed there is no track total.

However, TagLib returns `track()` as an integer, rather than a string.

I'm not very familiar with CPP, but the following line from `id3v2tag.cpp`:
```
unsigned int ID3v2::Tag::track() const
{
  if(!d->frameListMap["TRCK"].isEmpty())
    return d->frameListMap["TRCK"].front()->toString().toInt();
  return 0;
}
```
Looks like only the first string in the `TRCK` frame is returned, and it is converted to an integer or discarded.

I don't think VORBIS tags have a standard for total tracks, however, `TRACKTOTAL` was proposed a few years ago. 

Related to #783

**Comment by scotchi** [comment]
It is possible to get the track total, but you have to grab it from the frame directly -- you can't use `track()`.  Note that you can do almost the same thing that the `track()` implementation does by accessing the frameList using [this method](http://taglib.org/api/classTagLib_1_1ID3v2_1_1Tag.html#ab954025fb0bddd3c4a65cb71c385fb58) and then just skip the integer conversion at the end.
