### ISSUE TITLE
potential heap based overread

### ISSUE THREAD

**Issue by castilma** [taglib/taglib#868]
Hi, I'm just randomly passing by.
I read \[0] and the reply to it and decided to mention this here.

From a quick look, this isn't really information disclosure, since it's only one byte that's being read, which is nowhere written to.

The relevant file is [oggflacfile.cpp:237](https://github.com/taglib/taglib/blob/master/taglib/ogg/flac/oggflacfile.cpp#L237)
From a quick look, it's because it does not check, whether Metadataheader is 5 bytes long(and not 4).

\[0]: http://seclists.org/fulldisclosure/2018/May/49

**Comment by sgayou** [comment]
Pull request for potential fix.
