### ISSUE TITLE
:-1: error: App/libraries/linux/taglib/lib//libtag.a(tzlib.cpp.o): undefined reference to symbol 'inflateInit_'

### ISSUE THREAD

**Issue by LinArcX** [taglib/taglib#875]
Hi. and thank you for this awesome library.
I want to use it in a qt-quick application. so i compiled it from source, according to your instructions. and link it in qmake:
```
    # tagLib
    LIBS += -L$$PWD/libraries/linux/taglib/lib -ltag
    PRE_TARGETDEPS += $$PWD/libraries/linux/taglib/lib/libtag.a
    INCLUDEPATH += $$PWD/libraries/linux/taglib/include/taglib
    DEPENDPATH += $$PWD/libraries/linux/taglib/include/taglib
```
when i want to build the project, qmake complains:
```
/usr/bin/ld: /mnt/D/Document/WorkSpace/Qt/Project/Naghme/libraries/linux/taglib/lib/libtag.a(tzlib.cpp.o): undefined reference to symbol 'inflateInit_'
/usr/bin/ld: /usr/lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:290: Naghme] Error 1
19:46:09: The process "/usr/bin/make" exited with code 2.
```

**Comment by LinArcX** [comment]
up!

**Comment by LinArcX** [comment]
:-1: error: /usr/lib/libz.so.1: error adding symbols: DSO missing from command line

**Comment by scotchi** [comment]
This is basic Linux development, not anything TagLib specific.  In this case, you need to either add `-lz` to your linker flags, or use TagLib's pkgconfig file, which will pull it in automatically.

**Comment by boegel** [comment]
If anyone else is hitting this problem: this linking issue occur when using TagLib 1.11.1 (latest stable release to date), but it's fixed in `master` (cfr. #872 and https://github.com/taglib/taglib/commit/ef1312d62239f399c40233d76ef3328b8dadf984).
