### ISSUE TITLE
Album name not being tagged

### ISSUE THREAD

**Issue by DavidOrazine** [taglib/taglib#876]
Hello everyone,

I have a project that uses this library. Everything is working great except the album name is not being tagged. I can see the value is there at run time, when I save the tag info, open it up with a tag reading software, these is everything there except the album name. I am new to tagging, am I doing anything wrong?

I have tried adding these lines to the program:

                TagLib.Id3v2.Tag.DefaultVersion = 3
                TagLib.Id3v2.Tag.ForceDefaultVersion = True
                TagLib.Id3v2.Tag.ForceDefaultEncoding 

These have not yielded any luck.

Thanks in advance!

**Comment by scotchi** [comment]
Looks like you're using the (unfortunately named) TagLib#, which is separate (though originally based on) TagLib.  This project is the C++ library.

**Comment by DavidOrazine** [comment]
Thank you, sorry for the confusion.
