### ISSUE TITLE
Libtag segfaults on mkv files

### ISSUE THREAD

**Issue by ltworf** [taglib/taglib#880]
Ok you don't want to support them.

Segfault is not the answer.

**Comment by scotchi** [comment]
Can you paste in the code that's segfaulting?

**Comment by ltworf** [comment]
```
TagLib::FileRef tags(i.filePath().toStdString().c_str());
```

where i is a QFile pointing to a mkv.

**Comment by scotchi** [comment]
That works just fine here (tested on macOS and Linux).  I believe the problem is that you're using `c_str()` from a temporary variable.

**Comment by scotchi** [comment]
To be clearer, this is the code I used:

```
#include <fileref.h>
int main(int argc, const char *argv[])
{
    TagLib::FileRef tags(argv[1]);
    return 0;
}
```

**Comment by ltworf** [comment]
I have ii  libtag1v5:amd64                               1.11.1+dfsg.1-0.2+b1           amd64        audio meta-data library

Is it a different version than latest release?

**Comment by scotchi** [comment]
Yes, that's the version I was testing with.

**Comment by scotchi** [comment]
Closing this for now unless there's some further info at some point.  At this point it's not possible to reproduce the issue you're seeing.

**Comment by ltworf** [comment]
I was not aware I had to check isNull() besides isEmpty()
