### ISSUE TITLE
Access to less standard ID3 fields

### ISSUE THREAD

**Issue by ryanfrancesconi** [taglib/taglib#884]
I need access to the less standard tags such as Arranger, BPM, Composer, Grouping, Publisher, Composer, etc.

Taglib works great for the standard ones, but in looking at the source, doesn't seem particularly flexible to extend it. Is there any way to currently get at these ID3 frames that I've overlooked?

Thanks!
Ryan

**Comment by supermihi** [comment]
Duplicate of #665 - see `Tag::properties()`

**Comment by ryanfrancesconi** [comment]
ah thanks!
