### ISSUE TITLE
Issue with MP4 rate atom in git

### ISSUE THREAD

**Issue by astippich** [taglib/taglib#885]
Hello,

openSUSE Tumbleweed recently updated to a git version of taglib, and since then the CI tests of KDE's KFileMetaData library fail with the MP4 "rate" atom.
I think the issue is https://github.com/taglib/taglib/pull/818
which changes the internal representation of the rate atom from text to int. However, this causes a regression when reading files that previously saved the rating as text. For example, if the rate atom was written to "80" as text, or 0x3830, taglib will now interpret it as integer, which yields 14384.
I am also now unable to read ratings saved with e.g. MediaMonkey or MP3Tag, which seem to save them as text as well.
Thoughts?

**Comment by StefanBruens** [comment]
I think this could be fixed in a compatible way by respecting the "class" of the atom when reading it. The sample file mentioned above has class 1 == UTF-8 for the "rate" atom.

**Comment by scotchi** [comment]
The fix for this was already merged.
