### ISSUE TITLE
readonly permissions ignored when running as root

### ISSUE THREAD

**Issue by supermihi** [taglib/taglib#890]
When running as root and opening a file with taglib that has no write permissions, `File::readOnly()` returns `true`, while at the same time `File::save()` **does not** throw an error but modifies the file.

I wonder if this is a bug or intended behavior? I'd tend to the former because `readOnly=true` feels inconsistent with being able to save.

I came across this while trying to set up a docker-based CI for [pytaglib](https://github.com/supermihi/pytaglib), in which everything runs as `root` user. The tests assessing that exceptions are thrown when trying to save readonly files are failing.

**Comment by sbooth** [comment]
Is it safe to close this since `root` can always write to any file?

**Comment by scotchi** [comment]
While I understand how this is confusing, I think this is the correct behavior.
