### ISSUE TITLE
Undefined reference using Taglib with Qt

### ISSUE THREAD

**Issue by avignat** [taglib/taglib#897]
Hello,

I can't get Taglib to work with Qt on Windows 10 64bits but I can with GNU/Linux 64bits.

![](https://i.stack.imgur.com/S02nd.jpg)

I successfuly managed to build Taglib as explain in the manual with cmake and the compiler provided by Qt (`C:\Qt\Tools\mingw730_64\bin\`) and the variable `CMAKE_BUILD_TYPE=Release`

Then with the shell provided by Qt for MinGW 7.3.0 64bits I can run `mingw32-make` to build it.
With `mingw32-make install` I have everything I need in `C:\Program Files (x86)\taglib\` the .a and .h files (no .dll?).

.pro file generated using the tool to add external libraries in Qt Creator :

```
LIBS += -L$$PWD/'../../../../../Program Files (x86)/taglib/lib/' -llibtag

INCLUDEPATH += $$PWD/'../../../../../Program Files (x86)/taglib/include'
DEPENDPATH += $$PWD/'../../../../../Program Files (x86)/taglib/include'
```
cpp code :
```
void MainWindow::test()
{
    TagLib::FileRef f("Latex Solar Beef.mp3");
}
```
What am I missing?

**Comment by Chukak** [comment]
HI!
Change it and try again: 
`LIBS += -L$$PWD/'../../../../../Program Files (x86)/taglib/lib/' -ltag`

Also you may need this in your .pro: `DEFINES += TAGLIB_STATIC`

**Comment by avignat** [comment]
Thanks I was missing the `DEFINES += TAGLIB_STATIC`
