### ISSUE TITLE
Support ID3v2 GRP1 frame introduced with iTunes 12.5.4.42

### ISSUE THREAD

**Issue by ufleisch** [taglib/taglib#903]
TagLib already supports iTunes specific ID3v2 frames such as WFED (Podcast URL), MVNM (Movement Name), MVIN (Movement Number), but support for GRP1 (Grouping) is missing.
See also [iTunes GRP1 id3 frame](http://kde.6490.n7.nabble.com/iTunes-GRP1-id3-frame-td1661453.html#a1661459).

**Comment by scotchi** [comment]
This was already merged.
