### ISSUE TITLE
Runtime version check?

### ISSUE THREAD

**Issue by Moonbase59** [taglib/taglib#920]
There should be a runtime (API) "get version" call, to determine which taglib we’re using when using shared objects or DLLs.

Since there wasn’t a new version for some time, but some bugs have been fixed, it might even make sense to also return the commit hash from which it has been built, maybe optional. Programs like loudgain and others could thus better work around known bugs (like #864).

**Comment by scotchi** [comment]
Out of curiosity, what's the use case that you imagine runtime version information being useful in? (It is available at build time.) I'm not aware of many cases where a program is built against a different version of TagLib than the one that it's using at runtime (though it is possible, and TagLib maintains binary compatibility to support such).

**Comment by Moonbase59** [comment]
Just take the case above (#864): My loudgain ReplayGain tagger should be sure not to corrupt Ogg Vorbis files. Mixxx already blocks TagLib 1.11.1 for writing tags …

With shared libraries, we must be sure that the use can (and will) update these independently from the application, and some distros still ship buggy versions.
