### ISSUE TITLE
Implement functions to read and write User Text fields 

### ISSUE THREAD

**Issue by dougforester** [taglib/taglib#921]
Both .mp3 and .wma files support user text fields by providing a key (called a Description in TagLib) and text (called Text in TagLib). I have modified my local copy of TagLib to implement two (TagLib-virtual) functions UserText() and setUserText(). They are analogous to functions like title() and setTitle() and are declared as:
`
virtual String userText(const String &description);

virtual void setUserText(const String &description, const String &text);
`
I would like to make the changes to TagLib or provide them to someone who can make the changes. What is the best way to proceed?

**Comment by scotchi** [comment]
Until we're pushing for TagLib 2.0 (which is another whole debate), we're unable to add virtual functions to public interfaces as it breaks binary compatibility with existing releases.
