### ISSUE TITLE
AIFF: No "save (TagTypes tags, bool stripOthers=true, int id3v2Version=4)"

### ISSUE THREAD

**Issue by Moonbase59** [taglib/taglib#922]
**AIFF** files are usually written using _ID3v2.3_ tags (iTunes and dBPowerAmp don’t support ID3v2.4).

Using `TagLib::RIFF::AIFF::File::save()` always produces ID3v2.4 tags (the default).

Why is there no function
```
TagLib::RIFF::AIFF::File::save(TagTypes tags, bool stripOthers=true, int id3v2Version=4)
```
like we have in `TagLib::RIFF::WAV::File`?

Is there any other method to get _ID3v2.3_ tags instead?

I’d really need that so [loudgain](https://github.com/Moonbase59/loudgain) can write correct tags for AIFF file users. Thanks!

**Comment by Moonbase59** [comment]
@scotchi: I know you currently don’t have too much time (congrats on the new baby!), would it be okay for you if I tried to prepare a minimal PR for this issue that would introduce a new
```
TagLib::RIFF::AIFF::File::save(int id3v2Version=4)
```
function?

This would be quite simple, and we don’t have "TagTypes" and "stripOthers" on AIFF anyway.
The change might be small enough to get into the next version, and have AIFF users benefit from getting "readable" tags. I know AIFF has officially been more or less abandoned but broadcasting professionals still use it everyday and often even catalog using iTunes.

Any objections? Or would you insist on keeping the "standard" `save(TagTypes, strip, id3v2version)` sequence (thus introducing probably unneeded code)?

**Comment by scotchi** [comment]
Honestly, I'm not crazy about the current API there in general.  I'd prefer for it to use an enum rather than an integer.  Let me have a look at the existing API in the next couple of days and I'll see if they can be unified towards something I'm happier with.

**Comment by Moonbase59** [comment]
Ok, great!

I’m currently trying to test some stuff on Linux Mint 19.2 (Ubuntu 18.04-based) but I can’t for the life of me find out how to run the test suite. Whatever I do, make complains `*** Keine Regel, um „check“ zu erstellen.  Schluss.`.

I’ve installed `cppunit-dev` and try either of the following:
```bash
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=on .
$ make all
$ make check
```
```bash
$ cmake -DBUILD_TESTS=on .
$ make check
```
Any ideas? (I do want the tests to run ok before making a PR …)

**Comment by Moonbase59** [comment]
Just for a quick glance and my tests, the following _should_ work, right? Or am I making a dumb mistake?

```diff
--- a/taglib/riff/aiff/aifffile.h
+++ b/taglib/riff/aiff/aifffile.h
@@ -119,6 +119,8 @@ namespace TagLib {
          */
         virtual bool save();
 
+        bool save(int id3v2Version = 4);
+
         /*!
          * Returns whether or not the file on disk actually has an ID3v2 tag.
          *
```
```diff
--- a/taglib/riff/aiff/aifffile.cpp
+++ b/taglib/riff/aiff/aifffile.cpp
@@ -117,6 +117,11 @@ RIFF::AIFF::Properties *RIFF::AIFF::File::audioProperties() const
 }
 
 bool RIFF::AIFF::File::save()
+{
+  return RIFF::AIFF::File::save(4);
+}
+
+bool RIFF::AIFF::File::save(int id3v2Version)
 {
   if(readOnly()) {
     debug("RIFF::AIFF::File::save() -- File is read only.");
@@ -135,7 +140,7 @@ bool RIFF::AIFF::File::save()
   }
 
   if(tag() && !tag()->isEmpty()) {
-    setChunkData("ID3 ", d->tag->render());
+    setChunkData("ID3 ", d->tag->render(id3v2Version));
     d->hasID3v2 = true;
   }
```

**Comment by Moonbase59** [comment]
Hm … or should it be like this—to remove the ambiguity?

```diff
--- a/taglib/riff/aiff/aifffile.h
+++ b/taglib/riff/aiff/aifffile.h
@@ -119,6 +119,8 @@ namespace TagLib {
          */
         virtual bool save();
 
+        bool save(int id3v2Version);
+
         /*!
          * Returns whether or not the file on disk actually has an ID3v2 tag.
          *
```

```diff
--- a/taglib/riff/aiff/aifffile.cpp
+++ b/taglib/riff/aiff/aifffile.cpp
@@ -117,6 +117,11 @@ RIFF::AIFF::Properties *RIFF::AIFF::File::audioProperties() const
 }
 
 bool RIFF::AIFF::File::save()
+{
+  return RIFF::AIFF::File::save(4);
+}
+
+bool RIFF::AIFF::File::save(int id3v2Version)
 {
   if(readOnly()) {
     debug("RIFF::AIFF::File::save() -- File is read only.");
@@ -135,7 +140,7 @@ bool RIFF::AIFF::File::save()
   }
 
   if(tag() && !tag()->isEmpty()) {
-    setChunkData("ID3 ", d->tag->render());
+    setChunkData("ID3 ", d->tag->render(id3v2Version));
     d->hasID3v2 = true;
   }
 
```

**Comment by scotchi** [comment]
It would have to be like the latter one because of the ambiguity, but as I said, I'd like to rework things in the the other places that ID3v2 tags are used so that it's something like:

    save(ID3v2::v3);

Rather than:

    save(3);

And then deprecate the existing methods.

**Comment by Moonbase59** [comment]
Ok, looks good, thanks for checking it! :-)

**Comment by scotchi** [comment]
Just for the record, I just tested with both iTunes and dbPowerAmp, and they both properly read ID3v2.4 in AIFF files.
