### ISSUE TITLE
TagLib 64bit Narrowing Conversions

### ISSUE THREAD

**Issue by XiNiHa** [taglib/taglib#928]
I am currently getting a large amount of unsafe type conversion(narrowing) warnings when I compile TagLib in MSVS 2017 Win64. While I don't think it would be a real problem, is it going to be fixed in the next release?

**Comment by scotchi** [comment]
Unless a patch is submitted, probably not. (I personally do very little development on Windows, and the folks who have typically maintained the Windows side of things are no longer active.)

**Comment by timnbraun** [comment]
Here's a patch that fixes this for the msys toolchain on Windows 11 

[0001-Add-_WIN64-support-in-refcounter-class.patch.txt](https://github.com/taglib/taglib/files/9873447/0001-Add-_WIN64-support-in-refcounter-class.patch.txt)

**Comment by neheb** [comment]
refcounter is gone

**Comment by sbooth** [comment]
This patch is no longer required.
