### ISSUE TITLE
Request for discussion: unified picture interface

### ISSUE THREAD

**Issue by supermihi** [taglib/taglib#94]
Hi,
I am thinking about implementing something similar to properties() / setProperties() for embedded cover art or other related pictures. Before starting to code I'd like to collect some opinions about the optimal interface for that.

The main problem seems to be that pictures are handled differently by different formats. 
- Apparently in both ID3v2 and FLAC each picture has a TYPE from a fixed enum AND an arbitrary string description.
- For APE there are items of type "BINARY". Can they have both a key and a Stringlist of values as well? The class is not documented. Is there any convention of how to put cover art in APE? Binary items could be everything not only images ...
- Similar problems in MP4: MP4::Item has "toCoverArtList()" but this probably does not work for all items!?

As for the interface, I imagine something like pictures() / setPictures() in analogy to the properties. What should the class returned from pictures() look like?
- a "PictureList" of "Picture" objects, where a "Picture" is something with a type, (optional?) description, and actual picture (plus perhaps mime type, ...)
- a "PictureMap", mapping picture type to (a list of?) picture(s) of that type. This might be overkill.

Then the question is of course how to deal with e.g. APE which does not know picture types. How should they be inferred?

Also some more implementation in the backends is needed which I'm afraid I cannot provide. For example, Ogg::Vorbis::File does not support pictures but according to  http://wiki.xiph.org/VorbisComment#Cover_art pictures are actually supported in OGG.

**Comment by Ecordonnier** [comment]
What's the state of your branch, MaxLeb? Is it something which could already be merged? I may have some time to help implement this feature, if required.

**Comment by fillobotto** [comment]
Is there any update about including pictures in a XiphComment tag?

**Comment by gogglesguy** [comment]
@fillobotto taglib has had support for pictures in a XiphComment for a while now:

https://github.com/taglib/taglib/blob/ebd3373d6d230f45cfb616b5af29b441126c4bb1/taglib/ogg/xiphcomment.h#L234-L257

**Comment by fillobotto** [comment]
@gogglesguy sure, but if we were talking about taglib2's unified picture interface, then it's empty.

https://github.com/taglib/taglib/blob/taglib2/taglib/ogg/xiphcomment.cpp#L198

I tried to clone and finish it by myself but I still get a signal 11 and I can't really find the reason of that.

**Comment by ufleisch** [comment]
Implemented with #1156.
