### ISSUE TITLE
Interest in Visual Studio project files?

### ISSUE THREAD

**Issue by vividos** [taglib/taglib#940]
Hi,
I'm the developer of winLAME and I'm using TagLib for (almost) all tag reading and writing in winLAME. I'm using TagLib by building it locally and checking in the .lib and .dll files so that the library doesn't have to be built for every AppVeyor build.
I created some project files for Visual Studio 2019 and I'd like to ask if there's interest in adding them to this repository via a PR?
The (automated) build can be found here:
https://github.com/vividos/winLAME/tree/master/buildlibs
The `build_taglib.cmd` batch file downloads the latest TagLib release, copies the Visual Studio project files into the folder structure and builds it with Visual Studio. The project files are here:
https://github.com/vividos/winLAME/tree/master/buildlibs/taglib-msvc/taglib
The files are currently put into the "taglib" folder, but I could move them elsewhere.

Are you interested in adding the files via a PR or other means?
Thanks!
Michael

**Comment by FestusHagen** [comment]
Why?
CMake creates them.

**Comment by vividos** [comment]
Ah I see, the build is done using CMake. I'm not familiar with it yet, but it may be a chance to see how it works. I'm closing this ticket then.
