### ISSUE TITLE
TagLib 2 corrupted M4A file

### ISSUE THREAD

**Issue by fillobotto** [taglib/taglib#945]
After editing, an m4a file is unplayable on any device.
I tried to inspect the problem and it looks like the track offset pointer in "stco" box is wrong. I have no clue how did it happen, but shouldn't a new edit process fix the wrong offset?

[Corrupted.zip](https://github.com/taglib/taglib/files/4112275/Corrupted.zip)

**Comment by scotchi** [comment]
We'd love to see a patch for this, but please not that "TagLib 2" is a development branch with currently nobody working on it.  It is not considered release quality.

**Comment by fillobotto** [comment]
@scotchi it's not really into mp4, so I can't give a solution by myself, but the code in charge of updating "stco" offsets it the same on the 1.x branch

**Comment by jonaski** [comment]
I can't reproduce. What tags did you change? Do you have the original file before it was corrupted or a file that is still gets corrupted if edited, if so can you send it to me jonas@jkvinge.net

**Comment by fillobotto** [comment]
@jonaski unfortunately not, I haven't received any similar issue requests so we can close it for now. I will comment back if there are more issue with further information
