### ISSUE TITLE
ID3v2::Tag::year() will only work for version 2.4 tags

### ISSUE THREAD

**Issue by finnianr** [taglib/taglib#949]
The code below will only work for `2.4` tags because `TDRC` is a `2.4` specific tag. The specs define the recording year/time as follows:
```
recording dates: 2.2: "TRD", 2.3: "TRDA"
recording time: 2.4: "TDRC"
```

```C++
unsigned int ID3v2::Tag::year() const
{
  if(!d->frameListMap["TDRC"].isEmpty())
    return d->frameListMap["TDRC"].front()->toString().substr(0, 4).toInt();
  return 0;
}
```

**Comment by scotchi** [comment]
This is incorrect.  In `ID3v2::FrameFactory` TYER frames are converted to TRDC frames.  In ID3v2.3 TRDA frames were not supposed to contain the year.

**Comment by finnianr** [comment]
> This is incorrect. In `ID3v2::FrameFactory` TYER frames are converted to TRDC frames. In ID3v2.3 TRDA frames were not supposed to contain the year.

Very good, so can I assume that the API is centered on 2.4 frame codes and that frames must only be referenced using 2.4 codes.

**Comment by scotchi** [comment]
Yes.

**Comment by scotchi** [comment]
Also, again, for general development questions, the mailing list is the preferred place for such.
