### ISSUE TITLE
id3v2 writer and reader for taglib_c

### ISSUE THREAD

**Issue by torikulhabib** [taglib/taglib#953]
I am having trouble attaching images using taglib_c to my application.
https://github.com/torikulhabib/niki
help me please.
https://github.com/taglib/taglib/blob/master/bindings/c/tag_c.h

**Comment by kdeng00** [comment]
What issues are you experiencing? Could you provide some code and your build configuration?

**Comment by torikulhabib** [comment]
I am constrained in the code attaching the picture to taglib_c
https://github.com/taglib/taglib/tree/master/bindings/c
only available for the album title ... and there is no attachment for the picture. this is the sample code that I used in valac https://github.com/torikulhabib/niki/blob/789356cc045231ebfbfc14e11509d269eed9bacb/src/MediaEditor.vala#L378

**Comment by kdeng00** [comment]
Hey @torikulhabib, check out this branch to see if it meets your needs:
https://github.com/kdeng00/taglib/tree/attached_picture_c_binding

I added some wrappers for interacting with covers. Note: It's only applicable for certain use cases. Can be further improved.

**Comment by kdeng00** [comment]
Hey @torikulhabib,

Check out my branch again. I added some wrappers similar to the ones to mentioned in the email.

To attach the an image follow this steps:
1. Create TagLib::MPEG::File wrapper
2. Create TagLib::ID3v2::Tag wrapper
3. Check if the picture frame list is empty
4. (Optional): Remove any **APIC** (Frame where cover art is stored) if necessary
5. Create ID3v2::AttachedPicture wrapper
6. Set the picture type
7. Set the picture
8. Add the ID3v2::AttachedPicture wrapper to ID3v2::Tag wrapper
9. Save the TagLib::MPEG::File song file
10. Free any resources

Check the [tag_c.h](https://github.com/kdeng00/taglib/blob/attached_picture_c_binding/bindings/c/tag_c.h#L140) file. Starts at line 140 and ends at 238

**Comment by torikulhabib** [comment]
thanks this working.
and need add set mimetype;

**Comment by kdeng00** [comment]
I can add that. I'll clean up some things and open a PR to get it in the master branch of the master repo

**Comment by torikulhabib** [comment]
add delete all tag please

**Comment by kdeng00** [comment]
Delete all tags?

**Comment by torikulhabib** [comment]
i mean clear all tag.
there are option to clear all.

**Comment by kdeng00** [comment]
I'll let you know when I get to it

**Comment by kdeng00** [comment]
Hey @torikulhabib, I made the change to set the mime type and also updated the code to comply with the coding convention.

The functionality to clear all tags does not fall under this issue and a separate issue should be created.

**Comment by kdeng00** [comment]
Changing the name of the issue won't change the situation. If that was the case then all GitHub repos would have a few issues with constant name changes. I'm going to make a PR for the original issue.

**Comment by ufleisch** [comment]
Implemented with #1159.
