### ISSUE TITLE
Mp3 duration might be miscalculated with certain mp3 files

### ISSUE THREAD

**Issue by mulgurul** [taglib/taglib#957]
I'm having problems with getting the correct duration from a mp3 file generated from Googles text to speech API. I have attached a short sample file.
Using Taglib I get a duration of 00:00:04.4600000
Using NLayer I get a duration of 00:00:03.9360000
Viewing the file with MediaInfo from MediaArea.net I get a duration of  3.936s
Opening the file with VLC I get a duration of 3 seconds as well as viewing the audio length in windows file explorer.
The correct length seems to be 3.9360000s.
I've inspected the first frameheaders and everything seems fine.
It's a a Layer 3 mpeg-2 file according to the first frameheader, with fixed bitrate.
Sample audio file is attached.

Br, Peter Meldgaard

[p_2-1.zip](https://github.com/taglib/taglib/files/4591836/p_2-1.zip)

**Comment by SomalRudra** [comment]
Hi !
since you're working on this,can u help me clearing a doubt?
 explicit FileRef(File *file);
this constructor should take
     FILE *songfile;
    TagLib::FileRef f(&songfile);
as a call to the contructor.
But it is showing an error.
can u help?

**Comment by scotchi** [comment]
`FILE *` and `TagLib::File *` aren't the same thing.

**Comment by SomalRudra** [comment]
how should I send a mp3 file as a parameter to the constructor in that case?

**Comment by ufleisch** [comment]
I cannot reproduce this with your example file, I get 3936 ms, which seems to be the correct value.
