### ISSUE TITLE
TagLib cannot get AudioProperties with some wav files.

### ISSUE THREAD

**Issue by BLumia** [taglib/taglib#959]
I use TagLib to get audio properties like sample rate and bitrate, it works fine with most of my audio files but some wav files doesn't works.

## To Reproduce:

 1. Download the example code [examples/tagreader.cpp](https://github.com/taglib/taglib/blob/master/examples/tagreader.cpp)
 2. Make sure taglib is installed, then build with ```g++ `pkg-config taglib --cflags --libs` tagreader.cpp```.
 3. Download [test.zip](https://github.com/taglib/taglib/files/4709696/test.zip) and unzip it, and pass the wav file path to the built `a.out` executable.
 4. See the result.

```
...
-- TAG (properties) --
-- AUDIO --
bitrate     - 0
sample rate - 0
channels    - 0
length      - 0:00
```

TagLib Version: 1.11.1-4 under Archlinux. ( I also did test with the master branch under windows, build it manually and it also doesn't works ).

Let me know if you need other details. Thanks.

**Comment by ufleisch** [comment]
When you open the attached file with a debug build of TagLib, you will see the following output:

```
TagLib: RIFF::WAV::Properties::read() - Non-PCM format, but 'fact' chunk not found.
```

The `wFormatTag` in the `fmt ` chunk is 3, which means `WAVE_FORMAT_IEEE_FLOAT`. "New Multimedia Data Types and Data Techniques" (Microsoft, 1994, RIFFNEW.pdf, see also http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html) states

> The fact chunk is required for all new WAVE formats. The chunk is not required for the standard WAVE_FORMAT_PCM files.

As a `fact` chunk is missing in the attached file, it seems that this file is not valid. Editing the tags is still possible. Maybe it would be possible to get the properties correctly in this case without the information in the fact chunk (which is actually only the number of samples).

**Comment by scotchi** [comment]
Just for a little context on why TagLib is typically pretty strict on corrupted or non-conformant files:

Very often when files are non-conformant there's garbage somewhere in the file.  Historically, a lot of crashes and hangs (i.e. parsing the whole file) came from trying to make sense of bogus files, and one of the easiest ways to avoid that was to bail out as soon as a problem was detected.

**Comment by BLumia** [comment]
> ...on corrupted or non-conformant files:...

I'm not pretty sure about this, the audio file is rendered by fl studio without any other step to modify the file itself. Also, since the spec says "The chunk is not required for the standard WAVE_FORMAT_PCM files", so maybe it can't be treated as a "corrupted" file I guess?

**Comment by scotchi** [comment]
@BLumia That comment was mostly for @ufleisch who's been looking at a few bug reports in this general category of issues.

**Comment by scotchi** [comment]
Also, reading more carefully, I think @ufleisch is right that the file is invalid:  it's not PCM, and for all non-PCM .wav files, a data chunk is required.  So, yeah, it does fall into that category of deciding if and when to continue trying to parse non-compliant files.

**Comment by BLumia** [comment]
Yeah, so that's why I'm saying I'm not pretty sure about this since the file is rendered by a property software and there might be no way to let "upstream" fix the "bug" :/

And I'd like to know if that's a wontfix kind of issue or if it's still possible to support from the taglib library. I'll also try to send a ticket to Image-line and see if I could get any response, I only need this as a read-only feature though...

**Comment by BLumia** [comment]
As a note here, the render option in case we might need:

![image](https://user-images.githubusercontent.com/10095765/101282439-29fcd600-3810-11eb-9b21-e017353411e1.png)

with version v20.7.2 build 1863. To reproduce, we need to set the WAV bit depth to 32-bit float and do the render. It *can* be a bug from fl studio.

**Comment by ufleisch** [comment]
After having another look at it, I think that we should calculate the bitrate for such WAV files. It can be done in the same way as for PCM files because the number of bits per sample is constant and known. I have made a pull request.

**Comment by BLumia** [comment]
Seems resolved in https://github.com/taglib/taglib/pull/980 , already tested with the current master HEAD build (89fb62c), and now it works fine!

Thanks for the fix! Closing now.
