### ISSUE TITLE
Receive a System.NotImplementedException

### ISSUE THREAD

**Issue by EricOuellet2** [taglib/taglib#964]
Receive a System.NotImplementedException: 'Unknown type/count 3/0 (0)'

Windows - .net Core 3.1 project. Using this file newly created by a new Sony camera (a6400):
![DSC00720](https://user-images.githubusercontent.com/10049632/86411603-2d9d9700-bc8b-11ea-8ea6-e70b1819b151.JPG)

**Comment by scotchi** [comment]
This seems to be an issue with TagLib#, which is a separate project.  TagLib proper is neither .NET, nor does it do anything related to images.
