### ISSUE TITLE
`File::properties()` keys do not align with ID3v2 frames

### ISSUE THREAD

**Issue by quyer** [taglib/taglib#966]
I'm trying to use taglib to read ID3v2 frames from an mp3 file. Using `mid3v2`, I have set one of the frames, `--WXXX`. When I use the supplied `example/tagreader.cpp` file, the properties map is shown to contain a `URL` key. Is there a way for me to access an ID3v2 frame by its name (`WXXX`) rather than by `URL` in the PropertyMap? Thanks.

**Comment by scotchi** [comment]
Yes, you can just use the relevant function in the ID3v2::Tag:

https://taglib.org/api/classTagLib_1_1ID3v2_1_1Tag.html#ab954025fb0bddd3c4a65cb71c385fb58
