### ISSUE TITLE
Neverending or heavyweight MPEG::File::findID3v2 full scan

### ISSUE THREAD

**Issue by fcartegnie** [taglib/taglib#968]
The logic behind MPEG::File::findID3v2()
is to scan the full file if no ID3 tag or MPEG sync frame is found on first offset.

Before 1.12, it scans on a first pass until it finds the ID3 tag, that may never happen.
On a second pass it scans for an MPEG sync frame.

Since 1.12 this has been optimized to find the first of both.
Still, the file can be unknown content and perform a full scan.

But unless Taglib is only designed to scan files (small ones) this is wrong.
Files could be huge, on a slow media, and if not MP2/MP3 it will always perform a full scan.
Even worse case if the IOStream is, surprisingly, a stream, it will never end.

To me, this behaviour should not be default unless specified.
I have a custom patch for 1.11, but that's not fully correct since ReadStyle supposely depends on readProperties flag.
https://github.com/fcartegnie/taglib/commit/ab30255ca71e7afe748c9b4e6acd5be5200ecfb0

**Comment by timusus** [comment]
Personally (and I don't represent TagLib), I don't think this is necessarily wrong, or that it shouldn't be the default. If you pass a file to TagLib and ask it to find the metadata, I think it's perfectly valid to scan the entire contents of the file. 

I think it's fine to have an option to not scan the entire file, but I don't think that should necessarily be the default behaviour.

**Comment by ufleisch** [comment]
@Tolriq, author of #1150: The main problem I see with this patch is that it changes the behavior of TagLib. What about changing the "level" where the VLC behavior kicks in from `Average` to `Fast`, so that the current default read style `Average` keeps the current behavior and one has to set it to fast to get the VLC behavior?

```
  if(readStyle == Properties::Fast)
    return -1;
```

**Comment by Tolriq** [comment]
That works for me, for remote files I'll always pass Fast anyway.

Not sure the patch can be applied with all the recent rework.

I lack time currently but if no one have time before I could port the patch if it's wanted.

**Comment by ufleisch** [comment]
I already have ported it. I will have to test it and probably add some unit tests before creating a pull request.

**Comment by ufleisch** [comment]
Fixed with #1151.
