### ISSUE TITLE
Can not read tag info for files using Hebrew characters

### ISSUE THREAD

**Issue by YairAtInnovo** [taglib/taglib#972]
Hello,

I build the latest TagLib from the repository.
When trying to read the tags of a song with Hebrew characters (attached), the 'tagreader' utility can not display any tags written in Hebrew.
I'm using macOS 10.15.6.

Yairs-MBP:examples yair$ ./tagreader /Users/yair/Music/iTunes/iTunes\ Music/Music/עידן\ עמדי/בזמן\ האחרון/02\ בזמן\ האחרון.m4a 
******************** "/Users/yair/Music/iTunes/iTunes Music/Music/עידן עמדי/בזמן האחרון/02 בזמן האחרון.m4a" ********************
-- TAG (basic) --
title   - "???? ??????"
artist  - "???? ????"
album   - "???? ??????"
year    - "2013"
comment - ""
track   - "2"
genre   - "Israeli"
-- TAG (properties) --
ALBUM       - "???? ??????"
ALBUMARTIST - "???? ????"
ARTIST      - "???? ????"
ARTISTSORT  - "Idan Amedi"
COMPILATION - "0"
COMPOSER    - "Idan Amedi"
COPYRIGHT   - " 2013 A.M productions LTD. / Tedy Productions LTD. / Mobile1Music LTD"
DATE        - "2013-02-27T08:00:00Z"
DISCNUMBER  - "1/1"
GENRE       - "Israeli"
TITLE       - "???? ??????"
TRACKNUMBER - "2/11"
-- AUDIO --
bitrate     - 257
sample rate - 44100
channels    - 2
length      - 3:33

Thanks for your help.
[‎⁨02 בזמן האחרון⁩.m4a.zip](https://github.com/taglib/taglib/files/5184503/02.m4a.zip)

**Comment by scotchi** [comment]
TagLib parses Hebrew just fine; it's just that the examples come from a time before most terminals used UTF-8, so the examples print things in ISO-8859-1 instead, which breaks on UTF-8 (which is obviously required for Hebrew).

If you for example change this in `tagreader`, it'll print Hebrew correctly:

      cout << "title   - \"" << tag->title().to8Bit(true) << "\"" << endl;

**Comment by YairAtInnovo** [comment]
It worked. Thanks,
Yair
