### ISSUE TITLE
m4a file causes crash on KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [taglib/taglib#974]
I have already reported this crash to KDE devs
https://bugs.kde.org/show_bug.cgi?id=427448

it's caused by the file that you can download on the following link.
http://www.mediafire.com/file/8ltxilto0bxc7zq/zero-length-mdat.m4a/file

**Comment by ufleisch** [comment]
According to the comments in https://bugs.kde.org/show_bug.cgi?id=427448 this is fixed in git.
