### ISSUE TITLE
Linking error 

### ISSUE THREAD

**Issue by aslanyan13** [taglib/taglib#976]
Trying to connect library to my Qt project and getting following errors:

```
In function `Z5qMainiPPc':
undefined reference to `_imp___ZN6TagLib8FileNameC1EPKw'
undefined reference to `_imp___ZN6TagLib7FileRefC1ENS_8FileNameEbNS_15AudioProperties9ReadStyleE'
undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
collect2.exe: error: ld returned 1 exit status
```

**Comment by scotchi** [comment]
Hi - I suspect you aren't actually linking to TagLib, and need to configure your project to do so.  However, our issue tracking system isn't the appropriate place for basic C++ development support.  You're welcome to email our [list](mailto:taglib-devel@kde.org) though (there I'd recommend mentioning your platform and compiler) where you may run into other developers that are using a similar setup.
