### ISSUE TITLE
FileTypeResolver virtual destructor

### ISSUE THREAD

**Issue by gfgit** [taglib/taglib#979]
Abstract class:
`class FileTypeResolver`
declared in  [fileref.h, line L92](https://github.com/taglib/taglib/blob/91b00b17b253dad0d7037232ef7033c88bdd28bd/taglib/fileref.h#L92)
**has no virtual destructor** but is deleted in the list destructor:
`ResolverList fileTypeResolvers;` at [fileref.cpp line 61](https://github.com/taglib/taglib/blob/91b00b17b253dad0d7037232ef7033c88bdd28bd/taglib/fileref.cpp#L61)

**Comment by ufleisch** [comment]
Duplicate of #477
