### ISSUE TITLE
FLAC metadata blocks with 0 length invalidate the file

### ISSUE THREAD

**Issue by sbooth** [taglib/taglib#98]
Commit ad9ffc62e6fac5c47f46eb96b39c614e32742eb5 added the behavior where FLAC metadata blocks with a length of 0 cause the file to be marked as invalid.  I've received numerous reports from users with FLACs purchased/downloaded from third party websites that their tags are no longer showing up.  Specifically, it seems WaveLab is creating seektables with a length of 0 causing tag parsing to fail.  A 0 length seektable does not conform to the FLAC spec, however `metaflac` handles the files correctly and I believe the behavior might be a bit too strict.

**Comment by FestusHagen** [comment]
#637 Closes this?

-Enjoy
