### ISSUE TITLE
taglib_file_new from memory

### ISSUE THREAD

**Issue by dajuric** [taglib/taglib#987]
Create a new function where files can be read from memory and written to memory. That would be useful when files are obtained from HTTP source using curl.

**Comment by ufleisch** [comment]
You can already initialize a `ByteVectorStream` from a `ByteVector` and then create a `FileRef` (or a subclass of `File`) from it.

**Comment by scotchi** [comment]
I think this person was asking for such in the C bindings.  I have no particularly strong feelings on such.

**Comment by ufleisch** [comment]
Implemented with #1162.
