### ISSUE TITLE
TagLib - Segfault when fetching tag.

### ISSUE THREAD

**Issue by apoorv569** [taglib/taglib#992]
I'm using `TagLib` to get tags from audio files for my application that I'm making using wxWidgets. I have set it up to fetch multiple tags like artist, title, album and all, some files load fine, but some when loaded crashes my application and gives error saying,
```
./build.sh: line 12:  5891 Segmentation fault      ./SampleBrowser
```

I tried running with `GDB`,
```
Thread 1 "SampleBrowser" received signal SIGSEGV, Segmentation fault.
Browser::AddSamples (this=0x555555a73e00, file=...) at ../src/Browser.cpp:248
248         std::string Artist = File.tag()->artist().to8Bit(true);
(gdb)
```

Here is the function that is responsible for fetching tags,
```
void Browser::AddSamples(wxString file)
{
    TagLib::FileRef f (static_cast<const char*>(file), true, TagLib::AudioProperties::ReadStyle::Average);

    if (!f.isNull() && f.tag() && f.audioProperties())
    {
        TagLib::Tag* tag = f.tag();
        TagLib::AudioProperties* properties = f.audioProperties();

        TagLib::String Artist = tag->artist();
        TagLib::String Album = tag->album();
        TagLib::String Genre = tag->genre();
        TagLib::String Title = tag->title();
        TagLib::String Comment = tag->comment();

        int seconds = properties->length() % 60;
        int minutes = (properties->length() - seconds) / 60;

        int Bitrate = properties->bitrate();
        int Channels = properties->channels();
        int Length = properties->lengthInMilliseconds();
        int LengthSec = properties->lengthInSeconds();
        int SampleRate = properties->sampleRate();

        wxString Path = file;
        wxString Filename = file.AfterLast('/').BeforeLast('.');

        Data.clear();
        Data.push_back(false);
        Data.push_back(Filename);
        Data.push_back(wxString::FromUTF8(Artist.toCString(true)));
        Data.push_back(wxString::Format("%d", Channels));
        Data.push_back(wxString::Format("%d", Length));
        Data.push_back(wxString::Format("%d", SampleRate));
        Data.push_back(wxString::Format("%d", Bitrate));
        Data.push_back(wxString::FromUTF8(Comment.toCString(true)));

        SampleListView->AppendItem(Data);

        db.InsertSample(0, Filename.ToStdString(), Artist.to8Bit(true),
                        Channels, Length, SampleRate, Bitrate,
                        Comment.to8Bit(true), Path.ToStdString());
    }
    else
    {
        for (int i = 0; i < f.isNull(); i++)
        {
            const wxString& msg = wxString::Format("Error! Cannot open file %s", f.file()->name());
            wxMessageDialog *msgDialog = new wxMessageDialog(NULL, msg, "Error", wxOK | wxICON_ERROR);
            msgDialog->ShowModal();
        }
    }
}
```
I have this `AddSamples()`, that I call inside 2 other functions, as I have different ways of adding files to my application, via drag and drop and by file browser inside the application, both of which uses this `AddSamples()` to get tags and insert them in the `wxDataViewListCtrl` and `SQLite3` database. `file` here is the parameter passed in the function, which is of `wxString` type. I am able to successfully add files to the application using `AddSamples()`, but say there are 5 files in a directory, 3 will add fine, but other 2 crashes the application and causes segmentation fault.

![Peek 2021-02-06 04-46](https://user-images.githubusercontent.com/53279454/107098995-96a74780-6836-11eb-9355-e9dab3625da1.gif)
As you can see, there are 30 files in the directory, `Kick 001` and `Kick 006` fails to add to the application. I tried opening those 2 files in a audio player, it plays fine, file is not corrupt. Also say user drags and drops 1000+ files at once, a lot of files are going to fail to be added this way.

**Comment by ufleisch** [comment]
What puzzles me a bit is that in your stack trace it says that it crashes at a line (probably because `File.tag()` is null)

```
std::string Artist = File.tag()->artist().to8Bit(true);
```

but in the listing you provide, no such line exists, there is another line

```
TagLib::String Artist = tag->artist();
```

but this line is inside an `if` statement checking if `tag` is null. Are you sure that the code you are running is the code in the listing? Maybe you are running an old version of your code. You could print more surrounding lines from `gdb` by using the `l` command.

**Comment by apoorv569** [comment]
> What puzzles me a bit is that in your stack trace it says that it crashes at a line (probably because `File.tag()` is null)
> 
> ```
> std::string Artist = File.tag()->artist().to8Bit(true);
> ```
> 
> but in the listing you provide, no such line exists, there is another line
> 
> ```
> TagLib::String Artist = tag->artist();
> ```
> 
> but this line is inside an `if` statement checking if `tag` is null. Are you sure that the code you are running is the code in the listing? Maybe you are running an old version of your code. You could print more surrounding lines from `gdb` by using the `l` command.

Sorry, my bad, I forgot to mention that I updated the function and added that `if f.isNull()` later, before it was giving segfault, now it shows that error dialog that I have in `else` statement.
![2021-02-06_20-04](https://user-images.githubusercontent.com/53279454/107121111-ad8d7e80-68b6-11eb-8e14-56789a64c241.png)

So the app doesn't crash. But I wanna know why certain are not able to load correctly with `TagLib` ?

**Comment by scotchi** [comment]
My guess would be that it's either a corrupted file, or the permissions disallow reading.  If you've compiled with debugging on, there's usually a semi-useful message in those cases.

**Comment by apoorv569** [comment]
> My guess would be that it's either a corrupted file, or the permissions disallow reading. If you've compiled with debugging on, there's usually a semi-useful message in those cases.

The permission for all files are same as the others that are able to load properly,
![2021-02-06_04-10](https://user-images.githubusercontent.com/53279454/107121893-d31c8700-68ba-11eb-9c25-2cb13b6a03f2.png)

Here only the `Kick 001` and `Kick 006` fails rest of the files load fine.

I also checked these files with other audio player, and they play fine. However I also tried converting them to other formats with `ffmpeg` by using `ffmpeg -i filename new_filename` to `.mp3`, `.ogg` and even made another copy of the `.wav` then it loads fine. Also there are other files on my system that I tried to load, a big directory, it loads some files and for other files it keeps showing that error dialog box.

**Comment by scotchi** [comment]
I'd stick with the guess that they're corrupted in one way or another.  A lot of players try harder to recover from corruption or standard non-conformance than TagLib does.  Again, do you have debugging enabled?  Checking the output would be useful as most places where TagLib bails out, it prints a message saying why.

**Comment by apoorv569** [comment]
> I'd stick with the guess that they're corrupted in one way or another. A lot of players try harder to recover from corruption or standard non-conformance than TagLib does. Again, do you have debugging enabled? Checking the output would be useful as most places where TagLib bails out, it prints a message saying why.

I'm not very good at debugging, should I put `breakpoint` at where I'm checking `if (f.isNull())`? And What am I looking for?

**Comment by scotchi** [comment]
Are you using the system TagLib or one that you've compiled yourself?  It's probably useful to compile TagLib for yourself and link your application against that.  If you compile with `-DCMAKE_BUILD_TYPE=Debug` it'll probably tell you exactly why it's bailing out.

**Comment by apoorv569** [comment]
> Are you using the system TagLib or one that you've compiled yourself? It's probably useful to compile TagLib for yourself and link your application against that. If you compile with `-DCMAKE_BUILD_TYPE=Debug` it'll probably tell you exactly why it's bailing out.

As of now, I'm using `TagLib` from my OS repository, I will try to compile `TagLib` myself with `-DCMAKE_BUILD_TYPE=Debug` and try with that and get back to you.

**Comment by apoorv569** [comment]
I put a breakpoint on the `if (f.isNull() ...)` line tried debugging here is the output, with back trace as well.
```
Reading symbols from SampleBrowser...
(gdb) b ../src/Browser.cpp:254
Breakpoint 1 at 0x2a3cc: file ../src/Browser.cpp, line 254.
(gdb) run
Starting program: /home/apoorv/repos/cpp-projects/wxWidgets/SampleBrowser/build/Sa
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2404640 (LWP 11977)]
[New Thread 0x7ffff1c03640 (LWP 11978)]
10:57:26: Debug: Size H: 720
10:57:26: Debug: Size W: 1280
10:57:26: Debug: Table created successfully.
10:57:26: Debug: Autoplay: 0
10:57:26: Debug: Loop: 0
10:57:26: Debug: Muted: 0
[New Thread 0x7ffff0b77640 (LWP 11979)]
[New Thread 0x7fffe36ee640 (LWP 11980)]
[New Thread 0x7fffe2eed640 (LWP 11981)]

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.244: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.244: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.266: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.266: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.283: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(SampleBrowser:11933): Gtk-CRITICAL **: 10:57:27.283: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
[Thread 0x7ffff0b77640 (LWP 11979) exited]

Thread 1 "SampleBrowser" hit Breakpoint 1, Browser::AddSamples (this=0x555555a72000, file=...) at ../src/Browser.cpp:254
254         if (!f.isNull() && f.tag() && f.audioProperties())
(gdb) l
249
250     void Browser::AddSamples(wxString file)
251     {
252         TagLib::FileRef f (static_cast<const char*>(file), true, TagLib::AudioProperties::ReadStyle::Average);
253
254         if (!f.isNull() && f.tag() && f.audioProperties())
255         {
256             TagLib::Tag* tag = f.tag();
257             TagLib::AudioProperties* properties = f.audioProperties();
258
(gdb) l
259             TagLib::String Artist = tag->artist();
260             TagLib::String Album = tag->album();
261             TagLib::String Genre = tag->genre();
262             TagLib::String Title = tag->title();
263             TagLib::String Comment = tag->comment();
264
265             int seconds = properties->length() % 60;
266             int minutes = (properties->length() - seconds) / 60;
267
268             int Bitrate = properties->bitrate();
(gdb) bt
#0  Browser::AddSamples(wxString) (this=0x555555a72000, file=...) at ../src/Browser.cpp:254
#1  0x000055555557f2e7 in Browser::OnClickDirCtrl(wxCommandEvent&) (this=0x555555a72000, event=...) at ../src/Browser.cpp:321
#2  0x00007ffff7687dde in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#3  0x00007ffff768815b in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#4  0x00007ffff76881f1 in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#5  0x00007ffff76882ac in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#6  0x00007ffff7688382 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#7  0x00007ffff7b96cba in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#8  0x00007ffff7b96cba in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#9  0x00007ffff7b96cba in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#13 0x00007ffff7bc4a51 in wxGenericDirCtrl::OnItemActivated(wxTreeEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#14 0x00007ffff7687dde in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#15 0x00007ffff7687edc in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib/libwx_baseu-3.0.so.0
#16 0x00007ffff768821e in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#17 0x00007ffff76882ac in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#18 0x00007ffff7688382 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#19 0x00007ffff7b96cba in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#20 0x00007ffff7bfa37e in wxScrollHelperEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#21 0x00007ffff7c147b3 in wxGenericTreeCtrl::OnMouse(wxMouseEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#22 0x00007ffff7687dde in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#23 0x00007ffff7687edc in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib/libwx_baseu-3.0.so.0
#24 0x00007ffff768821e in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#25 0x00007ffff76882ac in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#26 0x00007ffff7688382 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#27 0x00007ffff7bfa37e in wxScrollHelperEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#28 0x00007ffff76880d7 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.0.so.0
#29 0x00007ffff79da512 in  () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#30 0x00007ffff6724f6f in  () at /usr/lib/libgtk-3.so.0
#31 0x00007ffff643c052 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#32 0x00007ffff64649c5 in  () at /usr/lib/libgobject-2.0.so.0
#33 0x00007ffff6457bcb in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#34 0x00007ffff6458b00 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#35 0x00007ffff69eb9f5 in  () at /usr/lib/libgtk-3.so.0
#36 0x00007ffff6883e15 in  () at /usr/lib/libgtk-3.so.0
#37 0x00007ffff688516d in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#38 0x00007ffff65de413 in  () at /usr/lib/libgdk-3.so.0
#39 0x00007ffff662f114 in  () at /usr/lib/libgdk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--RET
#40 0x00007ffff6347a84 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff639b9b1 in  () at /usr/lib/libglib-2.0.so.0
#42 0x00007ffff6346fd3 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#43 0x00007ffff688222f in gtk_main () at /usr/lib/libgtk-3.so.0
#44 0x00007ffff79b8b26 in wxGUIEventLoop::DoRun() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#45 0x00007ffff756037e in wxEventLoopBase::Run() () at /usr/lib/libwx_baseu-3.0.so.0
#46 0x00007ffff7526766 in wxAppConsoleBase::MainLoop() () at /usr/lib/libwx_baseu-3.0.so.0
#47 0x00007ffff75a5199 in wxEntry(int&, wchar_t**) () at /usr/lib/libwx_baseu-3.0.so.0
#48 0x000055555557414c in main(int, char**) (argc=1, argv=0x7fffffffe178) at ../src/app.cpp:3
(gdb)
```
I also build `TagLib` from source with the flag `-DCMAKE_BUILD_TYPE=Debug`, by cloning this repository, but I have never linked manually, if you can point me how I can link manuallly, and which library I have to link with. I am currently using `Meson` to build my project, and I have this line that links to `TagLib` from the OS repository version.
```
taglib = dependency('taglib')
.
.
.

exec = executable('SampleBrowser', src,
  dependencies : [wx, taglib, sqlite3, yaml],
```

**Comment by scotchi** [comment]
The honest truth is that I don't know how to do this in Meson, but I fear we're getting too far into "C++ support" territory and not really looking into a TagLib issue.  I'd say with a fairly high degree of certainty that there's something wrong with the files you're looking at.  Feel free to attach one here for us to look at.  Past that, I think you'd be better off using the mailing list for help on general development questions.

**Comment by apoorv569** [comment]
I understand, here are the 2 files that fails to load.
[taglib_test.tar.gz](https://github.com/taglib/taglib/files/5938403/taglib_test.tar.gz)

**Comment by ufleisch** [comment]
Thanks for the example files. With version 1.11.1, I cannot read them either, but with the latest code from master or the current [v1.12-beta-2](https://github.com/taglib/taglib/archive/v1.12-beta-2.zip) they can be read, so I suggest that you use this version.

**Comment by scotchi** [comment]
Ok, with that, I think we can go ahead and mark this one closed.

**Comment by apoorv569** [comment]
> Thanks for the example files. With version 1.11.1, I cannot read them either, but with the latest code from master or the current [v1.12-beta-2](https://github.com/taglib/taglib/archive/v1.12-beta-2.zip) they can be read, so I suggest that you use this version.

Thank you, I will try with new version. I also wanted to know if there is a way to check if the file the user is adding is valid, like it is a audio file and not a text document or something? So I can handle that case as well.

**Comment by ufleisch** [comment]
Have a look at _examples/tagreader.cpp_. Open the file with a `FileRef`, check `isNull()`, `tag()`, and `audioProperties()`. If the file is not a supported audio file, you won't get any `audioProperties()`. But I guess you know that since this is all done in your example listing.

**Comment by apoorv569** [comment]
> Have a look at _examples/tagreader.cpp_. Open the file with a `FileRef`, check `isNull()`, `tag()`, and `audioProperties()`. If the file is not a supported audio file, you won't get any `audioProperties()`. But I guess you know that since this is all done in your example listing.

I don't think this is a good solution, as the previous version was not even able to read some audio files, and what if some audio file was ripped or downloaded from somewhere and it does not have tags on it. I am already checking for `isNull()` `tag()` and `audioProperties()` and if I try to open say a text document, the application crash with seg fault. `TabLib` should really have a function that checks for is file is a valid audio file type or something.

**Comment by ufleisch** [comment]
The crash you experienced was with an old version of your code where the check whether `tag()` returns not null was missing. In the latest TagLib version, each `File` class has a static `isSupported()` method, which checks the file contents. You do not need to use this explicitly as it is used by the `FileRef` constructors. I am using TagLib for my own project [Kid3](https://kid3.kde.org) since 2006, and the crashes I had with TagLib were when I used an iterator which was invalidated by some of TagLib's `remove...` methods which offer an easier API than STL `erase()`, but unfortunately invalidate iterators on the container without returning a new valid iterator. The other crash I remember was using a stream after its file had been closed. But I have never seen a crash when opening an invalid file. If you have such a file, feel free to provide it so the crash can be fixed. By the way: I tested the current version with files created by an adapted vesion of [Fuzzbox](https://github.com/iSECPartners/fuzzbox/), and none of the created files led to a crash.

**Comment by apoorv569** [comment]
> The crash you experienced was with an old version of your code where the check whether `tag()` returns not null was missing. In the latest TagLib version, each `File` class has a static `isSupported()` method, which checks the file contents. You do not need to use this explicitly as it is used by the `FileRef` constructors. I am using TagLib for my own project [Kid3](https://kid3.kde.org) since 2006, and the crashes I had with TagLib were when I used an iterator which was invalidated by some of TagLib's `remove...` methods which offer an easier API than STL `erase()`, but unfortunately invalidate iterators on the container without returning a new valid iterator. The other crash I remember was using a stream after its file had been closed. But I have never seen a crash when opening an invalid file. If you have such a file, feel free to provide it so the crash can be fixed. By the way: I tested the current version with files created by an adapted vesion of [Fuzzbox](https://github.com/iSECPartners/fuzzbox/), and none of the created files led to a crash.

I found the problem, that was causing error in my code, when I try to load a file that is not audio,
```
const wxString& msg = wxString::Format("Error! Cannot open file %s", f.file()->name());
```
it was because of this error message in the `else` statement, I was passing `f.file()->name()` which when its not a audio file, it cannot fetch the filename for it, I changed it, now it works.

Thanks.

**Comment by scotchi** [comment]
Just for the record, that code will also always be wrong and crash-prone:  you're taking a reference to a temporary value.  That line could very easily crash even if the file was valid.

**Comment by apoorv569** [comment]
> Just for the record, that code will also always be wrong and crash-prone: you're taking a reference to a temporary value. That line could very easily crash even if the file was valid.

You mean this `const wxString& msg`? this is in the `else` statement, when the file is `null` and I have this because the `wxMessageDialog` takes `const wxString& message` as parameter.

**Comment by jonaski** [comment]
The parameter to the function should be a reference to your string, not a reference to the return value of `wxString::Format`.
Use: `const wxString msg`

**Comment by scotchi** [comment]
That's very incorrect and again, will cause crashes.  If you turn on `-Wall` (all warnings) or similar, your compiler will tell you just that.  The correct return type is just `wxString`.
