### ISSUE TITLE
taglib 1.12 did not get marked as "latest release"

### ISSUE THREAD

**Issue by chenrui333** [taglib/taglib#995]
👋  just a reminder that the latest release `1.12` did not get marked as "latest release"
![image](https://user-images.githubusercontent.com/1580956/108000871-f6c98680-6fb8-11eb-806f-254aef736040.png)

---

relates to https://github.com/Homebrew/homebrew-core/pull/71186

**Comment by jonaski** [comment]
It's a tag, not a release.

**Comment by scotchi** [comment]
That's because the release is schedule for tomorrow, not today.  It was an accident (@ufleisch wasn't used to how the website updates work) that the website got updated today.

**Comment by chenrui333** [comment]
Oh ok, I might released homebrew formula update too early then. 😅
