### ISSUE TITLE
LGPL 2.1 or 3.0?

### ISSUE THREAD

**Issue by uklotzde** [taglib/taglib#999]
The homepage links to LGPL 3.0 but this repo still contains the license text of the LGPL 2.1.

It is also not specified if the license term "any later version" applies or not.

Background: We (Mixxx) have prepared an update of the vcpkg package. I will use LGPL 2.1 in the package description that applies to version 1.12.

**Comment by Be-ing** [comment]
The [code headers](https://github.com/taglib/taglib/blob/master/taglib/flac/flacfile.h#L9) say LGPL 2.1 or MPL 1.1, no "or later".

**Comment by uklotzde** [comment]
https://github.com/microsoft/vcpkg/pull/16266

**Comment by scotchi** [comment]
To be clear, the TagLib homepage doesn't explicitly link to the LGPL 3.0; it just links to the old, standard gnu.org LGPL link, and that now redirects to the LGPL.  That link on the TagLib home page predates the LGPL 3.0 even existing.  (TagLib is almost 20 years old.)
